// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _contact_discovery_HH_
#define _contact_discovery_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "contact_discoverybkb.h"
#include "contact_discovery_AXILiteS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_AXILITES_ADDR_WIDTH = 7,
         unsigned int C_S_AXI_AXILITES_DATA_WIDTH = 32>
struct contact_discovery : public sc_module {
    // Port declarations 26
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_lv<512> > db_in_V_V_TDATA;
    sc_in< sc_logic > db_in_V_V_TVALID;
    sc_out< sc_logic > db_in_V_V_TREADY;
    sc_out< sc_lv<8> > results_out_V_TDATA;
    sc_out< sc_logic > results_out_V_TVALID;
    sc_in< sc_logic > results_out_V_TREADY;
    sc_in< sc_logic > s_axi_AXILiteS_AWVALID;
    sc_out< sc_logic > s_axi_AXILiteS_AWREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_AWADDR;
    sc_in< sc_logic > s_axi_AXILiteS_WVALID;
    sc_out< sc_logic > s_axi_AXILiteS_WREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_WDATA;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH/8> > s_axi_AXILiteS_WSTRB;
    sc_in< sc_logic > s_axi_AXILiteS_ARVALID;
    sc_out< sc_logic > s_axi_AXILiteS_ARREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_ARADDR;
    sc_out< sc_logic > s_axi_AXILiteS_RVALID;
    sc_in< sc_logic > s_axi_AXILiteS_RREADY;
    sc_out< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_RDATA;
    sc_out< sc_lv<2> > s_axi_AXILiteS_RRESP;
    sc_out< sc_logic > s_axi_AXILiteS_BVALID;
    sc_in< sc_logic > s_axi_AXILiteS_BREADY;
    sc_out< sc_lv<2> > s_axi_AXILiteS_BRESP;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    contact_discovery(sc_module_name name);
    SC_HAS_PROCESS(contact_discovery);

    ~contact_discovery();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    contact_discoverybkb* contacts_V_U;
    contact_discovery_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>* contact_discovery_AXILiteS_s_axi_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<10> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<32> > operation;
    sc_signal< sc_lv<32> > operation_preg;
    sc_signal< sc_logic > operation_ap_vld;
    sc_signal< sc_lv<32> > operation_in_sig;
    sc_signal< sc_logic > operation_ap_vld_preg;
    sc_signal< sc_logic > operation_ap_vld_in_sig;
    sc_signal< sc_lv<512> > contact_in_V;
    sc_signal< sc_lv<512> > db_in_V_V_0_data_out;
    sc_signal< sc_logic > db_in_V_V_0_vld_in;
    sc_signal< sc_logic > db_in_V_V_0_vld_out;
    sc_signal< sc_logic > db_in_V_V_0_ack_in;
    sc_signal< sc_logic > db_in_V_V_0_ack_out;
    sc_signal< sc_lv<512> > db_in_V_V_0_payload_A;
    sc_signal< sc_lv<512> > db_in_V_V_0_payload_B;
    sc_signal< sc_logic > db_in_V_V_0_sel_rd;
    sc_signal< sc_logic > db_in_V_V_0_sel_wr;
    sc_signal< sc_logic > db_in_V_V_0_sel;
    sc_signal< sc_logic > db_in_V_V_0_load_A;
    sc_signal< sc_logic > db_in_V_V_0_load_B;
    sc_signal< sc_lv<2> > db_in_V_V_0_state;
    sc_signal< sc_logic > db_in_V_V_0_state_cmp_full;
    sc_signal< sc_lv<32> > db_size_in;
    sc_signal< sc_lv<32> > error_out_1_data_reg;
    sc_signal< sc_lv<32> > error_out_1_data_in;
    sc_signal< sc_logic > error_out_1_vld_reg;
    sc_signal< sc_logic > error_out_1_vld_in;
    sc_signal< sc_logic > error_out_1_ack_in;
    sc_signal< sc_lv<32> > contacts_size_out_1_data_reg;
    sc_signal< sc_lv<32> > contacts_size_out_1_data_in;
    sc_signal< sc_logic > contacts_size_out_1_vld_reg;
    sc_signal< sc_logic > contacts_size_out_1_vld_in;
    sc_signal< sc_logic > contacts_size_out_1_ack_in;
    sc_signal< sc_lv<8> > results_out_V_1_data_out;
    sc_signal< sc_logic > results_out_V_1_vld_in;
    sc_signal< sc_logic > results_out_V_1_vld_out;
    sc_signal< sc_logic > results_out_V_1_ack_in;
    sc_signal< sc_logic > results_out_V_1_ack_out;
    sc_signal< sc_lv<8> > results_out_V_1_payload_A;
    sc_signal< sc_lv<8> > results_out_V_1_payload_B;
    sc_signal< sc_logic > results_out_V_1_sel_rd;
    sc_signal< sc_logic > results_out_V_1_sel_wr;
    sc_signal< sc_logic > results_out_V_1_sel;
    sc_signal< sc_logic > results_out_V_1_load_A;
    sc_signal< sc_logic > results_out_V_1_load_B;
    sc_signal< sc_lv<2> > results_out_V_1_state;
    sc_signal< sc_logic > results_out_V_1_state_cmp_full;
    sc_signal< sc_lv<32> > contacts_size;
    sc_signal< sc_lv<7> > contacts_V_address0;
    sc_signal< sc_logic > contacts_V_ce0;
    sc_signal< sc_logic > contacts_V_we0;
    sc_signal< sc_lv<512> > contacts_V_q0;
    sc_signal< sc_logic > operation_blk_n;
    sc_signal< sc_logic > db_in_V_V_TDATA_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > results_out_V_TDATA_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > exitcond_i_fu_247_p2;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<512> > contact_in_V_read_reg_285;
    sc_signal< sc_lv<32> > operation_read_read_fu_92_p2;
    sc_signal< sc_lv<32> > contacts_size_load_reg_294;
    sc_signal< sc_lv<32> > tmp_5_fu_225_p2;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > icmp_fu_215_p2;
    sc_signal< sc_lv<32> > database_index_1_fu_241_p2;
    sc_signal< sc_lv<32> > database_index_1_reg_314;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<512> > tmp_V_reg_319;
    sc_signal< sc_lv<8> > contacts_index_fu_253_p2;
    sc_signal< sc_lv<8> > contacts_index_reg_327;
    sc_signal< bool > ap_block_state5_io;
    sc_signal< sc_lv<8> > tmp_1_fu_264_p1;
    sc_signal< sc_lv<1> > matched_fu_274_p2;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<32> > database_index_reg_149;
    sc_signal< sc_lv<8> > contacts_index_i_reg_160;
    sc_signal< sc_lv<1> > matched_i_reg_171;
    sc_signal< sc_lv<32> > storemerge_reg_183;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<64> > tmp_4_fu_221_p1;
    sc_signal< sc_lv<64> > tmp_i_fu_259_p1;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<25> > tmp_fu_206_p4;
    sc_signal< sc_lv<1> > tmp_1_i_fu_269_p2;
    sc_signal< sc_lv<1> > exitcond_fu_236_p2;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< bool > ap_block_state10;
    sc_signal< sc_lv<10> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<10> ap_ST_fsm_state1;
    static const sc_lv<10> ap_ST_fsm_state2;
    static const sc_lv<10> ap_ST_fsm_state3;
    static const sc_lv<10> ap_ST_fsm_state4;
    static const sc_lv<10> ap_ST_fsm_state5;
    static const sc_lv<10> ap_ST_fsm_state6;
    static const sc_lv<10> ap_ST_fsm_state7;
    static const sc_lv<10> ap_ST_fsm_state8;
    static const sc_lv<10> ap_ST_fsm_state9;
    static const sc_lv<10> ap_ST_fsm_state10;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_6;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<25> ap_const_lv25_0;
    static const sc_lv<8> ap_const_lv8_80;
    static const sc_lv<8> ap_const_lv8_1;
    static const sc_lv<32> ap_const_lv32_9;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_block_state1();
    void thread_ap_block_state10();
    void thread_ap_block_state5_io();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_contacts_V_address0();
    void thread_contacts_V_ce0();
    void thread_contacts_V_we0();
    void thread_contacts_index_fu_253_p2();
    void thread_contacts_size_out_1_ack_in();
    void thread_contacts_size_out_1_data_in();
    void thread_contacts_size_out_1_vld_in();
    void thread_database_index_1_fu_241_p2();
    void thread_db_in_V_V_0_ack_in();
    void thread_db_in_V_V_0_ack_out();
    void thread_db_in_V_V_0_data_out();
    void thread_db_in_V_V_0_load_A();
    void thread_db_in_V_V_0_load_B();
    void thread_db_in_V_V_0_sel();
    void thread_db_in_V_V_0_state_cmp_full();
    void thread_db_in_V_V_0_vld_in();
    void thread_db_in_V_V_0_vld_out();
    void thread_db_in_V_V_TDATA_blk_n();
    void thread_db_in_V_V_TREADY();
    void thread_error_out_1_ack_in();
    void thread_error_out_1_data_in();
    void thread_error_out_1_vld_in();
    void thread_exitcond_fu_236_p2();
    void thread_exitcond_i_fu_247_p2();
    void thread_icmp_fu_215_p2();
    void thread_matched_fu_274_p2();
    void thread_operation_ap_vld_in_sig();
    void thread_operation_blk_n();
    void thread_operation_in_sig();
    void thread_operation_read_read_fu_92_p2();
    void thread_results_out_V_1_ack_in();
    void thread_results_out_V_1_ack_out();
    void thread_results_out_V_1_data_out();
    void thread_results_out_V_1_load_A();
    void thread_results_out_V_1_load_B();
    void thread_results_out_V_1_sel();
    void thread_results_out_V_1_state_cmp_full();
    void thread_results_out_V_1_vld_in();
    void thread_results_out_V_1_vld_out();
    void thread_results_out_V_TDATA();
    void thread_results_out_V_TDATA_blk_n();
    void thread_results_out_V_TVALID();
    void thread_tmp_1_fu_264_p1();
    void thread_tmp_1_i_fu_269_p2();
    void thread_tmp_4_fu_221_p1();
    void thread_tmp_5_fu_225_p2();
    void thread_tmp_fu_206_p4();
    void thread_tmp_i_fu_259_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
