#pragma line 1 "ed25519_sign/src/ed25519.c" ::: -10
#pragma line 1 "ed25519_sign/src/ed25519.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 289 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 427 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "ed25519_sign/src/ed25519.c" 2 ::: 184
#pragma line 17 "ed25519_sign/src/ed25519.c" ::: 193
#pragma line 1 "ed25519_sign/src/ed25519-donna.h" 1 ::: 194
#pragma line 1 "ed25519_sign/src/ed25519-donna-portable.h" 1 ::: 207
#pragma line 1 "ed25519_sign/src/ed25519-donna-portable-identify.h" 1 ::: 208
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/param.h" 1 3 4 ::: 216
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 240
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 281
#pragma line 24 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 284
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 286
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 312
#pragma line 122 "/usr/include/features.h" 3 4 ::: 409
#pragma line 177 "/usr/include/features.h" 3 4 ::: 442
#pragma line 188 "/usr/include/features.h" 3 4 ::: 445
#pragma line 340 "/usr/include/features.h" 3 4 ::: 476
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 480
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 515
#pragma line 343 "/usr/include/features.h" 2 3 4 ::: 524
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 547
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 588
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 594
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 612
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 618
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 622
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 624
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 628
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 638
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 691
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 732
#pragma line 351 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 762
#pragma line 415 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 786
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 787
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 789
#pragma line 416 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 791
#pragma line 365 "/usr/include/features.h" 2 3 4 ::: 792
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 817
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 828
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 833
#pragma line 389 "/usr/include/features.h" 2 3 4 ::: 834
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 835
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 839
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 867
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 869
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 871
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 932
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 939
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 957
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 962
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 973
#pragma line 30 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1042
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1062
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1090
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1116
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 1117
#pragma line 58 "/usr/include/time.h" 3 4 ::: 1138
#pragma line 74 "/usr/include/time.h" 3 4 ::: 1141
#pragma line 90 "/usr/include/time.h" 3 4 ::: 1144
#pragma line 102 "/usr/include/time.h" 3 4 ::: 1147
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1150
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1151
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1152
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1177
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1180
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1190
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 1222
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 1259
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 1261
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 1265
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 1268
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 1286
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1287
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1289
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 1291
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 1299
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 1317
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 1320
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 1323
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 1325
#pragma line 217 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1326
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 1330
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 1361
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1384
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1386
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 1388
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1389
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 1393
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1433
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 1446
#pragma line 118 "/usr/include/time.h" 3 4 ::: 1467
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1475
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 1477
#pragma line 48 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1512
#pragma line 100 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 1557
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1587
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 1591
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 1609
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 1620
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1622
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1644
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 1648
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1670
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1672
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 1674
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 1675
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 1698
#pragma line 125 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 1720
#pragma line 220 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 1797
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1828
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 1829
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 1 3 4 ::: 1830
#pragma line 1 "/usr/include/limits.h" 1 3 4 ::: 1869
#pragma line 116 "/usr/include/limits.h" 3 4 ::: 1905
#pragma line 142 "/usr/include/limits.h" 3 4 ::: 1919
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 1 3 4 ::: 1922
#pragma line 95 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 3 4 ::: 2005
#pragma line 155 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 3 4 ::: 2048
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 1 3 4 ::: 2055
#pragma line 37 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 3 4 ::: 2079
#pragma line 1 "/usr/include/linux/limits.h" 1 3 4 ::: 2082
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 2 3 4 ::: 2083
#pragma line 161 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 2 3 4 ::: 2144
#pragma line 144 "/usr/include/limits.h" 2 3 4 ::: 2154
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 1 3 4 ::: 2158
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 3 4 ::: 2219
#pragma line 148 "/usr/include/limits.h" 2 3 4 ::: 2221
#pragma line 39 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 2 3 4 ::: 2222
#pragma line 60 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 4 ::: 2227
#pragma line 90 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 4 ::: 2229
#pragma line 102 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 4 ::: 2231
#pragma line 27 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 2236
#pragma line 1 "/usr/include/signal.h" 1 3 4 ::: 2238
#pragma line 32 "/usr/include/signal.h" 3 4 ::: 2259
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 2260
#pragma line 35 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 3 4 ::: 2278
#pragma line 48 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 3 4 ::: 2284
#pragma line 99 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 3 4 ::: 2290
#pragma line 33 "/usr/include/signal.h" 2 3 4 ::: 2297
#pragma line 57 "/usr/include/signal.h" 3 4 ::: 2306
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/signum.h" 1 3 4 ::: 2307
#pragma line 31 "/usr/include/x86_64-linux-gnu/bits/signum.h" 3 4 ::: 2329
#pragma line 74 "/usr/include/x86_64-linux-gnu/bits/signum.h" 3 4 ::: 2331
#pragma line 58 "/usr/include/signal.h" 2 3 4 ::: 2334
#pragma line 73 "/usr/include/signal.h" 3 4 ::: 2335
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2339
#pragma line 76 "/usr/include/signal.h" 2 3 4 ::: 2360
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 1 3 4 ::: 2366
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2391
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2393
#pragma line 25 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 2 3 4 ::: 2395
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 2408
#pragma line 158 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 2488
#pragma line 263 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 2580
#pragma line 306 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 2614
#pragma line 81 "/usr/include/signal.h" 2 3 4 ::: 2668
#pragma line 123 "/usr/include/signal.h" 3 4 ::: 2692
#pragma line 178 "/usr/include/signal.h" 3 4 ::: 2735
#pragma line 205 "/usr/include/signal.h" 3 4 ::: 2752
#pragma line 241 "/usr/include/signal.h" 3 4 ::: 2775
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigaction.h" 1 3 4 ::: 2779
#pragma line 69 "/usr/include/x86_64-linux-gnu/bits/sigaction.h" 3 4 ::: 2832
#pragma line 244 "/usr/include/signal.h" 2 3 4 ::: 2840
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigcontext.h" 1 3 4 ::: 2904
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/sigcontext.h" 3 4 ::: 2921
#pragma line 121 "/usr/include/x86_64-linux-gnu/bits/sigcontext.h" 3 4 ::: 2948
#pragma line 307 "/usr/include/signal.h" 2 3 4 ::: 3021
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3032
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3057
#pragma line 317 "/usr/include/signal.h" 2 3 4 ::: 3060
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigstack.h" 1 3 4 ::: 3068
#pragma line 324 "/usr/include/signal.h" 2 3 4 ::: 3123
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/ucontext.h" 1 3 4 ::: 3127
#pragma line 1 "/usr/include/signal.h" 1 3 4 ::: 3150
#pragma line 23 "/usr/include/x86_64-linux-gnu/sys/ucontext.h" 2 3 4 ::: 3171
#pragma line 92 "/usr/include/x86_64-linux-gnu/sys/ucontext.h" 3 4 ::: 3187
#pragma line 327 "/usr/include/signal.h" 2 3 4 ::: 3238
#pragma line 359 "/usr/include/signal.h" 3 4 ::: 3251
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigthread.h" 1 3 4 ::: 3256
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/sigthread.h" 3 4 ::: 3274
#pragma line 363 "/usr/include/signal.h" 2 3 4 ::: 3285
#pragma line 29 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 3295
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/param.h" 1 3 4 ::: 3299
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/param.h" 3 4 ::: 3317
#pragma line 1 "/usr/include/linux/param.h" 1 3 4 ::: 3318
#pragma line 1 "/usr/include/x86_64-linux-gnu/asm/param.h" 1 3 4 ::: 3322
#pragma line 1 "/usr/include/asm-generic/param.h" 1 3 4 ::: 3323
#pragma line 2 "/usr/include/x86_64-linux-gnu/asm/param.h" 2 3 4 ::: 3324
#pragma line 5 "/usr/include/linux/param.h" 2 3 4 ::: 3325
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/param.h" 2 3 4 ::: 3326
#pragma line 32 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 3339
#pragma line 67 "/usr/include/x86_64-linux-gnu/sys/param.h" 3 4 ::: 3343
#pragma line 76 "/usr/include/x86_64-linux-gnu/sys/param.h" 3 4 ::: 3345
#pragma line 101 "/usr/include/x86_64-linux-gnu/sys/param.h" 3 4 ::: 3359
#pragma line 8 "ed25519_sign/src/ed25519-donna-portable-identify.h" 2 ::: 3361
#pragma line 24 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 3362
#pragma line 47 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 3364
#pragma line 86 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 3366
#pragma line 101 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 3368
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 1 3 ::: 3369
#pragma line 1 "/usr/include/stdint.h" 1 3 4 ::: 3403
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wchar.h" 1 3 4 ::: 3430
#pragma line 27 "/usr/include/stdint.h" 2 3 4 ::: 3462
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3463
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3465
#pragma line 28 "/usr/include/stdint.h" 2 3 4 ::: 3467
#pragma line 47 "/usr/include/stdint.h" 3 4 ::: 3474
#pragma line 116 "/usr/include/stdint.h" 3 4 ::: 3536
#pragma line 132 "/usr/include/stdint.h" 3 4 ::: 3544
#pragma line 152 "/usr/include/stdint.h" 3 4 ::: 3549
#pragma line 200 "/usr/include/stdint.h" 3 4 ::: 3589
#pragma line 211 "/usr/include/stdint.h" 3 4 ::: 3591
#pragma line 223 "/usr/include/stdint.h" 3 4 ::: 3593
#pragma line 235 "/usr/include/stdint.h" 3 4 ::: 3595
#pragma line 255 "/usr/include/stdint.h" 3 4 ::: 3608
#pragma line 270 "/usr/include/stdint.h" 3 4 ::: 3614
#pragma line 291 "/usr/include/stdint.h" 3 4 ::: 3627
#pragma line 301 "/usr/include/stdint.h" 3 4 ::: 3629
#pragma line 34 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 2 3 ::: 3631
#pragma line 102 "ed25519_sign/src/ed25519-donna-portable-identify.h" 2 ::: 3632
#pragma line 2 "ed25519_sign/src/ed25519-donna-portable.h" 2 ::: 3633
#pragma line 28 "ed25519_sign/src/ed25519-donna-portable.h" ::: 3638
#pragma line 89 "ed25519_sign/src/ed25519-donna-portable.h" ::: 3644
#pragma line 108 "ed25519_sign/src/ed25519-donna-portable.h" ::: 3653
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 3679
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3712
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3737
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 3740
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 3750
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 3779
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 3797
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 3798
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 3854
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 3857
#pragma line 263 "/usr/include/stdlib.h" 3 4 ::: 3979
#pragma line 426 "/usr/include/stdlib.h" 3 4 ::: 4135
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 4164
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4189
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4214
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 4217
#pragma line 454 "/usr/include/stdlib.h" 2 3 4 ::: 4226
#pragma line 475 "/usr/include/stdlib.h" 3 4 ::: 4239
#pragma line 494 "/usr/include/stdlib.h" 3 4 ::: 4246
#pragma line 516 "/usr/include/stdlib.h" 3 4 ::: 4258
#pragma line 536 "/usr/include/stdlib.h" 3 4 ::: 4269
#pragma line 595 "/usr/include/stdlib.h" 3 4 ::: 4315
#pragma line 618 "/usr/include/stdlib.h" 3 4 ::: 4324
#pragma line 673 "/usr/include/stdlib.h" 3 4 ::: 4331
#pragma line 689 "/usr/include/stdlib.h" 3 4 ::: 4337
#pragma line 713 "/usr/include/stdlib.h" 3 4 ::: 4352
#pragma line 872 "/usr/include/stdlib.h" 3 4 ::: 4503
#pragma line 908 "/usr/include/stdlib.h" 3 4 ::: 4505
#pragma line 921 "/usr/include/stdlib.h" 3 4 ::: 4511
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 4512
#pragma line 922 "/usr/include/stdlib.h" 2 3 4 ::: 4530
#pragma line 133 "ed25519_sign/src/ed25519-donna-portable.h" 2 ::: 4533
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 4534
#pragma line 29 "/usr/include/string.h" 3 4 ::: 4555
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4560
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4585
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 4588
#pragma line 92 "/usr/include/string.h" 3 4 ::: 4625
#pragma line 124 "/usr/include/string.h" 3 4 ::: 4628
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 4665
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 4708
#pragma line 207 "/usr/include/string.h" 3 4 ::: 4730
#pragma line 231 "/usr/include/string.h" 3 4 ::: 4732
#pragma line 258 "/usr/include/string.h" 3 4 ::: 4737
#pragma line 278 "/usr/include/string.h" 3 4 ::: 4740
#pragma line 310 "/usr/include/string.h" 3 4 ::: 4750
#pragma line 337 "/usr/include/string.h" 3 4 ::: 4755
#pragma line 393 "/usr/include/string.h" 3 4 ::: 4776
#pragma line 439 "/usr/include/string.h" 3 4 ::: 4807
#pragma line 484 "/usr/include/string.h" 3 4 ::: 4830
#pragma line 512 "/usr/include/string.h" 3 4 ::: 4836
#pragma line 550 "/usr/include/string.h" 3 4 ::: 4860
#pragma line 134 "ed25519_sign/src/ed25519-donna-portable.h" 2 ::: 4886
#pragma line 13 "ed25519_sign/src/ed25519-donna.h" 2 ::: 4887
#pragma line 24 "ed25519_sign/src/ed25519-donna.h" ::: 4888
#pragma line 47 "ed25519_sign/src/ed25519-donna.h" ::: 4890
#pragma line 1 "ed25519_sign/src/curve25519-donna-64bit.h" 1 ::: 4891
#pragma line 140 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 5023
#pragma line 158 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 5034
#pragma line 215 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 5084
#pragma line 271 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 5133
#pragma line 308 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 5161
#pragma line 347 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 5188
#pragma line 48 "ed25519_sign/src/ed25519-donna.h" 2 ::: 5251
#pragma line 1 "ed25519_sign/src/curve25519-donna-helpers.h" 1 ::: 5256
#pragma line 53 "ed25519_sign/src/ed25519-donna.h" 2 ::: 5324
#pragma line 1 "ed25519_sign/src/modm-donna-64bit.h" 1 ::: 5329
#pragma line 57 "ed25519_sign/src/ed25519-donna.h" 2 ::: 5691
#pragma line 1 "ed25519_sign/src/ed25519-donna-basepoint-table.h" 1 ::: 5733
#pragma line 98 "ed25519_sign/src/ed25519-donna.h" 2 ::: 5993
#pragma line 1 "ed25519_sign/src/ed25519-donna-64bit-tables.h" 1 ::: 5996
#pragma line 101 "ed25519_sign/src/ed25519-donna.h" 2 ::: 6050
#pragma line 1 "ed25519_sign/src/ed25519-donna-64bit-x86.h" 1 ::: 6051
#pragma line 102 "ed25519_sign/src/ed25519-donna.h" 2 ::: 6400
#pragma line 113 "ed25519_sign/src/ed25519-donna.h" ::: 6401
#pragma line 1 "ed25519_sign/src/ed25519-donna-impl-base.h" 1 ::: 6402
#pragma line 71 "ed25519_sign/src/ed25519-donna-impl-base.h" ::: 6475
#pragma line 90 "ed25519_sign/src/ed25519-donna-impl-base.h" ::: 6497
#pragma line 193 "ed25519_sign/src/ed25519-donna-impl-base.h" ::: 6603
#pragma line 194 "ed25519_sign/src/ed25519-donna-impl-base.h" ::: 6607
#pragma line 333 "ed25519_sign/src/ed25519-donna-impl-base.h" ::: 6707
#pragma line 114 "ed25519_sign/src/ed25519-donna.h" 2 ::: 6739
#pragma line 18 "ed25519_sign/src/ed25519.c" 2 ::: 6740
#pragma line 1 "ed25519_sign/src/ed25519.h" 1 ::: 6741
#pragma line 12 "ed25519_sign/src/ed25519.h" ::: 6742
#pragma line 19 "ed25519_sign/src/ed25519.c" 2 ::: 6758
#pragma line 1 "ed25519_sign/src/ed25519-randombytes.h" 1 ::: 6759
#pragma line 83 "ed25519_sign/src/ed25519-randombytes.h" ::: 6760
#pragma line 1 "/usr/include/openssl/rand.h" 1 3 4 ::: 6761
#pragma line 1 "/usr/include/openssl/ossl_typ.h" 1 3 4 ::: 6825
#pragma line 62 "/usr/include/openssl/ossl_typ.h" 3 4 ::: 6879
#pragma line 1 "/usr/include/openssl/e_os2.h" 1 3 4 ::: 6880
#pragma line 1 "/usr/include/x86_64-linux-gnu/openssl/opensslconf.h" 1 3 4 ::: 6937
#pragma line 66 "/usr/include/x86_64-linux-gnu/openssl/opensslconf.h" 3 4 ::: 6945
#pragma line 120 "/usr/include/x86_64-linux-gnu/openssl/opensslconf.h" 3 4 ::: 6950
#pragma line 57 "/usr/include/openssl/e_os2.h" 2 3 4 ::: 6954
#pragma line 129 "/usr/include/openssl/e_os2.h" 3 4 ::: 6998
#pragma line 138 "/usr/include/openssl/e_os2.h" 3 4 ::: 7000
#pragma line 152 "/usr/include/openssl/e_os2.h" 3 4 ::: 7006
#pragma line 166 "/usr/include/openssl/e_os2.h" 3 4 ::: 7008
#pragma line 207 "/usr/include/openssl/e_os2.h" 3 4 ::: 7016
#pragma line 218 "/usr/include/openssl/e_os2.h" 3 4 ::: 7018
#pragma line 234 "/usr/include/openssl/e_os2.h" 3 4 ::: 7025
#pragma line 247 "/usr/include/openssl/e_os2.h" 3 4 ::: 7031
#pragma line 282 "/usr/include/openssl/e_os2.h" 3 4 ::: 7051
#pragma line 63 "/usr/include/openssl/ossl_typ.h" 2 3 4 ::: 7063
#pragma line 83 "/usr/include/openssl/ossl_typ.h" 3 4 ::: 7064
#pragma line 120 "/usr/include/openssl/ossl_typ.h" 3 4 ::: 7089
#pragma line 64 "/usr/include/openssl/rand.h" 2 3 4 ::: 7177
#pragma line 1 "/usr/include/openssl/e_os2.h" 1 3 4 ::: 7178
#pragma line 1 "/usr/include/x86_64-linux-gnu/openssl/opensslconf.h" 1 3 4 ::: 7235
#pragma line 66 "/usr/include/x86_64-linux-gnu/openssl/opensslconf.h" 3 4 ::: 7243
#pragma line 120 "/usr/include/x86_64-linux-gnu/openssl/opensslconf.h" 3 4 ::: 7248
#pragma line 57 "/usr/include/openssl/e_os2.h" 2 3 4 ::: 7252
#pragma line 65 "/usr/include/openssl/rand.h" 2 3 4 ::: 7253
#pragma line 78 "/usr/include/openssl/rand.h" 3 4 ::: 7254
#pragma line 126 "/usr/include/openssl/rand.h" 3 4 ::: 7290
#pragma line 84 "ed25519_sign/src/ed25519-randombytes.h" 2 ::: 7306
#pragma line 20 "ed25519_sign/src/ed25519.c" 2 ::: 7314
#pragma line 1 "ed25519_sign/src/ed25519-hash.h" 1 ::: 7315
#pragma line 91 "ed25519_sign/src/ed25519-hash.h" ::: 7385
#pragma line 21 "ed25519_sign/src/ed25519.c" 2 ::: 7483
#pragma line 1 "ed25519_sign/src/ed25519-donna-batchverify.h" 1 ::: 7582
#pragma line 195 "ed25519_sign/src/ed25519-donna-batchverify.h" ::: 7779
#pragma line 119 "ed25519_sign/src/ed25519.c" 2 ::: 7860
