#pragma line 1 "ed25519_sign/src/ed25519.c" ::: 0
#pragma line 1 "ed25519_sign/src/ed25519.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 289 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 427 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "ed25519_sign/src/ed25519.c" 2 ::: 194
#pragma line 17 "ed25519_sign/src/ed25519.c" ::: 203
#pragma line 1 "ed25519_sign/src/ed25519-donna.h" 1 ::: 204
#pragma line 1 "ed25519_sign/src/ed25519-donna-portable.h" 1 ::: 217
#pragma line 1 "ed25519_sign/src/ed25519-donna-portable-identify.h" 1 ::: 218
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/param.h" 1 3 4 ::: 226
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 250
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 291
#pragma line 24 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 294
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 296
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 322
#pragma line 122 "/usr/include/features.h" 3 4 ::: 419
#pragma line 177 "/usr/include/features.h" 3 4 ::: 452
#pragma line 188 "/usr/include/features.h" 3 4 ::: 455
#pragma line 340 "/usr/include/features.h" 3 4 ::: 486
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 490
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 525
#pragma line 343 "/usr/include/features.h" 2 3 4 ::: 534
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 557
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 598
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 604
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 622
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 628
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 632
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 634
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 638
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 648
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 701
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 742
#pragma line 351 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 772
#pragma line 415 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 796
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 797
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 799
#pragma line 416 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 801
#pragma line 365 "/usr/include/features.h" 2 3 4 ::: 802
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 827
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 838
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 843
#pragma line 389 "/usr/include/features.h" 2 3 4 ::: 844
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 845
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 849
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 877
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 879
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 881
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 942
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 949
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 967
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 972
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 983
#pragma line 30 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1052
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1072
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1100
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1126
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 1127
#pragma line 58 "/usr/include/time.h" 3 4 ::: 1148
#pragma line 74 "/usr/include/time.h" 3 4 ::: 1151
#pragma line 90 "/usr/include/time.h" 3 4 ::: 1154
#pragma line 102 "/usr/include/time.h" 3 4 ::: 1157
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1160
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1161
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1162
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1187
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1190
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1200
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 1232
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 1269
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 1271
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 1275
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 1278
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 1296
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1297
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1299
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 1301
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 1309
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 1327
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 1330
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 1333
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 1335
#pragma line 217 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1336
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 1340
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 1371
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1394
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1396
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 1398
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1399
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 1403
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1443
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 1456
#pragma line 118 "/usr/include/time.h" 3 4 ::: 1477
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1485
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 1487
#pragma line 48 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1522
#pragma line 100 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 1567
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1597
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 1601
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 1619
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 1630
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1632
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 1654
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 1658
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1680
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1682
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 1684
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 1685
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 1708
#pragma line 125 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 1730
#pragma line 220 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 1807
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 1838
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 1839
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 1 3 4 ::: 1840
#pragma line 1 "/usr/include/limits.h" 1 3 4 ::: 1879
#pragma line 116 "/usr/include/limits.h" 3 4 ::: 1915
#pragma line 142 "/usr/include/limits.h" 3 4 ::: 1929
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 1 3 4 ::: 1932
#pragma line 95 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 3 4 ::: 2015
#pragma line 155 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 3 4 ::: 2058
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 1 3 4 ::: 2065
#pragma line 37 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 3 4 ::: 2089
#pragma line 1 "/usr/include/linux/limits.h" 1 3 4 ::: 2092
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 2 3 4 ::: 2093
#pragma line 161 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 2 3 4 ::: 2154
#pragma line 144 "/usr/include/limits.h" 2 3 4 ::: 2164
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 1 3 4 ::: 2168
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 3 4 ::: 2229
#pragma line 148 "/usr/include/limits.h" 2 3 4 ::: 2231
#pragma line 39 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 2 3 4 ::: 2232
#pragma line 60 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 4 ::: 2237
#pragma line 90 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 4 ::: 2239
#pragma line 102 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 4 ::: 2241
#pragma line 27 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 2246
#pragma line 1 "/usr/include/signal.h" 1 3 4 ::: 2248
#pragma line 32 "/usr/include/signal.h" 3 4 ::: 2269
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 2270
#pragma line 35 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 3 4 ::: 2288
#pragma line 48 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 3 4 ::: 2294
#pragma line 99 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 3 4 ::: 2300
#pragma line 33 "/usr/include/signal.h" 2 3 4 ::: 2307
#pragma line 57 "/usr/include/signal.h" 3 4 ::: 2316
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/signum.h" 1 3 4 ::: 2317
#pragma line 31 "/usr/include/x86_64-linux-gnu/bits/signum.h" 3 4 ::: 2339
#pragma line 74 "/usr/include/x86_64-linux-gnu/bits/signum.h" 3 4 ::: 2341
#pragma line 58 "/usr/include/signal.h" 2 3 4 ::: 2344
#pragma line 73 "/usr/include/signal.h" 3 4 ::: 2345
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2349
#pragma line 76 "/usr/include/signal.h" 2 3 4 ::: 2370
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 1 3 4 ::: 2376
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2401
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2403
#pragma line 25 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 2 3 4 ::: 2405
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 2418
#pragma line 158 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 2498
#pragma line 263 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 2590
#pragma line 306 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 2624
#pragma line 81 "/usr/include/signal.h" 2 3 4 ::: 2678
#pragma line 123 "/usr/include/signal.h" 3 4 ::: 2702
#pragma line 178 "/usr/include/signal.h" 3 4 ::: 2745
#pragma line 205 "/usr/include/signal.h" 3 4 ::: 2762
#pragma line 241 "/usr/include/signal.h" 3 4 ::: 2785
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigaction.h" 1 3 4 ::: 2789
#pragma line 69 "/usr/include/x86_64-linux-gnu/bits/sigaction.h" 3 4 ::: 2842
#pragma line 244 "/usr/include/signal.h" 2 3 4 ::: 2850
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigcontext.h" 1 3 4 ::: 2914
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/sigcontext.h" 3 4 ::: 2931
#pragma line 121 "/usr/include/x86_64-linux-gnu/bits/sigcontext.h" 3 4 ::: 2958
#pragma line 307 "/usr/include/signal.h" 2 3 4 ::: 3031
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3042
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3067
#pragma line 317 "/usr/include/signal.h" 2 3 4 ::: 3070
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigstack.h" 1 3 4 ::: 3078
#pragma line 324 "/usr/include/signal.h" 2 3 4 ::: 3133
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/ucontext.h" 1 3 4 ::: 3137
#pragma line 1 "/usr/include/signal.h" 1 3 4 ::: 3160
#pragma line 23 "/usr/include/x86_64-linux-gnu/sys/ucontext.h" 2 3 4 ::: 3181
#pragma line 92 "/usr/include/x86_64-linux-gnu/sys/ucontext.h" 3 4 ::: 3197
#pragma line 327 "/usr/include/signal.h" 2 3 4 ::: 3248
#pragma line 359 "/usr/include/signal.h" 3 4 ::: 3261
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigthread.h" 1 3 4 ::: 3266
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/sigthread.h" 3 4 ::: 3284
#pragma line 363 "/usr/include/signal.h" 2 3 4 ::: 3295
#pragma line 29 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 3305
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/param.h" 1 3 4 ::: 3309
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/param.h" 3 4 ::: 3327
#pragma line 1 "/usr/include/linux/param.h" 1 3 4 ::: 3328
#pragma line 1 "/usr/include/x86_64-linux-gnu/asm/param.h" 1 3 4 ::: 3332
#pragma line 1 "/usr/include/asm-generic/param.h" 1 3 4 ::: 3333
#pragma line 2 "/usr/include/x86_64-linux-gnu/asm/param.h" 2 3 4 ::: 3334
#pragma line 5 "/usr/include/linux/param.h" 2 3 4 ::: 3335
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/param.h" 2 3 4 ::: 3336
#pragma line 32 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 3349
#pragma line 67 "/usr/include/x86_64-linux-gnu/sys/param.h" 3 4 ::: 3353
#pragma line 76 "/usr/include/x86_64-linux-gnu/sys/param.h" 3 4 ::: 3355
#pragma line 101 "/usr/include/x86_64-linux-gnu/sys/param.h" 3 4 ::: 3369
#pragma line 8 "ed25519_sign/src/ed25519-donna-portable-identify.h" 2 ::: 3371
#pragma line 24 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 3372
#pragma line 47 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 3374
#pragma line 86 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 3376
#pragma line 101 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 3378
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 1 3 ::: 3379
#pragma line 1 "/usr/include/stdint.h" 1 3 4 ::: 3413
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wchar.h" 1 3 4 ::: 3440
#pragma line 27 "/usr/include/stdint.h" 2 3 4 ::: 3472
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3473
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3475
#pragma line 28 "/usr/include/stdint.h" 2 3 4 ::: 3477
#pragma line 47 "/usr/include/stdint.h" 3 4 ::: 3484
#pragma line 116 "/usr/include/stdint.h" 3 4 ::: 3546
#pragma line 132 "/usr/include/stdint.h" 3 4 ::: 3554
#pragma line 152 "/usr/include/stdint.h" 3 4 ::: 3559
#pragma line 200 "/usr/include/stdint.h" 3 4 ::: 3599
#pragma line 211 "/usr/include/stdint.h" 3 4 ::: 3601
#pragma line 223 "/usr/include/stdint.h" 3 4 ::: 3603
#pragma line 235 "/usr/include/stdint.h" 3 4 ::: 3605
#pragma line 255 "/usr/include/stdint.h" 3 4 ::: 3618
#pragma line 270 "/usr/include/stdint.h" 3 4 ::: 3624
#pragma line 291 "/usr/include/stdint.h" 3 4 ::: 3637
#pragma line 301 "/usr/include/stdint.h" 3 4 ::: 3639
#pragma line 34 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 2 3 ::: 3641
#pragma line 102 "ed25519_sign/src/ed25519-donna-portable-identify.h" 2 ::: 3642
#pragma line 2 "ed25519_sign/src/ed25519-donna-portable.h" 2 ::: 3643
#pragma line 28 "ed25519_sign/src/ed25519-donna-portable.h" ::: 3648
#pragma line 89 "ed25519_sign/src/ed25519-donna-portable.h" ::: 3654
#pragma line 108 "ed25519_sign/src/ed25519-donna-portable.h" ::: 3663
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 3689
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3722
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3747
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 3750
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 3760
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 3789
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 3807
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 3808
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 3864
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 3867
#pragma line 263 "/usr/include/stdlib.h" 3 4 ::: 3989
#pragma line 426 "/usr/include/stdlib.h" 3 4 ::: 4145
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 4174
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4199
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4224
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 4227
#pragma line 454 "/usr/include/stdlib.h" 2 3 4 ::: 4236
#pragma line 475 "/usr/include/stdlib.h" 3 4 ::: 4249
#pragma line 494 "/usr/include/stdlib.h" 3 4 ::: 4256
#pragma line 516 "/usr/include/stdlib.h" 3 4 ::: 4268
#pragma line 536 "/usr/include/stdlib.h" 3 4 ::: 4279
#pragma line 595 "/usr/include/stdlib.h" 3 4 ::: 4325
#pragma line 618 "/usr/include/stdlib.h" 3 4 ::: 4334
#pragma line 673 "/usr/include/stdlib.h" 3 4 ::: 4341
#pragma line 689 "/usr/include/stdlib.h" 3 4 ::: 4347
#pragma line 713 "/usr/include/stdlib.h" 3 4 ::: 4362
#pragma line 872 "/usr/include/stdlib.h" 3 4 ::: 4513
#pragma line 908 "/usr/include/stdlib.h" 3 4 ::: 4515
#pragma line 921 "/usr/include/stdlib.h" 3 4 ::: 4521
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 4522
#pragma line 922 "/usr/include/stdlib.h" 2 3 4 ::: 4540
#pragma line 133 "ed25519_sign/src/ed25519-donna-portable.h" 2 ::: 4543
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 4544
#pragma line 29 "/usr/include/string.h" 3 4 ::: 4565
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4570
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4595
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 4598
#pragma line 92 "/usr/include/string.h" 3 4 ::: 4635
#pragma line 124 "/usr/include/string.h" 3 4 ::: 4638
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 4675
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 4718
#pragma line 207 "/usr/include/string.h" 3 4 ::: 4740
#pragma line 231 "/usr/include/string.h" 3 4 ::: 4742
#pragma line 258 "/usr/include/string.h" 3 4 ::: 4747
#pragma line 278 "/usr/include/string.h" 3 4 ::: 4750
#pragma line 310 "/usr/include/string.h" 3 4 ::: 4760
#pragma line 337 "/usr/include/string.h" 3 4 ::: 4765
#pragma line 393 "/usr/include/string.h" 3 4 ::: 4786
#pragma line 439 "/usr/include/string.h" 3 4 ::: 4817
#pragma line 484 "/usr/include/string.h" 3 4 ::: 4840
#pragma line 512 "/usr/include/string.h" 3 4 ::: 4846
#pragma line 550 "/usr/include/string.h" 3 4 ::: 4870
#pragma line 134 "ed25519_sign/src/ed25519-donna-portable.h" 2 ::: 4896
#pragma line 13 "ed25519_sign/src/ed25519-donna.h" 2 ::: 4897
#pragma line 24 "ed25519_sign/src/ed25519-donna.h" ::: 4898
#pragma line 47 "ed25519_sign/src/ed25519-donna.h" ::: 4900
#pragma line 1 "ed25519_sign/src/curve25519-donna-64bit.h" 1 ::: 4901
#pragma line 140 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 5033
#pragma line 158 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 5044
#pragma line 215 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 5094
#pragma line 271 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 5143
#pragma line 308 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 5171
#pragma line 347 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 5198
#pragma line 48 "ed25519_sign/src/ed25519-donna.h" 2 ::: 5261
#pragma line 1 "ed25519_sign/src/curve25519-donna-helpers.h" 1 ::: 5266
#pragma line 53 "ed25519_sign/src/ed25519-donna.h" 2 ::: 5334
#pragma line 1 "ed25519_sign/src/modm-donna-64bit.h" 1 ::: 5339
#pragma line 57 "ed25519_sign/src/ed25519-donna.h" 2 ::: 5701
#pragma line 1 "ed25519_sign/src/ed25519-donna-basepoint-table.h" 1 ::: 5743
#pragma line 98 "ed25519_sign/src/ed25519-donna.h" 2 ::: 6003
#pragma line 1 "ed25519_sign/src/ed25519-donna-64bit-tables.h" 1 ::: 6006
#pragma line 101 "ed25519_sign/src/ed25519-donna.h" 2 ::: 6060
#pragma line 1 "ed25519_sign/src/ed25519-donna-64bit-x86.h" 1 ::: 6061
#pragma line 102 "ed25519_sign/src/ed25519-donna.h" 2 ::: 6410
#pragma line 113 "ed25519_sign/src/ed25519-donna.h" ::: 6411
#pragma line 1 "ed25519_sign/src/ed25519-donna-impl-base.h" 1 ::: 6412
#pragma line 333 "ed25519_sign/src/ed25519-donna-impl-base.h" ::: 6705
#pragma line 114 "ed25519_sign/src/ed25519-donna.h" 2 ::: 6737
#pragma line 18 "ed25519_sign/src/ed25519.c" 2 ::: 6738
#pragma line 1 "ed25519_sign/src/ed25519.h" 1 ::: 6739
#pragma line 12 "ed25519_sign/src/ed25519.h" ::: 6740
#pragma line 19 "ed25519_sign/src/ed25519.c" 2 ::: 6756
#pragma line 1 "ed25519_sign/src/ed25519-randombytes.h" 1 ::: 6757
#pragma line 83 "ed25519_sign/src/ed25519-randombytes.h" ::: 6758
#pragma line 1 "/usr/include/openssl/rand.h" 1 3 4 ::: 6759
#pragma line 1 "/usr/include/openssl/ossl_typ.h" 1 3 4 ::: 6823
#pragma line 62 "/usr/include/openssl/ossl_typ.h" 3 4 ::: 6877
#pragma line 1 "/usr/include/openssl/e_os2.h" 1 3 4 ::: 6878
#pragma line 1 "/usr/include/x86_64-linux-gnu/openssl/opensslconf.h" 1 3 4 ::: 6935
#pragma line 66 "/usr/include/x86_64-linux-gnu/openssl/opensslconf.h" 3 4 ::: 6943
#pragma line 120 "/usr/include/x86_64-linux-gnu/openssl/opensslconf.h" 3 4 ::: 6948
#pragma line 57 "/usr/include/openssl/e_os2.h" 2 3 4 ::: 6952
#pragma line 129 "/usr/include/openssl/e_os2.h" 3 4 ::: 6996
#pragma line 138 "/usr/include/openssl/e_os2.h" 3 4 ::: 6998
#pragma line 152 "/usr/include/openssl/e_os2.h" 3 4 ::: 7004
#pragma line 166 "/usr/include/openssl/e_os2.h" 3 4 ::: 7006
#pragma line 207 "/usr/include/openssl/e_os2.h" 3 4 ::: 7014
#pragma line 218 "/usr/include/openssl/e_os2.h" 3 4 ::: 7016
#pragma line 234 "/usr/include/openssl/e_os2.h" 3 4 ::: 7023
#pragma line 247 "/usr/include/openssl/e_os2.h" 3 4 ::: 7029
#pragma line 282 "/usr/include/openssl/e_os2.h" 3 4 ::: 7049
#pragma line 63 "/usr/include/openssl/ossl_typ.h" 2 3 4 ::: 7061
#pragma line 83 "/usr/include/openssl/ossl_typ.h" 3 4 ::: 7062
#pragma line 120 "/usr/include/openssl/ossl_typ.h" 3 4 ::: 7087
#pragma line 64 "/usr/include/openssl/rand.h" 2 3 4 ::: 7175
#pragma line 1 "/usr/include/openssl/e_os2.h" 1 3 4 ::: 7176
#pragma line 1 "/usr/include/x86_64-linux-gnu/openssl/opensslconf.h" 1 3 4 ::: 7233
#pragma line 66 "/usr/include/x86_64-linux-gnu/openssl/opensslconf.h" 3 4 ::: 7241
#pragma line 120 "/usr/include/x86_64-linux-gnu/openssl/opensslconf.h" 3 4 ::: 7246
#pragma line 57 "/usr/include/openssl/e_os2.h" 2 3 4 ::: 7250
#pragma line 65 "/usr/include/openssl/rand.h" 2 3 4 ::: 7251
#pragma line 78 "/usr/include/openssl/rand.h" 3 4 ::: 7252
#pragma line 126 "/usr/include/openssl/rand.h" 3 4 ::: 7288
#pragma line 84 "ed25519_sign/src/ed25519-randombytes.h" 2 ::: 7304
#pragma line 20 "ed25519_sign/src/ed25519.c" 2 ::: 7312
#pragma line 1 "ed25519_sign/src/ed25519-hash.h" 1 ::: 7313
#pragma line 91 "ed25519_sign/src/ed25519-hash.h" ::: 7383
#pragma line 21 "ed25519_sign/src/ed25519.c" 2 ::: 7481
#pragma line 1 "ed25519_sign/src/ed25519-donna-batchverify.h" 1 ::: 7580
#pragma line 119 "ed25519_sign/src/ed25519.c" 2 ::: 7855
