#pragma line 1 "ed25519_sign/src/test-internals.c" ::: 0
#pragma line 1 "ed25519_sign/src/test-internals.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 289 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 427 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "ed25519_sign/src/test-internals.c" 2 ::: 194
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 195
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 223
#pragma line 122 "/usr/include/features.h" 3 4 ::: 320
#pragma line 177 "/usr/include/features.h" 3 4 ::: 353
#pragma line 188 "/usr/include/features.h" 3 4 ::: 356
#pragma line 340 "/usr/include/features.h" 3 4 ::: 387
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 391
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 426
#pragma line 343 "/usr/include/features.h" 2 3 4 ::: 435
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 458
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 499
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 505
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 523
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 529
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 533
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 535
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 539
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 549
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 602
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 643
#pragma line 351 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 673
#pragma line 415 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 697
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 698
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 700
#pragma line 416 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 702
#pragma line 365 "/usr/include/features.h" 2 3 4 ::: 703
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 728
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 739
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 744
#pragma line 389 "/usr/include/features.h" 2 3 4 ::: 745
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 746
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 752
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 793
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 796
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 798
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 826
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 828
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 830
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 891
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 898
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 916
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 921
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 932
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 1001
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1015
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1018
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1019
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1051
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1067
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1092
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1095
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1100
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1122
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1143
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1146
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1157
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1167
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1169
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1173
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1222
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1223
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1229
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1231
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1251
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1262
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1303
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1333
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 1359
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1363
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1378
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1390
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1396
#pragma line 104 "/usr/include/stdio.h" 3 4 ::: 1398
#pragma line 121 "/usr/include/stdio.h" 3 4 ::: 1408
#pragma line 152 "/usr/include/stdio.h" 3 4 ::: 1430
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1446
#pragma line 167 "/usr/include/stdio.h" 2 3 4 ::: 1463
#pragma line 210 "/usr/include/stdio.h" 3 4 ::: 1495
#pragma line 270 "/usr/include/stdio.h" 3 4 ::: 1541
#pragma line 307 "/usr/include/stdio.h" 3 4 ::: 1555
#pragma line 320 "/usr/include/stdio.h" 3 4 ::: 1558
#pragma line 413 "/usr/include/stdio.h" 3 4 ::: 1634
#pragma line 469 "/usr/include/stdio.h" 3 4 ::: 1673
#pragma line 529 "/usr/include/stdio.h" 3 4 ::: 1714
#pragma line 657 "/usr/include/stdio.h" 3 4 ::: 1827
#pragma line 733 "/usr/include/stdio.h" 3 4 ::: 1890
#pragma line 796 "/usr/include/stdio.h" 3 4 ::: 1939
#pragma line 827 "/usr/include/stdio.h" 3 4 ::: 1950
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1980
#pragma line 856 "/usr/include/stdio.h" 2 3 4 ::: 2008
#pragma line 911 "/usr/include/stdio.h" 3 4 ::: 2040
#pragma line 932 "/usr/include/stdio.h" 3 4 ::: 2052
#pragma line 2 "ed25519_sign/src/test-internals.c" 2 ::: 2055
#pragma line 1 "ed25519_sign/src/ed25519-donna.h" 1 ::: 2056
#pragma line 1 "ed25519_sign/src/ed25519-donna-portable.h" 1 ::: 2069
#pragma line 1 "ed25519_sign/src/ed25519-donna-portable-identify.h" 1 ::: 2070
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/param.h" 1 3 4 ::: 2078
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2102
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2127
#pragma line 24 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 2130
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2132
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2153
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2170
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2192
#pragma line 115 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2200
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2209
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2210
#pragma line 58 "/usr/include/time.h" 3 4 ::: 2231
#pragma line 74 "/usr/include/time.h" 3 4 ::: 2234
#pragma line 90 "/usr/include/time.h" 3 4 ::: 2237
#pragma line 102 "/usr/include/time.h" 3 4 ::: 2240
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2243
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2244
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2245
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2270
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2273
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2283
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2315
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2352
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2354
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2358
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2361
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2379
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2380
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2382
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2384
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 2392
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2410
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2413
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2416
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 2418
#pragma line 217 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2419
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 2423
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 2454
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2477
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2479
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 2481
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2482
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 2486
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2526
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2539
#pragma line 118 "/usr/include/time.h" 3 4 ::: 2560
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2568
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 2570
#pragma line 48 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2605
#pragma line 100 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 2650
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2680
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 2684
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 2702
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 2713
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2715
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2737
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 2741
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2763
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2765
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 2767
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 2768
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 2791
#pragma line 125 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 2813
#pragma line 220 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 2890
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2921
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 2922
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 1 3 4 ::: 2923
#pragma line 1 "/usr/include/limits.h" 1 3 4 ::: 2962
#pragma line 116 "/usr/include/limits.h" 3 4 ::: 2998
#pragma line 142 "/usr/include/limits.h" 3 4 ::: 3012
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 1 3 4 ::: 3015
#pragma line 95 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 3 4 ::: 3098
#pragma line 155 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 3 4 ::: 3141
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 1 3 4 ::: 3148
#pragma line 37 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 3 4 ::: 3172
#pragma line 1 "/usr/include/linux/limits.h" 1 3 4 ::: 3175
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 2 3 4 ::: 3176
#pragma line 161 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 2 3 4 ::: 3237
#pragma line 144 "/usr/include/limits.h" 2 3 4 ::: 3247
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 1 3 4 ::: 3251
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 3 4 ::: 3312
#pragma line 148 "/usr/include/limits.h" 2 3 4 ::: 3314
#pragma line 39 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 2 3 4 ::: 3315
#pragma line 60 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 4 ::: 3320
#pragma line 90 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 4 ::: 3322
#pragma line 102 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 4 ::: 3324
#pragma line 27 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 3329
#pragma line 1 "/usr/include/signal.h" 1 3 4 ::: 3331
#pragma line 32 "/usr/include/signal.h" 3 4 ::: 3352
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 3353
#pragma line 35 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 3 4 ::: 3371
#pragma line 48 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 3 4 ::: 3377
#pragma line 99 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 3 4 ::: 3383
#pragma line 33 "/usr/include/signal.h" 2 3 4 ::: 3390
#pragma line 57 "/usr/include/signal.h" 3 4 ::: 3399
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/signum.h" 1 3 4 ::: 3400
#pragma line 31 "/usr/include/x86_64-linux-gnu/bits/signum.h" 3 4 ::: 3422
#pragma line 74 "/usr/include/x86_64-linux-gnu/bits/signum.h" 3 4 ::: 3424
#pragma line 58 "/usr/include/signal.h" 2 3 4 ::: 3427
#pragma line 73 "/usr/include/signal.h" 3 4 ::: 3428
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3432
#pragma line 76 "/usr/include/signal.h" 2 3 4 ::: 3453
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 1 3 4 ::: 3459
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3484
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3486
#pragma line 25 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 2 3 4 ::: 3488
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 3501
#pragma line 158 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 3581
#pragma line 263 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 3673
#pragma line 306 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 3707
#pragma line 81 "/usr/include/signal.h" 2 3 4 ::: 3761
#pragma line 123 "/usr/include/signal.h" 3 4 ::: 3785
#pragma line 178 "/usr/include/signal.h" 3 4 ::: 3828
#pragma line 205 "/usr/include/signal.h" 3 4 ::: 3845
#pragma line 241 "/usr/include/signal.h" 3 4 ::: 3868
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigaction.h" 1 3 4 ::: 3872
#pragma line 69 "/usr/include/x86_64-linux-gnu/bits/sigaction.h" 3 4 ::: 3925
#pragma line 244 "/usr/include/signal.h" 2 3 4 ::: 3933
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigcontext.h" 1 3 4 ::: 3997
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/sigcontext.h" 3 4 ::: 4014
#pragma line 121 "/usr/include/x86_64-linux-gnu/bits/sigcontext.h" 3 4 ::: 4041
#pragma line 307 "/usr/include/signal.h" 2 3 4 ::: 4114
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4125
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4150
#pragma line 317 "/usr/include/signal.h" 2 3 4 ::: 4153
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigstack.h" 1 3 4 ::: 4161
#pragma line 324 "/usr/include/signal.h" 2 3 4 ::: 4216
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/ucontext.h" 1 3 4 ::: 4220
#pragma line 1 "/usr/include/signal.h" 1 3 4 ::: 4243
#pragma line 23 "/usr/include/x86_64-linux-gnu/sys/ucontext.h" 2 3 4 ::: 4264
#pragma line 92 "/usr/include/x86_64-linux-gnu/sys/ucontext.h" 3 4 ::: 4280
#pragma line 327 "/usr/include/signal.h" 2 3 4 ::: 4331
#pragma line 359 "/usr/include/signal.h" 3 4 ::: 4344
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigthread.h" 1 3 4 ::: 4349
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/sigthread.h" 3 4 ::: 4367
#pragma line 363 "/usr/include/signal.h" 2 3 4 ::: 4378
#pragma line 29 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 4388
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/param.h" 1 3 4 ::: 4392
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/param.h" 3 4 ::: 4410
#pragma line 1 "/usr/include/linux/param.h" 1 3 4 ::: 4411
#pragma line 1 "/usr/include/x86_64-linux-gnu/asm/param.h" 1 3 4 ::: 4415
#pragma line 1 "/usr/include/asm-generic/param.h" 1 3 4 ::: 4416
#pragma line 2 "/usr/include/x86_64-linux-gnu/asm/param.h" 2 3 4 ::: 4417
#pragma line 5 "/usr/include/linux/param.h" 2 3 4 ::: 4418
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/param.h" 2 3 4 ::: 4419
#pragma line 32 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 4432
#pragma line 67 "/usr/include/x86_64-linux-gnu/sys/param.h" 3 4 ::: 4436
#pragma line 76 "/usr/include/x86_64-linux-gnu/sys/param.h" 3 4 ::: 4438
#pragma line 101 "/usr/include/x86_64-linux-gnu/sys/param.h" 3 4 ::: 4452
#pragma line 8 "ed25519_sign/src/ed25519-donna-portable-identify.h" 2 ::: 4454
#pragma line 24 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 4455
#pragma line 47 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 4457
#pragma line 86 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 4459
#pragma line 101 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 4461
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 1 3 ::: 4462
#pragma line 1 "/usr/include/stdint.h" 1 3 4 ::: 4496
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wchar.h" 1 3 4 ::: 4523
#pragma line 27 "/usr/include/stdint.h" 2 3 4 ::: 4555
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 4556
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 4558
#pragma line 28 "/usr/include/stdint.h" 2 3 4 ::: 4560
#pragma line 47 "/usr/include/stdint.h" 3 4 ::: 4567
#pragma line 116 "/usr/include/stdint.h" 3 4 ::: 4629
#pragma line 132 "/usr/include/stdint.h" 3 4 ::: 4637
#pragma line 152 "/usr/include/stdint.h" 3 4 ::: 4642
#pragma line 200 "/usr/include/stdint.h" 3 4 ::: 4682
#pragma line 211 "/usr/include/stdint.h" 3 4 ::: 4684
#pragma line 223 "/usr/include/stdint.h" 3 4 ::: 4686
#pragma line 235 "/usr/include/stdint.h" 3 4 ::: 4688
#pragma line 255 "/usr/include/stdint.h" 3 4 ::: 4701
#pragma line 270 "/usr/include/stdint.h" 3 4 ::: 4707
#pragma line 291 "/usr/include/stdint.h" 3 4 ::: 4720
#pragma line 301 "/usr/include/stdint.h" 3 4 ::: 4722
#pragma line 34 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 2 3 ::: 4724
#pragma line 102 "ed25519_sign/src/ed25519-donna-portable-identify.h" 2 ::: 4725
#pragma line 2 "ed25519_sign/src/ed25519-donna-portable.h" 2 ::: 4726
#pragma line 28 "ed25519_sign/src/ed25519-donna-portable.h" ::: 4731
#pragma line 89 "ed25519_sign/src/ed25519-donna-portable.h" ::: 4737
#pragma line 108 "ed25519_sign/src/ed25519-donna-portable.h" ::: 4746
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 4772
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4805
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4830
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 4833
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 4843
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 4872
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 4890
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 4891
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 4947
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 4950
#pragma line 263 "/usr/include/stdlib.h" 3 4 ::: 5072
#pragma line 426 "/usr/include/stdlib.h" 3 4 ::: 5228
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 5257
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 5282
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 5307
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 5310
#pragma line 454 "/usr/include/stdlib.h" 2 3 4 ::: 5319
#pragma line 475 "/usr/include/stdlib.h" 3 4 ::: 5332
#pragma line 494 "/usr/include/stdlib.h" 3 4 ::: 5339
#pragma line 516 "/usr/include/stdlib.h" 3 4 ::: 5351
#pragma line 536 "/usr/include/stdlib.h" 3 4 ::: 5362
#pragma line 595 "/usr/include/stdlib.h" 3 4 ::: 5408
#pragma line 618 "/usr/include/stdlib.h" 3 4 ::: 5417
#pragma line 673 "/usr/include/stdlib.h" 3 4 ::: 5424
#pragma line 689 "/usr/include/stdlib.h" 3 4 ::: 5430
#pragma line 713 "/usr/include/stdlib.h" 3 4 ::: 5445
#pragma line 872 "/usr/include/stdlib.h" 3 4 ::: 5596
#pragma line 908 "/usr/include/stdlib.h" 3 4 ::: 5598
#pragma line 921 "/usr/include/stdlib.h" 3 4 ::: 5604
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 5605
#pragma line 922 "/usr/include/stdlib.h" 2 3 4 ::: 5623
#pragma line 133 "ed25519_sign/src/ed25519-donna-portable.h" 2 ::: 5626
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 5627
#pragma line 29 "/usr/include/string.h" 3 4 ::: 5648
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 5653
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 5678
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 5681
#pragma line 92 "/usr/include/string.h" 3 4 ::: 5718
#pragma line 124 "/usr/include/string.h" 3 4 ::: 5721
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 5758
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 5801
#pragma line 207 "/usr/include/string.h" 3 4 ::: 5823
#pragma line 231 "/usr/include/string.h" 3 4 ::: 5825
#pragma line 258 "/usr/include/string.h" 3 4 ::: 5830
#pragma line 278 "/usr/include/string.h" 3 4 ::: 5833
#pragma line 310 "/usr/include/string.h" 3 4 ::: 5843
#pragma line 337 "/usr/include/string.h" 3 4 ::: 5848
#pragma line 393 "/usr/include/string.h" 3 4 ::: 5869
#pragma line 439 "/usr/include/string.h" 3 4 ::: 5900
#pragma line 484 "/usr/include/string.h" 3 4 ::: 5923
#pragma line 512 "/usr/include/string.h" 3 4 ::: 5929
#pragma line 550 "/usr/include/string.h" 3 4 ::: 5953
#pragma line 134 "ed25519_sign/src/ed25519-donna-portable.h" 2 ::: 5979
#pragma line 13 "ed25519_sign/src/ed25519-donna.h" 2 ::: 5980
#pragma line 24 "ed25519_sign/src/ed25519-donna.h" ::: 5981
#pragma line 47 "ed25519_sign/src/ed25519-donna.h" ::: 5983
#pragma line 1 "ed25519_sign/src/curve25519-donna-64bit.h" 1 ::: 5984
#pragma line 140 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 6116
#pragma line 158 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 6127
#pragma line 215 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 6177
#pragma line 271 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 6226
#pragma line 308 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 6254
#pragma line 347 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 6281
#pragma line 48 "ed25519_sign/src/ed25519-donna.h" 2 ::: 6344
#pragma line 1 "ed25519_sign/src/curve25519-donna-helpers.h" 1 ::: 6349
#pragma line 53 "ed25519_sign/src/ed25519-donna.h" 2 ::: 6417
#pragma line 1 "ed25519_sign/src/modm-donna-64bit.h" 1 ::: 6422
#pragma line 57 "ed25519_sign/src/ed25519-donna.h" 2 ::: 6784
#pragma line 1 "ed25519_sign/src/ed25519-donna-basepoint-table.h" 1 ::: 6826
#pragma line 98 "ed25519_sign/src/ed25519-donna.h" 2 ::: 7086
#pragma line 1 "ed25519_sign/src/ed25519-donna-64bit-tables.h" 1 ::: 7089
#pragma line 101 "ed25519_sign/src/ed25519-donna.h" 2 ::: 7143
#pragma line 1 "ed25519_sign/src/ed25519-donna-64bit-x86.h" 1 ::: 7144
#pragma line 102 "ed25519_sign/src/ed25519-donna.h" 2 ::: 7493
#pragma line 113 "ed25519_sign/src/ed25519-donna.h" ::: 7494
#pragma line 1 "ed25519_sign/src/ed25519-donna-impl-base.h" 1 ::: 7495
#pragma line 333 "ed25519_sign/src/ed25519-donna-impl-base.h" ::: 7788
#pragma line 114 "ed25519_sign/src/ed25519-donna.h" 2 ::: 7820
#pragma line 3 "ed25519_sign/src/test-internals.c" 2 ::: 7821
#pragma line 48 "ed25519_sign/src/test-internals.c" ::: 7848
#pragma line 120 "ed25519_sign/src/test-internals.c" ::: 7902
