#pragma line 1 "ed25519_sign/src/test.c" ::: 0
#pragma line 1 "ed25519_sign/src/test.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 289 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 427 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "ed25519_sign/src/test.c" 2 ::: 194
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 201
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 229
#pragma line 122 "/usr/include/features.h" 3 4 ::: 326
#pragma line 177 "/usr/include/features.h" 3 4 ::: 359
#pragma line 188 "/usr/include/features.h" 3 4 ::: 362
#pragma line 340 "/usr/include/features.h" 3 4 ::: 393
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 397
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 432
#pragma line 343 "/usr/include/features.h" 2 3 4 ::: 441
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 464
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 505
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 511
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 529
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 535
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 539
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 541
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 545
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 555
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 608
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 649
#pragma line 351 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 679
#pragma line 415 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 703
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 704
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 706
#pragma line 416 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 708
#pragma line 365 "/usr/include/features.h" 2 3 4 ::: 709
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 734
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 745
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 750
#pragma line 389 "/usr/include/features.h" 2 3 4 ::: 751
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 752
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 758
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 799
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 802
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 804
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 832
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 834
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 836
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 897
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 904
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 922
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 927
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 938
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 1007
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1021
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1024
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1025
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1057
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1073
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1098
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1101
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1106
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1128
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1149
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1152
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1163
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1173
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1175
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1179
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1228
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1229
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1235
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1237
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1257
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1268
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1309
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1339
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 1365
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1369
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1384
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1396
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1402
#pragma line 104 "/usr/include/stdio.h" 3 4 ::: 1404
#pragma line 121 "/usr/include/stdio.h" 3 4 ::: 1414
#pragma line 152 "/usr/include/stdio.h" 3 4 ::: 1436
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1452
#pragma line 167 "/usr/include/stdio.h" 2 3 4 ::: 1469
#pragma line 210 "/usr/include/stdio.h" 3 4 ::: 1501
#pragma line 270 "/usr/include/stdio.h" 3 4 ::: 1547
#pragma line 307 "/usr/include/stdio.h" 3 4 ::: 1561
#pragma line 320 "/usr/include/stdio.h" 3 4 ::: 1564
#pragma line 413 "/usr/include/stdio.h" 3 4 ::: 1640
#pragma line 469 "/usr/include/stdio.h" 3 4 ::: 1679
#pragma line 529 "/usr/include/stdio.h" 3 4 ::: 1720
#pragma line 657 "/usr/include/stdio.h" 3 4 ::: 1833
#pragma line 733 "/usr/include/stdio.h" 3 4 ::: 1896
#pragma line 796 "/usr/include/stdio.h" 3 4 ::: 1945
#pragma line 827 "/usr/include/stdio.h" 3 4 ::: 1956
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1986
#pragma line 856 "/usr/include/stdio.h" 2 3 4 ::: 2014
#pragma line 911 "/usr/include/stdio.h" 3 4 ::: 2046
#pragma line 932 "/usr/include/stdio.h" 3 4 ::: 2058
#pragma line 7 "ed25519_sign/src/test.c" 2 ::: 2061
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 2062
#pragma line 29 "/usr/include/string.h" 3 4 ::: 2083
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2088
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2113
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 2116
#pragma line 92 "/usr/include/string.h" 3 4 ::: 2153
#pragma line 124 "/usr/include/string.h" 3 4 ::: 2156
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2193
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 2236
#pragma line 207 "/usr/include/string.h" 3 4 ::: 2258
#pragma line 231 "/usr/include/string.h" 3 4 ::: 2260
#pragma line 258 "/usr/include/string.h" 3 4 ::: 2265
#pragma line 278 "/usr/include/string.h" 3 4 ::: 2268
#pragma line 310 "/usr/include/string.h" 3 4 ::: 2278
#pragma line 337 "/usr/include/string.h" 3 4 ::: 2283
#pragma line 393 "/usr/include/string.h" 3 4 ::: 2304
#pragma line 439 "/usr/include/string.h" 3 4 ::: 2335
#pragma line 484 "/usr/include/string.h" 3 4 ::: 2358
#pragma line 512 "/usr/include/string.h" 3 4 ::: 2364
#pragma line 550 "/usr/include/string.h" 3 4 ::: 2388
#pragma line 8 "ed25519_sign/src/test.c" 2 ::: 2414
#pragma line 1 "ed25519_sign/src/ed25519.h" 1 ::: 2415
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2419
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2452
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2477
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 2480
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 2490
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 2519
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 2537
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 2538
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2594
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 2597
#pragma line 263 "/usr/include/stdlib.h" 3 4 ::: 2719
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2733
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2754
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2771
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2793
#pragma line 115 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2801
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2810
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2811
#pragma line 58 "/usr/include/time.h" 3 4 ::: 2832
#pragma line 74 "/usr/include/time.h" 3 4 ::: 2835
#pragma line 90 "/usr/include/time.h" 3 4 ::: 2838
#pragma line 102 "/usr/include/time.h" 3 4 ::: 2841
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2844
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2845
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2846
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2871
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2874
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2884
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2916
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2953
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2955
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2959
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2962
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2980
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2981
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2983
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2985
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 2993
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 3011
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 3014
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 3017
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 3019
#pragma line 217 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3020
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 3024
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 3055
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3078
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3080
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 3082
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3083
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 3087
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3127
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3140
#pragma line 118 "/usr/include/time.h" 3 4 ::: 3161
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3169
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 3171
#pragma line 48 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3206
#pragma line 100 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 3251
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3281
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 3285
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 3303
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 3314
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3316
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3338
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 3342
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3364
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3366
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 3368
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3369
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3392
#pragma line 125 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3414
#pragma line 220 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3491
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3522
#pragma line 276 "/usr/include/stdlib.h" 2 3 4 ::: 3523
#pragma line 426 "/usr/include/stdlib.h" 3 4 ::: 3666
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3695
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3720
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3745
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3748
#pragma line 454 "/usr/include/stdlib.h" 2 3 4 ::: 3757
#pragma line 475 "/usr/include/stdlib.h" 3 4 ::: 3770
#pragma line 494 "/usr/include/stdlib.h" 3 4 ::: 3777
#pragma line 516 "/usr/include/stdlib.h" 3 4 ::: 3789
#pragma line 536 "/usr/include/stdlib.h" 3 4 ::: 3800
#pragma line 595 "/usr/include/stdlib.h" 3 4 ::: 3846
#pragma line 618 "/usr/include/stdlib.h" 3 4 ::: 3855
#pragma line 673 "/usr/include/stdlib.h" 3 4 ::: 3862
#pragma line 689 "/usr/include/stdlib.h" 3 4 ::: 3868
#pragma line 713 "/usr/include/stdlib.h" 3 4 ::: 3883
#pragma line 872 "/usr/include/stdlib.h" 3 4 ::: 4034
#pragma line 908 "/usr/include/stdlib.h" 3 4 ::: 4036
#pragma line 921 "/usr/include/stdlib.h" 3 4 ::: 4042
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 4043
#pragma line 922 "/usr/include/stdlib.h" 2 3 4 ::: 4061
#pragma line 5 "ed25519_sign/src/ed25519.h" 2 ::: 4064
#pragma line 9 "ed25519_sign/src/test.c" 2 ::: 4087
#pragma line 1 "ed25519_sign/src/test-ticks.h" 1 ::: 4089
#pragma line 1 "ed25519_sign/src/ed25519-donna-portable-identify.h" 1 ::: 4090
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/param.h" 1 3 4 ::: 4098
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4122
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4147
#pragma line 24 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 4150
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 1 3 4 ::: 4153
#pragma line 1 "/usr/include/limits.h" 1 3 4 ::: 4192
#pragma line 116 "/usr/include/limits.h" 3 4 ::: 4228
#pragma line 142 "/usr/include/limits.h" 3 4 ::: 4242
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 1 3 4 ::: 4245
#pragma line 95 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 3 4 ::: 4328
#pragma line 155 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 3 4 ::: 4371
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 1 3 4 ::: 4378
#pragma line 37 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 3 4 ::: 4402
#pragma line 1 "/usr/include/linux/limits.h" 1 3 4 ::: 4405
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 2 3 4 ::: 4406
#pragma line 161 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 2 3 4 ::: 4467
#pragma line 144 "/usr/include/limits.h" 2 3 4 ::: 4477
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 1 3 4 ::: 4481
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 3 4 ::: 4542
#pragma line 148 "/usr/include/limits.h" 2 3 4 ::: 4544
#pragma line 39 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 2 3 4 ::: 4545
#pragma line 60 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 4 ::: 4550
#pragma line 90 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 4 ::: 4552
#pragma line 102 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 4 ::: 4554
#pragma line 27 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 4559
#pragma line 1 "/usr/include/signal.h" 1 3 4 ::: 4561
#pragma line 32 "/usr/include/signal.h" 3 4 ::: 4582
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 4583
#pragma line 35 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 3 4 ::: 4601
#pragma line 48 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 3 4 ::: 4607
#pragma line 99 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 3 4 ::: 4613
#pragma line 33 "/usr/include/signal.h" 2 3 4 ::: 4620
#pragma line 57 "/usr/include/signal.h" 3 4 ::: 4629
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/signum.h" 1 3 4 ::: 4630
#pragma line 31 "/usr/include/x86_64-linux-gnu/bits/signum.h" 3 4 ::: 4652
#pragma line 74 "/usr/include/x86_64-linux-gnu/bits/signum.h" 3 4 ::: 4654
#pragma line 58 "/usr/include/signal.h" 2 3 4 ::: 4657
#pragma line 73 "/usr/include/signal.h" 3 4 ::: 4658
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 4662
#pragma line 76 "/usr/include/signal.h" 2 3 4 ::: 4683
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 1 3 4 ::: 4689
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 4714
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 4716
#pragma line 25 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 2 3 4 ::: 4718
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 4731
#pragma line 158 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 4811
#pragma line 263 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 4903
#pragma line 306 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 4937
#pragma line 81 "/usr/include/signal.h" 2 3 4 ::: 4991
#pragma line 123 "/usr/include/signal.h" 3 4 ::: 5015
#pragma line 178 "/usr/include/signal.h" 3 4 ::: 5058
#pragma line 205 "/usr/include/signal.h" 3 4 ::: 5075
#pragma line 241 "/usr/include/signal.h" 3 4 ::: 5098
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigaction.h" 1 3 4 ::: 5102
#pragma line 69 "/usr/include/x86_64-linux-gnu/bits/sigaction.h" 3 4 ::: 5155
#pragma line 244 "/usr/include/signal.h" 2 3 4 ::: 5163
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigcontext.h" 1 3 4 ::: 5227
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/sigcontext.h" 3 4 ::: 5244
#pragma line 121 "/usr/include/x86_64-linux-gnu/bits/sigcontext.h" 3 4 ::: 5271
#pragma line 307 "/usr/include/signal.h" 2 3 4 ::: 5344
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 5355
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 5380
#pragma line 317 "/usr/include/signal.h" 2 3 4 ::: 5383
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigstack.h" 1 3 4 ::: 5391
#pragma line 324 "/usr/include/signal.h" 2 3 4 ::: 5446
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/ucontext.h" 1 3 4 ::: 5450
#pragma line 1 "/usr/include/signal.h" 1 3 4 ::: 5473
#pragma line 23 "/usr/include/x86_64-linux-gnu/sys/ucontext.h" 2 3 4 ::: 5494
#pragma line 92 "/usr/include/x86_64-linux-gnu/sys/ucontext.h" 3 4 ::: 5510
#pragma line 327 "/usr/include/signal.h" 2 3 4 ::: 5561
#pragma line 359 "/usr/include/signal.h" 3 4 ::: 5574
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigthread.h" 1 3 4 ::: 5579
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/sigthread.h" 3 4 ::: 5597
#pragma line 363 "/usr/include/signal.h" 2 3 4 ::: 5608
#pragma line 29 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 5618
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/param.h" 1 3 4 ::: 5622
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/param.h" 3 4 ::: 5640
#pragma line 1 "/usr/include/linux/param.h" 1 3 4 ::: 5641
#pragma line 1 "/usr/include/x86_64-linux-gnu/asm/param.h" 1 3 4 ::: 5645
#pragma line 1 "/usr/include/asm-generic/param.h" 1 3 4 ::: 5646
#pragma line 2 "/usr/include/x86_64-linux-gnu/asm/param.h" 2 3 4 ::: 5647
#pragma line 5 "/usr/include/linux/param.h" 2 3 4 ::: 5648
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/param.h" 2 3 4 ::: 5649
#pragma line 32 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 5662
#pragma line 67 "/usr/include/x86_64-linux-gnu/sys/param.h" 3 4 ::: 5666
#pragma line 76 "/usr/include/x86_64-linux-gnu/sys/param.h" 3 4 ::: 5668
#pragma line 101 "/usr/include/x86_64-linux-gnu/sys/param.h" 3 4 ::: 5682
#pragma line 8 "ed25519_sign/src/ed25519-donna-portable-identify.h" 2 ::: 5684
#pragma line 24 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 5685
#pragma line 47 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 5687
#pragma line 86 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 5689
#pragma line 101 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 5691
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 1 3 ::: 5692
#pragma line 1 "/usr/include/stdint.h" 1 3 4 ::: 5726
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wchar.h" 1 3 4 ::: 5753
#pragma line 27 "/usr/include/stdint.h" 2 3 4 ::: 5785
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 5786
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 5788
#pragma line 28 "/usr/include/stdint.h" 2 3 4 ::: 5790
#pragma line 47 "/usr/include/stdint.h" 3 4 ::: 5797
#pragma line 116 "/usr/include/stdint.h" 3 4 ::: 5859
#pragma line 132 "/usr/include/stdint.h" 3 4 ::: 5867
#pragma line 152 "/usr/include/stdint.h" 3 4 ::: 5872
#pragma line 200 "/usr/include/stdint.h" 3 4 ::: 5912
#pragma line 211 "/usr/include/stdint.h" 3 4 ::: 5914
#pragma line 223 "/usr/include/stdint.h" 3 4 ::: 5916
#pragma line 235 "/usr/include/stdint.h" 3 4 ::: 5918
#pragma line 255 "/usr/include/stdint.h" 3 4 ::: 5931
#pragma line 270 "/usr/include/stdint.h" 3 4 ::: 5937
#pragma line 291 "/usr/include/stdint.h" 3 4 ::: 5950
#pragma line 301 "/usr/include/stdint.h" 3 4 ::: 5952
#pragma line 34 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 2 3 ::: 5954
#pragma line 102 "ed25519_sign/src/ed25519-donna-portable-identify.h" 2 ::: 5955
#pragma line 2 "ed25519_sign/src/test-ticks.h" 2 ::: 5956
#pragma line 40 "ed25519_sign/src/test-ticks.h" ::: 5970
#pragma line 11 "ed25519_sign/src/test.c" 2 ::: 5972
#pragma line 1 "ed25519_sign/src/regression.h" 1 ::: 6019
#pragma line 57 "ed25519_sign/src/test.c" 2 ::: 7044
