#pragma line 1 "ed25519_sign/src/test.c" ::: -10
#pragma line 1 "ed25519_sign/src/test.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 289 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 427 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "ed25519_sign/src/test.c" 2 ::: 184
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 191
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 219
#pragma line 122 "/usr/include/features.h" 3 4 ::: 316
#pragma line 177 "/usr/include/features.h" 3 4 ::: 349
#pragma line 188 "/usr/include/features.h" 3 4 ::: 352
#pragma line 340 "/usr/include/features.h" 3 4 ::: 383
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 387
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 422
#pragma line 343 "/usr/include/features.h" 2 3 4 ::: 431
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 454
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 495
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 501
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 519
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 525
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 529
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 531
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 535
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 545
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 598
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 639
#pragma line 351 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 669
#pragma line 415 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 693
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 694
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 696
#pragma line 416 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 698
#pragma line 365 "/usr/include/features.h" 2 3 4 ::: 699
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 724
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 735
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 740
#pragma line 389 "/usr/include/features.h" 2 3 4 ::: 741
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 742
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 748
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 789
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 792
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 794
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 822
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 824
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 826
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 887
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 894
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 912
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 917
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 928
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 997
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1011
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1014
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1015
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1047
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1063
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1088
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1091
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1096
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1118
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1139
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1142
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1153
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1163
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1165
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1169
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1218
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1219
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1225
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1227
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1247
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1258
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1299
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1329
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 1355
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1359
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1374
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1386
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1392
#pragma line 104 "/usr/include/stdio.h" 3 4 ::: 1394
#pragma line 121 "/usr/include/stdio.h" 3 4 ::: 1404
#pragma line 152 "/usr/include/stdio.h" 3 4 ::: 1426
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1442
#pragma line 167 "/usr/include/stdio.h" 2 3 4 ::: 1459
#pragma line 210 "/usr/include/stdio.h" 3 4 ::: 1491
#pragma line 270 "/usr/include/stdio.h" 3 4 ::: 1537
#pragma line 307 "/usr/include/stdio.h" 3 4 ::: 1551
#pragma line 320 "/usr/include/stdio.h" 3 4 ::: 1554
#pragma line 413 "/usr/include/stdio.h" 3 4 ::: 1630
#pragma line 469 "/usr/include/stdio.h" 3 4 ::: 1669
#pragma line 529 "/usr/include/stdio.h" 3 4 ::: 1710
#pragma line 657 "/usr/include/stdio.h" 3 4 ::: 1823
#pragma line 733 "/usr/include/stdio.h" 3 4 ::: 1886
#pragma line 796 "/usr/include/stdio.h" 3 4 ::: 1935
#pragma line 827 "/usr/include/stdio.h" 3 4 ::: 1946
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1976
#pragma line 856 "/usr/include/stdio.h" 2 3 4 ::: 2004
#pragma line 911 "/usr/include/stdio.h" 3 4 ::: 2036
#pragma line 932 "/usr/include/stdio.h" 3 4 ::: 2048
#pragma line 7 "ed25519_sign/src/test.c" 2 ::: 2051
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 2052
#pragma line 29 "/usr/include/string.h" 3 4 ::: 2073
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2078
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2103
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 2106
#pragma line 92 "/usr/include/string.h" 3 4 ::: 2143
#pragma line 124 "/usr/include/string.h" 3 4 ::: 2146
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2183
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 2226
#pragma line 207 "/usr/include/string.h" 3 4 ::: 2248
#pragma line 231 "/usr/include/string.h" 3 4 ::: 2250
#pragma line 258 "/usr/include/string.h" 3 4 ::: 2255
#pragma line 278 "/usr/include/string.h" 3 4 ::: 2258
#pragma line 310 "/usr/include/string.h" 3 4 ::: 2268
#pragma line 337 "/usr/include/string.h" 3 4 ::: 2273
#pragma line 393 "/usr/include/string.h" 3 4 ::: 2294
#pragma line 439 "/usr/include/string.h" 3 4 ::: 2325
#pragma line 484 "/usr/include/string.h" 3 4 ::: 2348
#pragma line 512 "/usr/include/string.h" 3 4 ::: 2354
#pragma line 550 "/usr/include/string.h" 3 4 ::: 2378
#pragma line 8 "ed25519_sign/src/test.c" 2 ::: 2404
#pragma line 1 "ed25519_sign/src/ed25519.h" 1 ::: 2405
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2409
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2442
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2467
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 2470
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 2480
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 2509
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 2527
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 2528
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2584
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 2587
#pragma line 263 "/usr/include/stdlib.h" 3 4 ::: 2709
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2723
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2744
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2761
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2783
#pragma line 115 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2791
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2800
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2801
#pragma line 58 "/usr/include/time.h" 3 4 ::: 2822
#pragma line 74 "/usr/include/time.h" 3 4 ::: 2825
#pragma line 90 "/usr/include/time.h" 3 4 ::: 2828
#pragma line 102 "/usr/include/time.h" 3 4 ::: 2831
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2834
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2835
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2836
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2861
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2864
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2874
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2906
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2943
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2945
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2949
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2952
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2970
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2971
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2973
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2975
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 2983
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 3001
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 3004
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 3007
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 3009
#pragma line 217 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3010
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 3014
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 3045
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3068
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3070
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 3072
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3073
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 3077
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3117
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3130
#pragma line 118 "/usr/include/time.h" 3 4 ::: 3151
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3159
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 3161
#pragma line 48 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3196
#pragma line 100 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 3241
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3271
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 3275
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 3293
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 3304
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3306
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3328
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 3332
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3354
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3356
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 3358
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3359
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3382
#pragma line 125 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3404
#pragma line 220 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3481
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3512
#pragma line 276 "/usr/include/stdlib.h" 2 3 4 ::: 3513
#pragma line 426 "/usr/include/stdlib.h" 3 4 ::: 3656
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3685
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3710
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3735
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3738
#pragma line 454 "/usr/include/stdlib.h" 2 3 4 ::: 3747
#pragma line 475 "/usr/include/stdlib.h" 3 4 ::: 3760
#pragma line 494 "/usr/include/stdlib.h" 3 4 ::: 3767
#pragma line 516 "/usr/include/stdlib.h" 3 4 ::: 3779
#pragma line 536 "/usr/include/stdlib.h" 3 4 ::: 3790
#pragma line 595 "/usr/include/stdlib.h" 3 4 ::: 3836
#pragma line 618 "/usr/include/stdlib.h" 3 4 ::: 3845
#pragma line 673 "/usr/include/stdlib.h" 3 4 ::: 3852
#pragma line 689 "/usr/include/stdlib.h" 3 4 ::: 3858
#pragma line 713 "/usr/include/stdlib.h" 3 4 ::: 3873
#pragma line 872 "/usr/include/stdlib.h" 3 4 ::: 4024
#pragma line 908 "/usr/include/stdlib.h" 3 4 ::: 4026
#pragma line 921 "/usr/include/stdlib.h" 3 4 ::: 4032
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 4033
#pragma line 922 "/usr/include/stdlib.h" 2 3 4 ::: 4051
#pragma line 5 "ed25519_sign/src/ed25519.h" 2 ::: 4054
#pragma line 9 "ed25519_sign/src/test.c" 2 ::: 4077
#pragma line 1 "ed25519_sign/src/test-ticks.h" 1 ::: 4079
#pragma line 1 "ed25519_sign/src/ed25519-donna-portable-identify.h" 1 ::: 4080
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/param.h" 1 3 4 ::: 4088
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4112
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4137
#pragma line 24 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 4140
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 1 3 4 ::: 4143
#pragma line 1 "/usr/include/limits.h" 1 3 4 ::: 4182
#pragma line 116 "/usr/include/limits.h" 3 4 ::: 4218
#pragma line 142 "/usr/include/limits.h" 3 4 ::: 4232
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 1 3 4 ::: 4235
#pragma line 95 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 3 4 ::: 4318
#pragma line 155 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 3 4 ::: 4361
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 1 3 4 ::: 4368
#pragma line 37 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 3 4 ::: 4392
#pragma line 1 "/usr/include/linux/limits.h" 1 3 4 ::: 4395
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 2 3 4 ::: 4396
#pragma line 161 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 2 3 4 ::: 4457
#pragma line 144 "/usr/include/limits.h" 2 3 4 ::: 4467
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 1 3 4 ::: 4471
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 3 4 ::: 4532
#pragma line 148 "/usr/include/limits.h" 2 3 4 ::: 4534
#pragma line 39 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 2 3 4 ::: 4535
#pragma line 60 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 4 ::: 4540
#pragma line 90 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 4 ::: 4542
#pragma line 102 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 4 ::: 4544
#pragma line 27 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 4549
#pragma line 1 "/usr/include/signal.h" 1 3 4 ::: 4551
#pragma line 32 "/usr/include/signal.h" 3 4 ::: 4572
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 4573
#pragma line 35 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 3 4 ::: 4591
#pragma line 48 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 3 4 ::: 4597
#pragma line 99 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 3 4 ::: 4603
#pragma line 33 "/usr/include/signal.h" 2 3 4 ::: 4610
#pragma line 57 "/usr/include/signal.h" 3 4 ::: 4619
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/signum.h" 1 3 4 ::: 4620
#pragma line 31 "/usr/include/x86_64-linux-gnu/bits/signum.h" 3 4 ::: 4642
#pragma line 74 "/usr/include/x86_64-linux-gnu/bits/signum.h" 3 4 ::: 4644
#pragma line 58 "/usr/include/signal.h" 2 3 4 ::: 4647
#pragma line 73 "/usr/include/signal.h" 3 4 ::: 4648
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 4652
#pragma line 76 "/usr/include/signal.h" 2 3 4 ::: 4673
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 1 3 4 ::: 4679
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 4704
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 4706
#pragma line 25 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 2 3 4 ::: 4708
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 4721
#pragma line 158 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 4801
#pragma line 263 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 4893
#pragma line 306 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 4927
#pragma line 81 "/usr/include/signal.h" 2 3 4 ::: 4981
#pragma line 123 "/usr/include/signal.h" 3 4 ::: 5005
#pragma line 178 "/usr/include/signal.h" 3 4 ::: 5048
#pragma line 205 "/usr/include/signal.h" 3 4 ::: 5065
#pragma line 241 "/usr/include/signal.h" 3 4 ::: 5088
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigaction.h" 1 3 4 ::: 5092
#pragma line 69 "/usr/include/x86_64-linux-gnu/bits/sigaction.h" 3 4 ::: 5145
#pragma line 244 "/usr/include/signal.h" 2 3 4 ::: 5153
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigcontext.h" 1 3 4 ::: 5217
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/sigcontext.h" 3 4 ::: 5234
#pragma line 121 "/usr/include/x86_64-linux-gnu/bits/sigcontext.h" 3 4 ::: 5261
#pragma line 307 "/usr/include/signal.h" 2 3 4 ::: 5334
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 5345
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 5370
#pragma line 317 "/usr/include/signal.h" 2 3 4 ::: 5373
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigstack.h" 1 3 4 ::: 5381
#pragma line 324 "/usr/include/signal.h" 2 3 4 ::: 5436
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/ucontext.h" 1 3 4 ::: 5440
#pragma line 1 "/usr/include/signal.h" 1 3 4 ::: 5463
#pragma line 23 "/usr/include/x86_64-linux-gnu/sys/ucontext.h" 2 3 4 ::: 5484
#pragma line 92 "/usr/include/x86_64-linux-gnu/sys/ucontext.h" 3 4 ::: 5500
#pragma line 327 "/usr/include/signal.h" 2 3 4 ::: 5551
#pragma line 359 "/usr/include/signal.h" 3 4 ::: 5564
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigthread.h" 1 3 4 ::: 5569
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/sigthread.h" 3 4 ::: 5587
#pragma line 363 "/usr/include/signal.h" 2 3 4 ::: 5598
#pragma line 29 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 5608
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/param.h" 1 3 4 ::: 5612
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/param.h" 3 4 ::: 5630
#pragma line 1 "/usr/include/linux/param.h" 1 3 4 ::: 5631
#pragma line 1 "/usr/include/x86_64-linux-gnu/asm/param.h" 1 3 4 ::: 5635
#pragma line 1 "/usr/include/asm-generic/param.h" 1 3 4 ::: 5636
#pragma line 2 "/usr/include/x86_64-linux-gnu/asm/param.h" 2 3 4 ::: 5637
#pragma line 5 "/usr/include/linux/param.h" 2 3 4 ::: 5638
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/param.h" 2 3 4 ::: 5639
#pragma line 32 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 5652
#pragma line 67 "/usr/include/x86_64-linux-gnu/sys/param.h" 3 4 ::: 5656
#pragma line 76 "/usr/include/x86_64-linux-gnu/sys/param.h" 3 4 ::: 5658
#pragma line 101 "/usr/include/x86_64-linux-gnu/sys/param.h" 3 4 ::: 5672
#pragma line 8 "ed25519_sign/src/ed25519-donna-portable-identify.h" 2 ::: 5674
#pragma line 24 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 5675
#pragma line 47 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 5677
#pragma line 86 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 5679
#pragma line 101 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 5681
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 1 3 ::: 5682
#pragma line 1 "/usr/include/stdint.h" 1 3 4 ::: 5716
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wchar.h" 1 3 4 ::: 5743
#pragma line 27 "/usr/include/stdint.h" 2 3 4 ::: 5775
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 5776
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 5778
#pragma line 28 "/usr/include/stdint.h" 2 3 4 ::: 5780
#pragma line 47 "/usr/include/stdint.h" 3 4 ::: 5787
#pragma line 116 "/usr/include/stdint.h" 3 4 ::: 5849
#pragma line 132 "/usr/include/stdint.h" 3 4 ::: 5857
#pragma line 152 "/usr/include/stdint.h" 3 4 ::: 5862
#pragma line 200 "/usr/include/stdint.h" 3 4 ::: 5902
#pragma line 211 "/usr/include/stdint.h" 3 4 ::: 5904
#pragma line 223 "/usr/include/stdint.h" 3 4 ::: 5906
#pragma line 235 "/usr/include/stdint.h" 3 4 ::: 5908
#pragma line 255 "/usr/include/stdint.h" 3 4 ::: 5921
#pragma line 270 "/usr/include/stdint.h" 3 4 ::: 5927
#pragma line 291 "/usr/include/stdint.h" 3 4 ::: 5940
#pragma line 301 "/usr/include/stdint.h" 3 4 ::: 5942
#pragma line 34 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 2 3 ::: 5944
#pragma line 102 "ed25519_sign/src/ed25519-donna-portable-identify.h" 2 ::: 5945
#pragma line 2 "ed25519_sign/src/test-ticks.h" 2 ::: 5946
#pragma line 40 "ed25519_sign/src/test-ticks.h" ::: 5960
#pragma line 11 "ed25519_sign/src/test.c" 2 ::: 5962
#pragma line 1 "ed25519_sign/src/regression.h" 1 ::: 6009
#pragma line 57 "ed25519_sign/src/test.c" 2 ::: 7034
#pragma line 127 "ed25519_sign/src/test.c" ::: 7107
#pragma line 128 "ed25519_sign/src/test.c" ::: 7111
#pragma line 129 "ed25519_sign/src/test.c" ::: 7115
