#pragma line 1 "ed25519_sign/src/test-internals.c" ::: -10
#pragma line 1 "ed25519_sign/src/test-internals.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 289 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 427 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "ed25519_sign/src/test-internals.c" 2 ::: 184
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 185
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 213
#pragma line 122 "/usr/include/features.h" 3 4 ::: 310
#pragma line 177 "/usr/include/features.h" 3 4 ::: 343
#pragma line 188 "/usr/include/features.h" 3 4 ::: 346
#pragma line 340 "/usr/include/features.h" 3 4 ::: 377
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 381
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 416
#pragma line 343 "/usr/include/features.h" 2 3 4 ::: 425
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 448
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 489
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 495
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 513
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 519
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 523
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 525
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 529
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 539
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 592
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 633
#pragma line 351 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 663
#pragma line 415 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 687
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 688
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 690
#pragma line 416 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 692
#pragma line 365 "/usr/include/features.h" 2 3 4 ::: 693
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 718
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 729
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 734
#pragma line 389 "/usr/include/features.h" 2 3 4 ::: 735
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 736
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 742
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 783
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 786
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 788
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 816
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 818
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 820
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 881
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 888
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 906
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 911
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 922
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 991
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1005
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1008
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1009
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1041
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1057
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1082
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1085
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1090
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1112
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1133
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1136
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1147
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1157
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1159
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1163
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1212
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1213
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1219
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1221
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1241
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1252
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1293
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1323
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 1349
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1353
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1368
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1380
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1386
#pragma line 104 "/usr/include/stdio.h" 3 4 ::: 1388
#pragma line 121 "/usr/include/stdio.h" 3 4 ::: 1398
#pragma line 152 "/usr/include/stdio.h" 3 4 ::: 1420
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1436
#pragma line 167 "/usr/include/stdio.h" 2 3 4 ::: 1453
#pragma line 210 "/usr/include/stdio.h" 3 4 ::: 1485
#pragma line 270 "/usr/include/stdio.h" 3 4 ::: 1531
#pragma line 307 "/usr/include/stdio.h" 3 4 ::: 1545
#pragma line 320 "/usr/include/stdio.h" 3 4 ::: 1548
#pragma line 413 "/usr/include/stdio.h" 3 4 ::: 1624
#pragma line 469 "/usr/include/stdio.h" 3 4 ::: 1663
#pragma line 529 "/usr/include/stdio.h" 3 4 ::: 1704
#pragma line 657 "/usr/include/stdio.h" 3 4 ::: 1817
#pragma line 733 "/usr/include/stdio.h" 3 4 ::: 1880
#pragma line 796 "/usr/include/stdio.h" 3 4 ::: 1929
#pragma line 827 "/usr/include/stdio.h" 3 4 ::: 1940
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1970
#pragma line 856 "/usr/include/stdio.h" 2 3 4 ::: 1998
#pragma line 911 "/usr/include/stdio.h" 3 4 ::: 2030
#pragma line 932 "/usr/include/stdio.h" 3 4 ::: 2042
#pragma line 2 "ed25519_sign/src/test-internals.c" 2 ::: 2045
#pragma line 1 "ed25519_sign/src/ed25519-donna.h" 1 ::: 2046
#pragma line 1 "ed25519_sign/src/ed25519-donna-portable.h" 1 ::: 2059
#pragma line 1 "ed25519_sign/src/ed25519-donna-portable-identify.h" 1 ::: 2060
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/param.h" 1 3 4 ::: 2068
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2092
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2117
#pragma line 24 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 2120
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2122
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2143
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2160
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2182
#pragma line 115 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2190
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2199
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2200
#pragma line 58 "/usr/include/time.h" 3 4 ::: 2221
#pragma line 74 "/usr/include/time.h" 3 4 ::: 2224
#pragma line 90 "/usr/include/time.h" 3 4 ::: 2227
#pragma line 102 "/usr/include/time.h" 3 4 ::: 2230
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2233
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2234
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2235
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2260
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2263
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2273
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2305
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2342
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2344
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2348
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2351
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2369
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2370
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2372
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2374
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 2382
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2400
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2403
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2406
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 2408
#pragma line 217 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2409
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 2413
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 2444
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2467
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2469
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 2471
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2472
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 2476
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2516
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2529
#pragma line 118 "/usr/include/time.h" 3 4 ::: 2550
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2558
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 2560
#pragma line 48 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2595
#pragma line 100 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 2640
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2670
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 2674
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 2692
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 2703
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2705
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2727
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 2731
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2753
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2755
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 2757
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 2758
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 2781
#pragma line 125 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 2803
#pragma line 220 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 2880
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2911
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 2912
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 1 3 4 ::: 2913
#pragma line 1 "/usr/include/limits.h" 1 3 4 ::: 2952
#pragma line 116 "/usr/include/limits.h" 3 4 ::: 2988
#pragma line 142 "/usr/include/limits.h" 3 4 ::: 3002
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 1 3 4 ::: 3005
#pragma line 95 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 3 4 ::: 3088
#pragma line 155 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 3 4 ::: 3131
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 1 3 4 ::: 3138
#pragma line 37 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 3 4 ::: 3162
#pragma line 1 "/usr/include/linux/limits.h" 1 3 4 ::: 3165
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 2 3 4 ::: 3166
#pragma line 161 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 2 3 4 ::: 3227
#pragma line 144 "/usr/include/limits.h" 2 3 4 ::: 3237
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 1 3 4 ::: 3241
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 3 4 ::: 3302
#pragma line 148 "/usr/include/limits.h" 2 3 4 ::: 3304
#pragma line 39 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 2 3 4 ::: 3305
#pragma line 60 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 4 ::: 3310
#pragma line 90 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 4 ::: 3312
#pragma line 102 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 4 ::: 3314
#pragma line 27 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 3319
#pragma line 1 "/usr/include/signal.h" 1 3 4 ::: 3321
#pragma line 32 "/usr/include/signal.h" 3 4 ::: 3342
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 3343
#pragma line 35 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 3 4 ::: 3361
#pragma line 48 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 3 4 ::: 3367
#pragma line 99 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 3 4 ::: 3373
#pragma line 33 "/usr/include/signal.h" 2 3 4 ::: 3380
#pragma line 57 "/usr/include/signal.h" 3 4 ::: 3389
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/signum.h" 1 3 4 ::: 3390
#pragma line 31 "/usr/include/x86_64-linux-gnu/bits/signum.h" 3 4 ::: 3412
#pragma line 74 "/usr/include/x86_64-linux-gnu/bits/signum.h" 3 4 ::: 3414
#pragma line 58 "/usr/include/signal.h" 2 3 4 ::: 3417
#pragma line 73 "/usr/include/signal.h" 3 4 ::: 3418
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3422
#pragma line 76 "/usr/include/signal.h" 2 3 4 ::: 3443
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 1 3 4 ::: 3449
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3474
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3476
#pragma line 25 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 2 3 4 ::: 3478
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 3491
#pragma line 158 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 3571
#pragma line 263 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 3663
#pragma line 306 "/usr/include/x86_64-linux-gnu/bits/siginfo.h" 3 4 ::: 3697
#pragma line 81 "/usr/include/signal.h" 2 3 4 ::: 3751
#pragma line 123 "/usr/include/signal.h" 3 4 ::: 3775
#pragma line 178 "/usr/include/signal.h" 3 4 ::: 3818
#pragma line 205 "/usr/include/signal.h" 3 4 ::: 3835
#pragma line 241 "/usr/include/signal.h" 3 4 ::: 3858
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigaction.h" 1 3 4 ::: 3862
#pragma line 69 "/usr/include/x86_64-linux-gnu/bits/sigaction.h" 3 4 ::: 3915
#pragma line 244 "/usr/include/signal.h" 2 3 4 ::: 3923
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigcontext.h" 1 3 4 ::: 3987
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/sigcontext.h" 3 4 ::: 4004
#pragma line 121 "/usr/include/x86_64-linux-gnu/bits/sigcontext.h" 3 4 ::: 4031
#pragma line 307 "/usr/include/signal.h" 2 3 4 ::: 4104
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4115
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4140
#pragma line 317 "/usr/include/signal.h" 2 3 4 ::: 4143
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigstack.h" 1 3 4 ::: 4151
#pragma line 324 "/usr/include/signal.h" 2 3 4 ::: 4206
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/ucontext.h" 1 3 4 ::: 4210
#pragma line 1 "/usr/include/signal.h" 1 3 4 ::: 4233
#pragma line 23 "/usr/include/x86_64-linux-gnu/sys/ucontext.h" 2 3 4 ::: 4254
#pragma line 92 "/usr/include/x86_64-linux-gnu/sys/ucontext.h" 3 4 ::: 4270
#pragma line 327 "/usr/include/signal.h" 2 3 4 ::: 4321
#pragma line 359 "/usr/include/signal.h" 3 4 ::: 4334
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigthread.h" 1 3 4 ::: 4339
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/sigthread.h" 3 4 ::: 4357
#pragma line 363 "/usr/include/signal.h" 2 3 4 ::: 4368
#pragma line 29 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 4378
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/param.h" 1 3 4 ::: 4382
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/param.h" 3 4 ::: 4400
#pragma line 1 "/usr/include/linux/param.h" 1 3 4 ::: 4401
#pragma line 1 "/usr/include/x86_64-linux-gnu/asm/param.h" 1 3 4 ::: 4405
#pragma line 1 "/usr/include/asm-generic/param.h" 1 3 4 ::: 4406
#pragma line 2 "/usr/include/x86_64-linux-gnu/asm/param.h" 2 3 4 ::: 4407
#pragma line 5 "/usr/include/linux/param.h" 2 3 4 ::: 4408
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/param.h" 2 3 4 ::: 4409
#pragma line 32 "/usr/include/x86_64-linux-gnu/sys/param.h" 2 3 4 ::: 4422
#pragma line 67 "/usr/include/x86_64-linux-gnu/sys/param.h" 3 4 ::: 4426
#pragma line 76 "/usr/include/x86_64-linux-gnu/sys/param.h" 3 4 ::: 4428
#pragma line 101 "/usr/include/x86_64-linux-gnu/sys/param.h" 3 4 ::: 4442
#pragma line 8 "ed25519_sign/src/ed25519-donna-portable-identify.h" 2 ::: 4444
#pragma line 24 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 4445
#pragma line 47 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 4447
#pragma line 86 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 4449
#pragma line 101 "ed25519_sign/src/ed25519-donna-portable-identify.h" ::: 4451
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 1 3 ::: 4452
#pragma line 1 "/usr/include/stdint.h" 1 3 4 ::: 4486
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wchar.h" 1 3 4 ::: 4513
#pragma line 27 "/usr/include/stdint.h" 2 3 4 ::: 4545
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 4546
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 4548
#pragma line 28 "/usr/include/stdint.h" 2 3 4 ::: 4550
#pragma line 47 "/usr/include/stdint.h" 3 4 ::: 4557
#pragma line 116 "/usr/include/stdint.h" 3 4 ::: 4619
#pragma line 132 "/usr/include/stdint.h" 3 4 ::: 4627
#pragma line 152 "/usr/include/stdint.h" 3 4 ::: 4632
#pragma line 200 "/usr/include/stdint.h" 3 4 ::: 4672
#pragma line 211 "/usr/include/stdint.h" 3 4 ::: 4674
#pragma line 223 "/usr/include/stdint.h" 3 4 ::: 4676
#pragma line 235 "/usr/include/stdint.h" 3 4 ::: 4678
#pragma line 255 "/usr/include/stdint.h" 3 4 ::: 4691
#pragma line 270 "/usr/include/stdint.h" 3 4 ::: 4697
#pragma line 291 "/usr/include/stdint.h" 3 4 ::: 4710
#pragma line 301 "/usr/include/stdint.h" 3 4 ::: 4712
#pragma line 34 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 2 3 ::: 4714
#pragma line 102 "ed25519_sign/src/ed25519-donna-portable-identify.h" 2 ::: 4715
#pragma line 2 "ed25519_sign/src/ed25519-donna-portable.h" 2 ::: 4716
#pragma line 28 "ed25519_sign/src/ed25519-donna-portable.h" ::: 4721
#pragma line 89 "ed25519_sign/src/ed25519-donna-portable.h" ::: 4727
#pragma line 108 "ed25519_sign/src/ed25519-donna-portable.h" ::: 4736
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 4762
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4795
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4820
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 4823
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 4833
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 4862
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 4880
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 4881
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 4937
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 4940
#pragma line 263 "/usr/include/stdlib.h" 3 4 ::: 5062
#pragma line 426 "/usr/include/stdlib.h" 3 4 ::: 5218
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 5247
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 5272
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 5297
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 5300
#pragma line 454 "/usr/include/stdlib.h" 2 3 4 ::: 5309
#pragma line 475 "/usr/include/stdlib.h" 3 4 ::: 5322
#pragma line 494 "/usr/include/stdlib.h" 3 4 ::: 5329
#pragma line 516 "/usr/include/stdlib.h" 3 4 ::: 5341
#pragma line 536 "/usr/include/stdlib.h" 3 4 ::: 5352
#pragma line 595 "/usr/include/stdlib.h" 3 4 ::: 5398
#pragma line 618 "/usr/include/stdlib.h" 3 4 ::: 5407
#pragma line 673 "/usr/include/stdlib.h" 3 4 ::: 5414
#pragma line 689 "/usr/include/stdlib.h" 3 4 ::: 5420
#pragma line 713 "/usr/include/stdlib.h" 3 4 ::: 5435
#pragma line 872 "/usr/include/stdlib.h" 3 4 ::: 5586
#pragma line 908 "/usr/include/stdlib.h" 3 4 ::: 5588
#pragma line 921 "/usr/include/stdlib.h" 3 4 ::: 5594
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 5595
#pragma line 922 "/usr/include/stdlib.h" 2 3 4 ::: 5613
#pragma line 133 "ed25519_sign/src/ed25519-donna-portable.h" 2 ::: 5616
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 5617
#pragma line 29 "/usr/include/string.h" 3 4 ::: 5638
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 5643
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 5668
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 5671
#pragma line 92 "/usr/include/string.h" 3 4 ::: 5708
#pragma line 124 "/usr/include/string.h" 3 4 ::: 5711
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 5748
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 5791
#pragma line 207 "/usr/include/string.h" 3 4 ::: 5813
#pragma line 231 "/usr/include/string.h" 3 4 ::: 5815
#pragma line 258 "/usr/include/string.h" 3 4 ::: 5820
#pragma line 278 "/usr/include/string.h" 3 4 ::: 5823
#pragma line 310 "/usr/include/string.h" 3 4 ::: 5833
#pragma line 337 "/usr/include/string.h" 3 4 ::: 5838
#pragma line 393 "/usr/include/string.h" 3 4 ::: 5859
#pragma line 439 "/usr/include/string.h" 3 4 ::: 5890
#pragma line 484 "/usr/include/string.h" 3 4 ::: 5913
#pragma line 512 "/usr/include/string.h" 3 4 ::: 5919
#pragma line 550 "/usr/include/string.h" 3 4 ::: 5943
#pragma line 134 "ed25519_sign/src/ed25519-donna-portable.h" 2 ::: 5969
#pragma line 13 "ed25519_sign/src/ed25519-donna.h" 2 ::: 5970
#pragma line 24 "ed25519_sign/src/ed25519-donna.h" ::: 5971
#pragma line 47 "ed25519_sign/src/ed25519-donna.h" ::: 5973
#pragma line 1 "ed25519_sign/src/curve25519-donna-64bit.h" 1 ::: 5974
#pragma line 140 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 6106
#pragma line 158 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 6117
#pragma line 215 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 6167
#pragma line 271 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 6216
#pragma line 308 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 6244
#pragma line 347 "ed25519_sign/src/curve25519-donna-64bit.h" ::: 6271
#pragma line 48 "ed25519_sign/src/ed25519-donna.h" 2 ::: 6334
#pragma line 1 "ed25519_sign/src/curve25519-donna-helpers.h" 1 ::: 6339
#pragma line 53 "ed25519_sign/src/ed25519-donna.h" 2 ::: 6407
#pragma line 1 "ed25519_sign/src/modm-donna-64bit.h" 1 ::: 6412
#pragma line 57 "ed25519_sign/src/ed25519-donna.h" 2 ::: 6774
#pragma line 1 "ed25519_sign/src/ed25519-donna-basepoint-table.h" 1 ::: 6816
#pragma line 98 "ed25519_sign/src/ed25519-donna.h" 2 ::: 7076
#pragma line 1 "ed25519_sign/src/ed25519-donna-64bit-tables.h" 1 ::: 7079
#pragma line 101 "ed25519_sign/src/ed25519-donna.h" 2 ::: 7133
#pragma line 1 "ed25519_sign/src/ed25519-donna-64bit-x86.h" 1 ::: 7134
#pragma line 102 "ed25519_sign/src/ed25519-donna.h" 2 ::: 7483
#pragma line 113 "ed25519_sign/src/ed25519-donna.h" ::: 7484
#pragma line 1 "ed25519_sign/src/ed25519-donna-impl-base.h" 1 ::: 7485
#pragma line 71 "ed25519_sign/src/ed25519-donna-impl-base.h" ::: 7558
#pragma line 90 "ed25519_sign/src/ed25519-donna-impl-base.h" ::: 7580
#pragma line 193 "ed25519_sign/src/ed25519-donna-impl-base.h" ::: 7686
#pragma line 194 "ed25519_sign/src/ed25519-donna-impl-base.h" ::: 7690
#pragma line 333 "ed25519_sign/src/ed25519-donna-impl-base.h" ::: 7790
#pragma line 114 "ed25519_sign/src/ed25519-donna.h" 2 ::: 7822
#pragma line 3 "ed25519_sign/src/test-internals.c" 2 ::: 7823
#pragma line 10 "ed25519_sign/src/test-internals.c" ::: 7833
#pragma line 16 "ed25519_sign/src/test-internals.c" ::: 7842
#pragma line 22 "ed25519_sign/src/test-internals.c" ::: 7851
#pragma line 28 "ed25519_sign/src/test-internals.c" ::: 7860
#pragma line 48 "ed25519_sign/src/test-internals.c" ::: 7862
#pragma line 49 "ed25519_sign/src/test-internals.c" ::: 7866
#pragma line 88 "ed25519_sign/src/test-internals.c" ::: 7908
#pragma line 94 "ed25519_sign/src/test-internals.c" ::: 7917
#pragma line 100 "ed25519_sign/src/test-internals.c" ::: 7926
#pragma line 120 "ed25519_sign/src/test-internals.c" ::: 7928
#pragma line 121 "ed25519_sign/src/test-internals.c" ::: 7932
