#pragma line 1 "curve25519/src/curve25519-donna.c" ::: 0
#pragma line 1 "curve25519/src/curve25519-donna.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 289 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 427 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "curve25519/src/curve25519-donna.c" 2 ::: 194
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 243
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 269
#pragma line 122 "/usr/include/features.h" 3 4 ::: 366
#pragma line 177 "/usr/include/features.h" 3 4 ::: 399
#pragma line 188 "/usr/include/features.h" 3 4 ::: 402
#pragma line 340 "/usr/include/features.h" 3 4 ::: 433
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 437
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 472
#pragma line 343 "/usr/include/features.h" 2 3 4 ::: 481
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 504
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 545
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 551
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 569
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 575
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 579
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 581
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 585
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 595
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 648
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 689
#pragma line 351 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 719
#pragma line 415 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 743
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 744
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 746
#pragma line 416 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 748
#pragma line 365 "/usr/include/features.h" 2 3 4 ::: 749
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 774
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 785
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 790
#pragma line 389 "/usr/include/features.h" 2 3 4 ::: 791
#pragma line 26 "/usr/include/string.h" 2 3 4 ::: 792
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 800
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 841
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 844
#pragma line 92 "/usr/include/string.h" 3 4 ::: 881
#pragma line 124 "/usr/include/string.h" 3 4 ::: 884
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 921
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 964
#pragma line 207 "/usr/include/string.h" 3 4 ::: 986
#pragma line 231 "/usr/include/string.h" 3 4 ::: 988
#pragma line 258 "/usr/include/string.h" 3 4 ::: 993
#pragma line 278 "/usr/include/string.h" 3 4 ::: 996
#pragma line 310 "/usr/include/string.h" 3 4 ::: 1006
#pragma line 337 "/usr/include/string.h" 3 4 ::: 1011
#pragma line 393 "/usr/include/string.h" 3 4 ::: 1032
#pragma line 439 "/usr/include/string.h" 3 4 ::: 1063
#pragma line 484 "/usr/include/string.h" 3 4 ::: 1086
#pragma line 512 "/usr/include/string.h" 3 4 ::: 1092
#pragma line 550 "/usr/include/string.h" 3 4 ::: 1116
#pragma line 49 "curve25519/src/curve25519-donna.c" 2 ::: 1142
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 1 3 ::: 1143
#pragma line 1 "/usr/include/stdint.h" 1 3 4 ::: 1177
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wchar.h" 1 3 4 ::: 1204
#pragma line 27 "/usr/include/stdint.h" 2 3 4 ::: 1236
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1237
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1239
#pragma line 28 "/usr/include/stdint.h" 2 3 4 ::: 1241
#pragma line 116 "/usr/include/stdint.h" 3 4 ::: 1322
#pragma line 132 "/usr/include/stdint.h" 3 4 ::: 1330
#pragma line 152 "/usr/include/stdint.h" 3 4 ::: 1335
#pragma line 200 "/usr/include/stdint.h" 3 4 ::: 1375
#pragma line 211 "/usr/include/stdint.h" 3 4 ::: 1377
#pragma line 223 "/usr/include/stdint.h" 3 4 ::: 1379
#pragma line 235 "/usr/include/stdint.h" 3 4 ::: 1381
#pragma line 255 "/usr/include/stdint.h" 3 4 ::: 1394
#pragma line 270 "/usr/include/stdint.h" 3 4 ::: 1400
#pragma line 291 "/usr/include/stdint.h" 3 4 ::: 1413
#pragma line 301 "/usr/include/stdint.h" 3 4 ::: 1415
#pragma line 34 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 2 3 ::: 1417
#pragma line 50 "curve25519/src/curve25519-donna.c" 2 ::: 1418
