#pragma line 1 "curve25519/src/curve25519-donna.c" ::: -10
#pragma line 1 "curve25519/src/curve25519-donna.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 289 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 427 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "curve25519/src/curve25519-donna.c" 2 ::: 184
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 233
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 259
#pragma line 122 "/usr/include/features.h" 3 4 ::: 356
#pragma line 177 "/usr/include/features.h" 3 4 ::: 389
#pragma line 188 "/usr/include/features.h" 3 4 ::: 392
#pragma line 340 "/usr/include/features.h" 3 4 ::: 423
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 427
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 462
#pragma line 343 "/usr/include/features.h" 2 3 4 ::: 471
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 494
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 535
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 541
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 559
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 565
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 569
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 571
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 575
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 585
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 638
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 679
#pragma line 351 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 709
#pragma line 415 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 733
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 734
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 736
#pragma line 416 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 738
#pragma line 365 "/usr/include/features.h" 2 3 4 ::: 739
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 764
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 775
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 780
#pragma line 389 "/usr/include/features.h" 2 3 4 ::: 781
#pragma line 26 "/usr/include/string.h" 2 3 4 ::: 782
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 790
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 831
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 834
#pragma line 92 "/usr/include/string.h" 3 4 ::: 871
#pragma line 124 "/usr/include/string.h" 3 4 ::: 874
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 911
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 954
#pragma line 207 "/usr/include/string.h" 3 4 ::: 976
#pragma line 231 "/usr/include/string.h" 3 4 ::: 978
#pragma line 258 "/usr/include/string.h" 3 4 ::: 983
#pragma line 278 "/usr/include/string.h" 3 4 ::: 986
#pragma line 310 "/usr/include/string.h" 3 4 ::: 996
#pragma line 337 "/usr/include/string.h" 3 4 ::: 1001
#pragma line 393 "/usr/include/string.h" 3 4 ::: 1022
#pragma line 439 "/usr/include/string.h" 3 4 ::: 1053
#pragma line 484 "/usr/include/string.h" 3 4 ::: 1076
#pragma line 512 "/usr/include/string.h" 3 4 ::: 1082
#pragma line 550 "/usr/include/string.h" 3 4 ::: 1106
#pragma line 49 "curve25519/src/curve25519-donna.c" 2 ::: 1132
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 1 3 ::: 1133
#pragma line 1 "/usr/include/stdint.h" 1 3 4 ::: 1167
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wchar.h" 1 3 4 ::: 1194
#pragma line 27 "/usr/include/stdint.h" 2 3 4 ::: 1226
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1227
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1229
#pragma line 28 "/usr/include/stdint.h" 2 3 4 ::: 1231
#pragma line 116 "/usr/include/stdint.h" 3 4 ::: 1312
#pragma line 132 "/usr/include/stdint.h" 3 4 ::: 1320
#pragma line 152 "/usr/include/stdint.h" 3 4 ::: 1325
#pragma line 200 "/usr/include/stdint.h" 3 4 ::: 1365
#pragma line 211 "/usr/include/stdint.h" 3 4 ::: 1367
#pragma line 223 "/usr/include/stdint.h" 3 4 ::: 1369
#pragma line 235 "/usr/include/stdint.h" 3 4 ::: 1371
#pragma line 255 "/usr/include/stdint.h" 3 4 ::: 1384
#pragma line 270 "/usr/include/stdint.h" 3 4 ::: 1390
#pragma line 291 "/usr/include/stdint.h" 3 4 ::: 1403
#pragma line 301 "/usr/include/stdint.h" 3 4 ::: 1405
#pragma line 34 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 2 3 ::: 1407
#pragma line 50 "curve25519/src/curve25519-donna.c" 2 ::: 1408
