#pragma line 1 "contact_discovery/src/contact_discovery.cpp" ::: -10
#pragma line 1 "contact_discovery/src/contact_discovery.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 155 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 1
#pragma line 145 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 54
#pragma line 156 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 57
#pragma line 413 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 187
#pragma line 427 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 7 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "contact_discovery/src/contact_discovery.cpp" 2 ::: 194
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/hls_stream.h" 1 ::: 195
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_enum.h" 1 ::: 262
#pragma line 67 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/hls_stream.h" 2 ::: 397
#pragma line 2 "contact_discovery/src/contact_discovery.cpp" 2 ::: 503
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 504
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 532
#pragma line 122 "/usr/include/features.h" 3 4 ::: 629
#pragma line 156 "/usr/include/features.h" 3 4 ::: 654
#pragma line 180 "/usr/include/features.h" 3 4 ::: 656
#pragma line 191 "/usr/include/features.h" 3 4 ::: 659
#pragma line 343 "/usr/include/features.h" 3 4 ::: 690
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 694
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 729
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 736
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 759
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 800
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 806
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 824
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 830
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 834
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 836
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 840
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 850
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 903
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 944
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 969
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 993
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 994
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 996
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 998
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 999
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 1024
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 1035
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 1040
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 1041
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 1042
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1049
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1085
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 1088
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 1090
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1118
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1120
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1122
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 1183
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 1190
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1208
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1213
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1224
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 1293
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1307
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1310
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1311
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1343
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1359
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1384
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1387
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1392
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1414
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1435
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1438
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1449
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1459
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1461
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1465
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1514
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1515
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1521
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1523
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1543
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1554
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1595
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1625
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1685
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1700
#pragma line 521 "/usr/include/libio.h" 3 4 ::: 1712
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1714
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1720
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1771
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1787
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1804
#pragma line 205 "/usr/include/stdio.h" 3 4 ::: 1836
#pragma line 297 "/usr/include/stdio.h" 3 4 ::: 1913
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 2052
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 2072
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 2325
#pragma line 818 "/usr/include/stdio.h" 3 4 ::: 2336
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2373
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2405
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2472
#pragma line 942 "/usr/include/stdio.h" 3 4 ::: 2475
#pragma line 3 "contact_discovery/src/contact_discovery.cpp" 2 ::: 2477
