#pragma line 1 "contact_discovery/src/contact_discovery.cpp" ::: 0
#pragma line 1 "contact_discovery/src/contact_discovery.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 155 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 11
#pragma line 145 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 64
#pragma line 156 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 67
#pragma line 413 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 197
#pragma line 427 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 200
#pragma line 7 "<command line>" 2 ::: 202
#pragma line 1 "<built-in>" 2 ::: 203
#pragma line 1 "contact_discovery/src/contact_discovery.cpp" 2 ::: 204
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/hls_stream.h" 1 ::: 205
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_enum.h" 1 ::: 272
#pragma line 67 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/hls_stream.h" 2 ::: 407
#pragma line 2 "contact_discovery/src/contact_discovery.cpp" 2 ::: 513
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 514
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 542
#pragma line 122 "/usr/include/features.h" 3 4 ::: 639
#pragma line 156 "/usr/include/features.h" 3 4 ::: 664
#pragma line 180 "/usr/include/features.h" 3 4 ::: 666
#pragma line 191 "/usr/include/features.h" 3 4 ::: 669
#pragma line 343 "/usr/include/features.h" 3 4 ::: 700
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 704
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 739
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 746
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 769
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 810
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 816
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 834
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 840
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 844
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 846
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 850
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 860
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 913
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 954
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 979
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 1003
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1004
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1006
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 1008
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 1009
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 1034
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 1045
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 1050
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 1051
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 1052
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1059
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1095
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 1098
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 1100
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1128
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1130
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1132
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 1193
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 1200
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1218
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1223
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1234
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 1303
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1317
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1320
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1321
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1353
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1369
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1394
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1397
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1402
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1424
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1445
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1448
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1459
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1469
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1471
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1475
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1524
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1525
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1531
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1533
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1553
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1564
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1605
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1635
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1695
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1710
#pragma line 521 "/usr/include/libio.h" 3 4 ::: 1722
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1724
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1730
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1781
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1797
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1814
#pragma line 205 "/usr/include/stdio.h" 3 4 ::: 1846
#pragma line 297 "/usr/include/stdio.h" 3 4 ::: 1923
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 2062
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 2082
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 2335
#pragma line 818 "/usr/include/stdio.h" 3 4 ::: 2346
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2383
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2415
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2482
#pragma line 942 "/usr/include/stdio.h" 3 4 ::: 2485
#pragma line 3 "contact_discovery/src/contact_discovery.cpp" 2 ::: 2487
