#pragma line 1 "contact_discovery_axi_experimental/src/contact_discovery.cpp" ::: -10
#pragma line 1 "contact_discovery_axi_experimental/src/contact_discovery.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 155 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 1
#pragma line 145 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 54
#pragma line 156 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 57
#pragma line 413 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 187
#pragma line 427 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 7 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "contact_discovery_axi_experimental/src/contact_discovery.cpp" 2 ::: 194
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/hls_stream.h" 1 ::: 195
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_enum.h" 1 ::: 262
#pragma line 67 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/hls_stream.h" 2 ::: 397
#pragma line 2 "contact_discovery_axi_experimental/src/contact_discovery.cpp" 2 ::: 503
#pragma line 1 "/usr/include/assert.h" 1 3 4 ::: 504
#pragma line 35 "/usr/include/assert.h" 3 4 ::: 525
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 526
#pragma line 122 "/usr/include/features.h" 3 4 ::: 623
#pragma line 156 "/usr/include/features.h" 3 4 ::: 648
#pragma line 180 "/usr/include/features.h" 3 4 ::: 650
#pragma line 191 "/usr/include/features.h" 3 4 ::: 653
#pragma line 343 "/usr/include/features.h" 3 4 ::: 684
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 688
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 723
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 730
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 753
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 794
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 800
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 818
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 824
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 828
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 830
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 834
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 844
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 897
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 938
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 963
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 987
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 988
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 990
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 992
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 993
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 1018
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 1029
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 1034
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 1035
#pragma line 36 "/usr/include/assert.h" 2 3 4 ::: 1036
#pragma line 66 "/usr/include/assert.h" 3 4 ::: 1048
#pragma line 100 "/usr/include/assert.h" 3 4 ::: 1069
#pragma line 3 "contact_discovery_axi_experimental/src/contact_discovery.cpp" 2 ::: 1075
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 1076
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1110
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1146
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 1149
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 1151
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1179
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1181
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1183
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 1244
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 1251
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1269
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1274
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1285
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 1354
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1368
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1371
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1372
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1404
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1420
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1445
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1448
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1453
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1475
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1496
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1499
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1510
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1520
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1522
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1526
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1575
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1576
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1582
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1584
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1604
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1615
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1656
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1686
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1746
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1761
#pragma line 521 "/usr/include/libio.h" 3 4 ::: 1773
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1775
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1781
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1832
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1848
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1865
#pragma line 205 "/usr/include/stdio.h" 3 4 ::: 1897
#pragma line 297 "/usr/include/stdio.h" 3 4 ::: 1974
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 2113
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 2133
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 2386
#pragma line 818 "/usr/include/stdio.h" 3 4 ::: 2397
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2434
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2466
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2533
#pragma line 942 "/usr/include/stdio.h" 3 4 ::: 2536
#pragma line 4 "contact_discovery_axi_experimental/src/contact_discovery.cpp" 2 ::: 2538
