#pragma line 1 "ed25519_ref/src/sc25519.c" ::: 0
#pragma line 1 "ed25519_ref/src/sc25519.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 289 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 427 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "ed25519_ref/src/sc25519.c" 2 ::: 194
#pragma line 1 "ed25519_ref/src/sc25519.h" 1 ::: 195
#pragma line 1 "ed25519_ref/src/crypto_int32.h" 1 ::: 199
#pragma line 5 "ed25519_ref/src/sc25519.h" 2 ::: 204
#pragma line 1 "ed25519_ref/src/crypto_uint32.h" 1 ::: 205
#pragma line 6 "ed25519_ref/src/sc25519.h" 2 ::: 210
#pragma line 25 "ed25519_ref/src/sc25519.h" ::: 211
#pragma line 2 "ed25519_ref/src/sc25519.c" 2 ::: 259
