#pragma line 1 "ed25519_ref/src/sha512.c" ::: 0
#pragma line 1 "ed25519_ref/src/sha512.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 289 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 427 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "ed25519_ref/src/sha512.c" 2 ::: 194
#pragma line 1 "ed25519_ref/src/fixedint.h" 1 ::: 207
#pragma line 21 "ed25519_ref/src/fixedint.h" ::: 213
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 1 3 ::: 214
#pragma line 1 "/usr/include/limits.h" 1 3 4 ::: 253
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 279
#pragma line 122 "/usr/include/features.h" 3 4 ::: 376
#pragma line 177 "/usr/include/features.h" 3 4 ::: 409
#pragma line 188 "/usr/include/features.h" 3 4 ::: 412
#pragma line 340 "/usr/include/features.h" 3 4 ::: 443
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 447
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 482
#pragma line 343 "/usr/include/features.h" 2 3 4 ::: 491
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 514
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 555
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 561
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 579
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 585
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 589
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 591
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 595
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 605
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 658
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 699
#pragma line 351 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 729
#pragma line 415 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 753
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 754
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 756
#pragma line 416 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 758
#pragma line 365 "/usr/include/features.h" 2 3 4 ::: 759
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 784
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 795
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 800
#pragma line 389 "/usr/include/features.h" 2 3 4 ::: 801
#pragma line 26 "/usr/include/limits.h" 2 3 4 ::: 802
#pragma line 116 "/usr/include/limits.h" 3 4 ::: 813
#pragma line 142 "/usr/include/limits.h" 3 4 ::: 827
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 1 3 4 ::: 830
#pragma line 95 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 3 4 ::: 913
#pragma line 155 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 3 4 ::: 956
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 1 3 4 ::: 963
#pragma line 37 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 3 4 ::: 987
#pragma line 1 "/usr/include/linux/limits.h" 1 3 4 ::: 990
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 2 3 4 ::: 991
#pragma line 161 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 2 3 4 ::: 1052
#pragma line 144 "/usr/include/limits.h" 2 3 4 ::: 1062
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 1 3 4 ::: 1066
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 3 4 ::: 1127
#pragma line 148 "/usr/include/limits.h" 2 3 4 ::: 1129
#pragma line 39 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 2 3 ::: 1130
#pragma line 60 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1135
#pragma line 90 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1137
#pragma line 102 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1139
#pragma line 22 "ed25519_ref/src/fixedint.h" 2 ::: 1144
#pragma line 39 "ed25519_ref/src/fixedint.h" ::: 1152
#pragma line 13 "ed25519_ref/src/sha512.c" 2 ::: 1171
#pragma line 1 "ed25519_ref/src/sha512.h" 1 ::: 1172
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 1176
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 1217
#pragma line 5 "ed25519_ref/src/sha512.h" 2 ::: 1220
#pragma line 1 "ed25519_ref/src/fixedint.h" 1 ::: 1222
#pragma line 7 "ed25519_ref/src/sha512.h" 2 ::: 1228
#pragma line 14 "ed25519_ref/src/sha512.c" 2 ::: 1247
#pragma line 71 "ed25519_ref/src/sha512.c" ::: 1294
#pragma line 95 "ed25519_ref/src/sha512.c" ::: 1296
