#pragma line 1 "ed25519_ref/src/sha512.c" ::: -10
#pragma line 1 "ed25519_ref/src/sha512.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 289 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 427 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "ed25519_ref/src/sha512.c" 2 ::: 184
#pragma line 1 "ed25519_ref/src/fixedint.h" 1 ::: 197
#pragma line 21 "ed25519_ref/src/fixedint.h" ::: 203
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 1 3 ::: 204
#pragma line 1 "/usr/include/limits.h" 1 3 4 ::: 243
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 269
#pragma line 122 "/usr/include/features.h" 3 4 ::: 366
#pragma line 177 "/usr/include/features.h" 3 4 ::: 399
#pragma line 188 "/usr/include/features.h" 3 4 ::: 402
#pragma line 340 "/usr/include/features.h" 3 4 ::: 433
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 437
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 472
#pragma line 343 "/usr/include/features.h" 2 3 4 ::: 481
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 504
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 545
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 551
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 569
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 575
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 579
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 581
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 585
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 595
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 648
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 689
#pragma line 351 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 719
#pragma line 415 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 743
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 744
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 746
#pragma line 416 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 748
#pragma line 365 "/usr/include/features.h" 2 3 4 ::: 749
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 774
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 785
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 790
#pragma line 389 "/usr/include/features.h" 2 3 4 ::: 791
#pragma line 26 "/usr/include/limits.h" 2 3 4 ::: 792
#pragma line 116 "/usr/include/limits.h" 3 4 ::: 803
#pragma line 142 "/usr/include/limits.h" 3 4 ::: 817
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 1 3 4 ::: 820
#pragma line 95 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 3 4 ::: 903
#pragma line 155 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 3 4 ::: 946
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 1 3 4 ::: 953
#pragma line 37 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 3 4 ::: 977
#pragma line 1 "/usr/include/linux/limits.h" 1 3 4 ::: 980
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 2 3 4 ::: 981
#pragma line 161 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 2 3 4 ::: 1042
#pragma line 144 "/usr/include/limits.h" 2 3 4 ::: 1052
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 1 3 4 ::: 1056
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 3 4 ::: 1117
#pragma line 148 "/usr/include/limits.h" 2 3 4 ::: 1119
#pragma line 39 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 2 3 ::: 1120
#pragma line 60 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1125
#pragma line 90 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1127
#pragma line 102 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1129
#pragma line 22 "ed25519_ref/src/fixedint.h" 2 ::: 1134
#pragma line 39 "ed25519_ref/src/fixedint.h" ::: 1142
#pragma line 13 "ed25519_ref/src/sha512.c" 2 ::: 1161
#pragma line 1 "ed25519_ref/src/sha512.h" 1 ::: 1162
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 1166
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 1207
#pragma line 5 "ed25519_ref/src/sha512.h" 2 ::: 1210
#pragma line 1 "ed25519_ref/src/fixedint.h" 1 ::: 1212
#pragma line 7 "ed25519_ref/src/sha512.h" 2 ::: 1218
#pragma line 14 "ed25519_ref/src/sha512.c" 2 ::: 1237
#pragma line 71 "ed25519_ref/src/sha512.c" ::: 1284
#pragma line 95 "ed25519_ref/src/sha512.c" ::: 1286
