#pragma line 1 "ed25519_ref/src/sign.c" ::: -10
#pragma line 1 "ed25519_ref/src/sign.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 289 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 427 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "ed25519_ref/src/sign.c" 2 ::: 184
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 185
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 211
#pragma line 122 "/usr/include/features.h" 3 4 ::: 308
#pragma line 177 "/usr/include/features.h" 3 4 ::: 341
#pragma line 188 "/usr/include/features.h" 3 4 ::: 344
#pragma line 340 "/usr/include/features.h" 3 4 ::: 375
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 379
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 414
#pragma line 343 "/usr/include/features.h" 2 3 4 ::: 423
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 446
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 487
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 493
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 511
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 517
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 521
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 523
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 527
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 537
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 590
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 631
#pragma line 351 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 661
#pragma line 415 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 685
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 686
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 688
#pragma line 416 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 690
#pragma line 365 "/usr/include/features.h" 2 3 4 ::: 691
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 716
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 727
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 732
#pragma line 389 "/usr/include/features.h" 2 3 4 ::: 733
#pragma line 26 "/usr/include/string.h" 2 3 4 ::: 734
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 742
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 783
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 786
#pragma line 92 "/usr/include/string.h" 3 4 ::: 823
#pragma line 124 "/usr/include/string.h" 3 4 ::: 826
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 863
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 906
#pragma line 207 "/usr/include/string.h" 3 4 ::: 928
#pragma line 231 "/usr/include/string.h" 3 4 ::: 930
#pragma line 258 "/usr/include/string.h" 3 4 ::: 935
#pragma line 278 "/usr/include/string.h" 3 4 ::: 938
#pragma line 310 "/usr/include/string.h" 3 4 ::: 948
#pragma line 337 "/usr/include/string.h" 3 4 ::: 953
#pragma line 393 "/usr/include/string.h" 3 4 ::: 974
#pragma line 439 "/usr/include/string.h" 3 4 ::: 1005
#pragma line 484 "/usr/include/string.h" 3 4 ::: 1028
#pragma line 512 "/usr/include/string.h" 3 4 ::: 1034
#pragma line 550 "/usr/include/string.h" 3 4 ::: 1058
#pragma line 2 "ed25519_ref/src/sign.c" 2 ::: 1084
#pragma line 1 "ed25519_ref/src/crypto_sign.h" 1 ::: 1085
#pragma line 3 "ed25519_ref/src/sign.c" 2 ::: 1121
#pragma line 1 "ed25519_ref/src/sha512.h" 1 ::: 1124
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 1128
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 1153
#pragma line 5 "ed25519_ref/src/sha512.h" 2 ::: 1156
#pragma line 1 "ed25519_ref/src/fixedint.h" 1 ::: 1158
#pragma line 21 "ed25519_ref/src/fixedint.h" ::: 1164
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 1 3 ::: 1165
#pragma line 1 "/usr/include/limits.h" 1 3 4 ::: 1204
#pragma line 116 "/usr/include/limits.h" 3 4 ::: 1240
#pragma line 142 "/usr/include/limits.h" 3 4 ::: 1254
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 1 3 4 ::: 1257
#pragma line 95 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 3 4 ::: 1340
#pragma line 155 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 3 4 ::: 1383
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 1 3 4 ::: 1390
#pragma line 37 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 3 4 ::: 1414
#pragma line 1 "/usr/include/linux/limits.h" 1 3 4 ::: 1417
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 2 3 4 ::: 1418
#pragma line 161 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 2 3 4 ::: 1479
#pragma line 144 "/usr/include/limits.h" 2 3 4 ::: 1489
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 1 3 4 ::: 1493
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 3 4 ::: 1554
#pragma line 148 "/usr/include/limits.h" 2 3 4 ::: 1556
#pragma line 39 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 2 3 ::: 1557
#pragma line 60 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1562
#pragma line 90 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1564
#pragma line 102 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1566
#pragma line 22 "ed25519_ref/src/fixedint.h" 2 ::: 1571
#pragma line 39 "ed25519_ref/src/fixedint.h" ::: 1579
#pragma line 7 "ed25519_ref/src/sha512.h" 2 ::: 1598
#pragma line 5 "ed25519_ref/src/sign.c" 2 ::: 1617
#pragma line 1 "ed25519_ref/src/ge25519.h" 1 ::: 1618
#pragma line 1 "ed25519_ref/src/fe25519.h" 1 ::: 1622
#pragma line 1 "ed25519_ref/src/crypto_int32.h" 1 ::: 1626
#pragma line 5 "ed25519_ref/src/fe25519.h" 2 ::: 1631
#pragma line 1 "ed25519_ref/src/crypto_uint32.h" 1 ::: 1632
#pragma line 6 "ed25519_ref/src/fe25519.h" 2 ::: 1637
#pragma line 25 "ed25519_ref/src/fe25519.h" ::: 1638
#pragma line 5 "ed25519_ref/src/ge25519.h" 2 ::: 1676
#pragma line 1 "ed25519_ref/src/sc25519.h" 1 ::: 1677
#pragma line 25 "ed25519_ref/src/sc25519.h" ::: 1678
#pragma line 6 "ed25519_ref/src/ge25519.h" 2 ::: 1726
#pragma line 15 "ed25519_ref/src/ge25519.h" ::: 1727
#pragma line 6 "ed25519_ref/src/sign.c" 2 ::: 1747
