#pragma line 1 "ed25519_ref/src/sign.c" ::: 0
#pragma line 1 "ed25519_ref/src/sign.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 289 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 427 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "ed25519_ref/src/sign.c" 2 ::: 194
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 195
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 221
#pragma line 122 "/usr/include/features.h" 3 4 ::: 318
#pragma line 177 "/usr/include/features.h" 3 4 ::: 351
#pragma line 188 "/usr/include/features.h" 3 4 ::: 354
#pragma line 340 "/usr/include/features.h" 3 4 ::: 385
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 389
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 424
#pragma line 343 "/usr/include/features.h" 2 3 4 ::: 433
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 456
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 497
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 503
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 521
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 527
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 531
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 533
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 537
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 547
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 600
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 641
#pragma line 351 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 671
#pragma line 415 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 695
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 696
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 698
#pragma line 416 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 700
#pragma line 365 "/usr/include/features.h" 2 3 4 ::: 701
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 726
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 737
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 742
#pragma line 389 "/usr/include/features.h" 2 3 4 ::: 743
#pragma line 26 "/usr/include/string.h" 2 3 4 ::: 744
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 752
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 793
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 796
#pragma line 92 "/usr/include/string.h" 3 4 ::: 833
#pragma line 124 "/usr/include/string.h" 3 4 ::: 836
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 873
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 916
#pragma line 207 "/usr/include/string.h" 3 4 ::: 938
#pragma line 231 "/usr/include/string.h" 3 4 ::: 940
#pragma line 258 "/usr/include/string.h" 3 4 ::: 945
#pragma line 278 "/usr/include/string.h" 3 4 ::: 948
#pragma line 310 "/usr/include/string.h" 3 4 ::: 958
#pragma line 337 "/usr/include/string.h" 3 4 ::: 963
#pragma line 393 "/usr/include/string.h" 3 4 ::: 984
#pragma line 439 "/usr/include/string.h" 3 4 ::: 1015
#pragma line 484 "/usr/include/string.h" 3 4 ::: 1038
#pragma line 512 "/usr/include/string.h" 3 4 ::: 1044
#pragma line 550 "/usr/include/string.h" 3 4 ::: 1068
#pragma line 2 "ed25519_ref/src/sign.c" 2 ::: 1094
#pragma line 1 "ed25519_ref/src/crypto_sign.h" 1 ::: 1095
#pragma line 3 "ed25519_ref/src/sign.c" 2 ::: 1131
#pragma line 1 "ed25519_ref/src/sha512.h" 1 ::: 1134
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 1138
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 1163
#pragma line 5 "ed25519_ref/src/sha512.h" 2 ::: 1166
#pragma line 1 "ed25519_ref/src/fixedint.h" 1 ::: 1168
#pragma line 21 "ed25519_ref/src/fixedint.h" ::: 1174
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 1 3 ::: 1175
#pragma line 1 "/usr/include/limits.h" 1 3 4 ::: 1214
#pragma line 116 "/usr/include/limits.h" 3 4 ::: 1250
#pragma line 142 "/usr/include/limits.h" 3 4 ::: 1264
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 1 3 4 ::: 1267
#pragma line 95 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 3 4 ::: 1350
#pragma line 155 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 3 4 ::: 1393
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 1 3 4 ::: 1400
#pragma line 37 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 3 4 ::: 1424
#pragma line 1 "/usr/include/linux/limits.h" 1 3 4 ::: 1427
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 2 3 4 ::: 1428
#pragma line 161 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 2 3 4 ::: 1489
#pragma line 144 "/usr/include/limits.h" 2 3 4 ::: 1499
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 1 3 4 ::: 1503
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 3 4 ::: 1564
#pragma line 148 "/usr/include/limits.h" 2 3 4 ::: 1566
#pragma line 39 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 2 3 ::: 1567
#pragma line 60 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1572
#pragma line 90 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1574
#pragma line 102 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1576
#pragma line 22 "ed25519_ref/src/fixedint.h" 2 ::: 1581
#pragma line 39 "ed25519_ref/src/fixedint.h" ::: 1589
#pragma line 7 "ed25519_ref/src/sha512.h" 2 ::: 1608
#pragma line 5 "ed25519_ref/src/sign.c" 2 ::: 1627
#pragma line 1 "ed25519_ref/src/ge25519.h" 1 ::: 1628
#pragma line 1 "ed25519_ref/src/fe25519.h" 1 ::: 1632
#pragma line 1 "ed25519_ref/src/crypto_int32.h" 1 ::: 1636
#pragma line 5 "ed25519_ref/src/fe25519.h" 2 ::: 1641
#pragma line 1 "ed25519_ref/src/crypto_uint32.h" 1 ::: 1642
#pragma line 6 "ed25519_ref/src/fe25519.h" 2 ::: 1647
#pragma line 25 "ed25519_ref/src/fe25519.h" ::: 1648
#pragma line 5 "ed25519_ref/src/ge25519.h" 2 ::: 1686
#pragma line 1 "ed25519_ref/src/sc25519.h" 1 ::: 1687
#pragma line 25 "ed25519_ref/src/sc25519.h" ::: 1688
#pragma line 6 "ed25519_ref/src/ge25519.h" 2 ::: 1736
#pragma line 15 "ed25519_ref/src/ge25519.h" ::: 1737
#pragma line 6 "ed25519_ref/src/sign.c" 2 ::: 1757
