// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xed25519_sign.h"

extern XEd25519_sign_Config XEd25519_sign_ConfigTable[];

XEd25519_sign_Config *XEd25519_sign_LookupConfig(u16 DeviceId) {
	XEd25519_sign_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XED25519_SIGN_NUM_INSTANCES; Index++) {
		if (XEd25519_sign_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XEd25519_sign_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XEd25519_sign_Initialize(XEd25519_sign *InstancePtr, u16 DeviceId) {
	XEd25519_sign_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XEd25519_sign_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XEd25519_sign_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

