// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sha512_final (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        md_length_i,
        md_length_o,
        md_length_o_ap_vld,
        md_state_address0,
        md_state_ce0,
        md_state_we0,
        md_state_d0,
        md_state_q0,
        md_curlen_i,
        md_curlen_o,
        md_curlen_o_ap_vld,
        md_buf_address0,
        md_buf_ce0,
        md_buf_we0,
        md_buf_d0,
        md_buf_q0,
        md_buf_address1,
        md_buf_ce1,
        md_buf_we1,
        md_buf_d1,
        md_buf_q1,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0
);

parameter    ap_ST_fsm_state1 = 26'd1;
parameter    ap_ST_fsm_state2 = 26'd2;
parameter    ap_ST_fsm_state3 = 26'd4;
parameter    ap_ST_fsm_state4 = 26'd8;
parameter    ap_ST_fsm_state5 = 26'd16;
parameter    ap_ST_fsm_state6 = 26'd32;
parameter    ap_ST_fsm_state7 = 26'd64;
parameter    ap_ST_fsm_state8 = 26'd128;
parameter    ap_ST_fsm_state9 = 26'd256;
parameter    ap_ST_fsm_state10 = 26'd512;
parameter    ap_ST_fsm_state11 = 26'd1024;
parameter    ap_ST_fsm_state12 = 26'd2048;
parameter    ap_ST_fsm_state13 = 26'd4096;
parameter    ap_ST_fsm_state14 = 26'd8192;
parameter    ap_ST_fsm_state15 = 26'd16384;
parameter    ap_ST_fsm_state16 = 26'd32768;
parameter    ap_ST_fsm_state17 = 26'd65536;
parameter    ap_ST_fsm_state18 = 26'd131072;
parameter    ap_ST_fsm_state19 = 26'd262144;
parameter    ap_ST_fsm_state20 = 26'd524288;
parameter    ap_ST_fsm_state21 = 26'd1048576;
parameter    ap_ST_fsm_state22 = 26'd2097152;
parameter    ap_ST_fsm_state23 = 26'd4194304;
parameter    ap_ST_fsm_state24 = 26'd8388608;
parameter    ap_ST_fsm_state25 = 26'd16777216;
parameter    ap_ST_fsm_state26 = 26'd33554432;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] md_length_i;
output  [63:0] md_length_o;
output   md_length_o_ap_vld;
output  [2:0] md_state_address0;
output   md_state_ce0;
output   md_state_we0;
output  [63:0] md_state_d0;
input  [63:0] md_state_q0;
input  [63:0] md_curlen_i;
output  [63:0] md_curlen_o;
output   md_curlen_o_ap_vld;
output  [6:0] md_buf_address0;
output   md_buf_ce0;
output   md_buf_we0;
output  [7:0] md_buf_d0;
input  [7:0] md_buf_q0;
output  [6:0] md_buf_address1;
output   md_buf_ce1;
output   md_buf_we1;
output  [7:0] md_buf_d1;
input  [7:0] md_buf_q1;
output  [5:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [7:0] out_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[63:0] md_length_o;
reg md_length_o_ap_vld;
reg[2:0] md_state_address0;
reg md_state_ce0;
reg md_state_we0;
reg[63:0] md_curlen_o;
reg md_curlen_o_ap_vld;
reg[6:0] md_buf_address0;
reg md_buf_ce0;
reg md_buf_we0;
reg[7:0] md_buf_d0;
reg[6:0] md_buf_address1;
reg md_buf_ce1;
reg md_buf_we1;
reg[7:0] md_buf_d1;
reg[5:0] out_r_address0;
reg out_r_ce0;
reg out_r_we0;
reg[7:0] out_r_d0;

(* fsm_encoding = "none" *) reg   [25:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_fu_487_p2;
reg   [0:0] icmp_reg_899;
wire   [0:0] tmp_24_fu_527_p2;
reg   [0:0] tmp_24_reg_903;
wire    ap_CS_fsm_state2;
wire   [7:0] temp_index_6_fu_562_p2;
reg   [7:0] temp_index_6_reg_913;
wire    ap_CS_fsm_state4;
wire   [63:0] tmp_26_fu_568_p1;
reg   [63:0] tmp_26_reg_918;
wire   [0:0] exitcond1_fu_556_p2;
wire   [7:0] temp_index_7_fu_579_p2;
reg   [7:0] temp_index_7_reg_931;
wire    ap_CS_fsm_state7;
wire   [63:0] tmp_27_fu_585_p1;
reg   [63:0] tmp_27_reg_936;
wire   [0:0] exitcond2_fu_573_p2;
reg   [7:0] tmp_32_reg_949;
wire    ap_CS_fsm_state9;
wire   [0:0] tmp_28_fu_594_p2;
reg   [7:0] tmp_33_reg_954;
reg   [7:0] tmp_34_reg_959;
reg   [7:0] tmp_35_reg_964;
reg   [7:0] tmp_36_reg_969;
wire   [7:0] tmp_56_fu_683_p1;
reg   [7:0] tmp_56_reg_974;
wire   [7:0] temp_index_8_fu_693_p2;
reg   [7:0] temp_index_8_reg_982;
wire    ap_CS_fsm_state13;
wire   [63:0] tmp_37_fu_699_p1;
reg   [63:0] tmp_37_reg_987;
wire   [0:0] exitcond9_fu_687_p2;
wire   [7:0] temp_index_9_fu_710_p2;
reg   [7:0] temp_index_9_reg_1000;
wire    ap_CS_fsm_state16;
wire   [63:0] tmp_38_fu_716_p1;
reg   [63:0] tmp_38_reg_1005;
wire   [0:0] exitcond8_fu_704_p2;
wire   [3:0] i_3_fu_727_p2;
reg   [3:0] i_3_reg_1018;
wire    ap_CS_fsm_state18;
wire   [0:0] exitcond_fu_721_p2;
wire   [2:0] tmp_57_fu_738_p1;
reg   [2:0] tmp_57_reg_1028;
wire   [5:0] tmp_42_fu_753_p3;
reg   [5:0] tmp_42_reg_1033;
wire    ap_CS_fsm_state19;
reg   [7:0] tmp_44_reg_1044;
reg   [7:0] tmp_45_reg_1049;
reg   [7:0] tmp_46_reg_1054;
reg   [7:0] tmp_47_reg_1059;
reg   [7:0] tmp_48_reg_1064;
reg   [7:0] tmp_49_reg_1069;
wire   [7:0] tmp_58_fu_825_p1;
reg   [7:0] tmp_58_reg_1074;
reg   [6:0] temp_buf_address0;
reg    temp_buf_ce0;
reg    temp_buf_we0;
reg   [7:0] temp_buf_d0;
wire   [7:0] temp_buf_q0;
reg    temp_buf_ce1;
wire   [7:0] temp_buf_q1;
wire    grp_sha512_compress_128_fu_468_ap_start;
wire    grp_sha512_compress_128_fu_468_ap_done;
wire    grp_sha512_compress_128_fu_468_ap_idle;
wire    grp_sha512_compress_128_fu_468_ap_ready;
wire   [2:0] grp_sha512_compress_128_fu_468_md_state_address0;
wire    grp_sha512_compress_128_fu_468_md_state_ce0;
wire    grp_sha512_compress_128_fu_468_md_state_we0;
wire   [63:0] grp_sha512_compress_128_fu_468_md_state_d0;
wire   [6:0] grp_sha512_compress_128_fu_468_buf_r_address0;
wire    grp_sha512_compress_128_fu_468_buf_r_ce0;
wire   [6:0] grp_sha512_compress_128_fu_468_buf_r_address1;
wire    grp_sha512_compress_128_fu_468_buf_r_ce1;
reg   [7:0] temp_index_reg_413;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state3;
wire   [0:0] tmp_54_fu_537_p3;
reg   [7:0] temp_index_1_reg_424;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state8;
reg   [7:0] temp_index_2_reg_435;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state14;
reg   [7:0] temp_index_3_reg_446;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state17;
reg   [3:0] i_reg_457;
wire    ap_CS_fsm_state26;
reg    ap_reg_grp_sha512_compress_128_fu_468_ap_start;
wire   [6:0] md_buf_addr_9_gep_fu_171_p3;
wire   [6:0] md_buf_addr_12_gep_fu_217_p3;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire   [63:0] tmp_40_fu_733_p1;
wire   [63:0] tmp_43_fu_760_p1;
wire   [63:0] p_sum1_cast_fu_834_p1;
wire    ap_CS_fsm_state20;
wire   [63:0] p_sum2_cast_fu_844_p1;
wire    ap_CS_fsm_state21;
wire   [63:0] p_sum3_cast_fu_854_p1;
wire    ap_CS_fsm_state22;
wire   [63:0] p_sum4_cast_fu_864_p1;
wire    ap_CS_fsm_state23;
wire   [63:0] p_sum5_cast_fu_874_p1;
wire    ap_CS_fsm_state24;
wire   [63:0] p_sum6_cast_fu_884_p1;
wire    ap_CS_fsm_state25;
wire   [63:0] p_sum7_cast_fu_894_p1;
wire   [63:0] tmp_22_fu_509_p2;
wire   [63:0] tmp_23_fu_516_p2;
wire   [63:0] tmp_27_cast_fu_551_p1;
wire   [63:0] tmp_31_cast_fu_606_p1;
wire   [56:0] tmp_fu_477_p4;
wire   [6:0] tmp_39_fu_493_p1;
wire   [9:0] tmp_s_fu_497_p3;
wire   [63:0] tmp_cast_fu_505_p1;
wire   [7:0] tmp_52_fu_523_p1;
wire   [7:0] tmp_53_fu_533_p1;
wire   [7:0] tmp_25_fu_545_p2;
wire   [7:0] tmp_55_fu_590_p1;
wire   [7:0] tmp_29_fu_600_p2;
wire   [5:0] p_sum1_fu_829_p2;
wire   [5:0] p_sum2_fu_839_p2;
wire   [5:0] p_sum3_fu_849_p2;
wire   [5:0] p_sum4_fu_859_p2;
wire   [5:0] p_sum5_fu_869_p2;
wire   [5:0] p_sum6_fu_879_p2;
wire   [5:0] p_sum7_fu_889_p2;
reg   [25:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 26'd1;
#0 ap_reg_grp_sha512_compress_128_fu_468_ap_start = 1'b0;
end

sha512_update_32_hbi #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
temp_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_buf_address0),
    .ce0(temp_buf_ce0),
    .we0(temp_buf_we0),
    .d0(temp_buf_d0),
    .q0(temp_buf_q0),
    .address1(grp_sha512_compress_128_fu_468_buf_r_address1),
    .ce1(temp_buf_ce1),
    .q1(temp_buf_q1)
);

sha512_compress_128 grp_sha512_compress_128_fu_468(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sha512_compress_128_fu_468_ap_start),
    .ap_done(grp_sha512_compress_128_fu_468_ap_done),
    .ap_idle(grp_sha512_compress_128_fu_468_ap_idle),
    .ap_ready(grp_sha512_compress_128_fu_468_ap_ready),
    .md_state_address0(grp_sha512_compress_128_fu_468_md_state_address0),
    .md_state_ce0(grp_sha512_compress_128_fu_468_md_state_ce0),
    .md_state_we0(grp_sha512_compress_128_fu_468_md_state_we0),
    .md_state_d0(grp_sha512_compress_128_fu_468_md_state_d0),
    .md_state_q0(md_state_q0),
    .buf_r_address0(grp_sha512_compress_128_fu_468_buf_r_address0),
    .buf_r_ce0(grp_sha512_compress_128_fu_468_buf_r_ce0),
    .buf_r_q0(temp_buf_q0),
    .buf_r_address1(grp_sha512_compress_128_fu_468_buf_r_address1),
    .buf_r_ce1(grp_sha512_compress_128_fu_468_buf_r_ce1),
    .buf_r_q1(temp_buf_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_sha512_compress_128_fu_468_ap_start <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_state4) & (exitcond1_fu_556_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state13) & (1'd1 == exitcond9_fu_687_p2)))) begin
            ap_reg_grp_sha512_compress_128_fu_468_ap_start <= 1'b1;
        end else if ((1'b1 == grp_sha512_compress_128_fu_468_ap_ready)) begin
            ap_reg_grp_sha512_compress_128_fu_468_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) & (1'd1 == exitcond8_fu_704_p2))) begin
        i_reg_457 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        i_reg_457 <= i_3_reg_1018;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        temp_index_1_reg_424 <= temp_index_7_reg_931;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_sha512_compress_128_fu_468_ap_done == 1'b1))) begin
        temp_index_1_reg_424 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        temp_index_2_reg_435 <= temp_index_8_reg_982;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_index_2_reg_435 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        temp_index_3_reg_446 <= temp_index_9_reg_1000;
    end else if (((grp_sha512_compress_128_fu_468_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        temp_index_3_reg_446 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'd1 == tmp_54_fu_537_p3))) begin
        temp_index_reg_413 <= 8'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        temp_index_reg_413 <= temp_index_6_reg_913;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state18) & (icmp_reg_899 == 1'd1))) begin
        i_3_reg_1018 <= i_3_fu_727_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        icmp_reg_899 <= icmp_fu_487_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        temp_index_6_reg_913 <= temp_index_6_fu_562_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (tmp_24_reg_903 == 1'd1))) begin
        temp_index_7_reg_931 <= temp_index_7_fu_579_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        temp_index_8_reg_982 <= temp_index_8_fu_693_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        temp_index_9_reg_1000 <= temp_index_9_fu_710_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_24_reg_903 <= tmp_24_fu_527_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (exitcond1_fu_556_p2 == 1'd0))) begin
        tmp_26_reg_918[7 : 0] <= tmp_26_fu_568_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (tmp_24_reg_903 == 1'd1) & (1'd0 == exitcond2_fu_573_p2))) begin
        tmp_27_reg_936[7 : 0] <= tmp_27_fu_585_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (1'd0 == tmp_28_fu_594_p2))) begin
        tmp_32_reg_949 <= {{md_length_i[47:40]}};
        tmp_33_reg_954 <= {{md_length_i[39:32]}};
        tmp_34_reg_959 <= {{md_length_i[31:24]}};
        tmp_35_reg_964 <= {{md_length_i[23:16]}};
        tmp_36_reg_969 <= {{md_length_i[15:8]}};
        tmp_56_reg_974 <= tmp_56_fu_683_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) & (1'd0 == exitcond9_fu_687_p2))) begin
        tmp_37_reg_987[7 : 0] <= tmp_37_fu_699_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) & (1'd0 == exitcond8_fu_704_p2))) begin
        tmp_38_reg_1005[7 : 0] <= tmp_38_fu_716_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        tmp_42_reg_1033[5 : 3] <= tmp_42_fu_753_p3[5 : 3];
        tmp_44_reg_1044 <= {{md_state_q0[55:48]}};
        tmp_45_reg_1049 <= {{md_state_q0[47:40]}};
        tmp_46_reg_1054 <= {{md_state_q0[39:32]}};
        tmp_47_reg_1059 <= {{md_state_q0[31:24]}};
        tmp_48_reg_1064 <= {{md_state_q0[23:16]}};
        tmp_49_reg_1069 <= {{md_state_q0[15:8]}};
        tmp_58_reg_1074 <= tmp_58_fu_825_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state18) & (icmp_reg_899 == 1'd1) & (1'd0 == exitcond_fu_721_p2))) begin
        tmp_57_reg_1028 <= tmp_57_fu_738_p1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state18) & ((icmp_reg_899 == 1'd0) | (1'd1 == exitcond_fu_721_p2))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) & ((icmp_reg_899 == 1'd0) | (1'd1 == exitcond_fu_721_p2)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        md_buf_address0 = 64'd127;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        md_buf_address0 = 64'd125;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        md_buf_address0 = 64'd123;
    end else if (((1'b1 == ap_CS_fsm_state9) & (1'd0 == tmp_28_fu_594_p2))) begin
        md_buf_address0 = 64'd120;
    end else if (((1'b1 == ap_CS_fsm_state9) & (1'd1 == tmp_28_fu_594_p2))) begin
        md_buf_address0 = md_buf_addr_12_gep_fu_217_p3;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        md_buf_address0 = tmp_27_reg_936;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        md_buf_address0 = tmp_26_fu_568_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        md_buf_address0 = md_buf_addr_9_gep_fu_171_p3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        md_buf_address0 = md_curlen_i;
    end else begin
        md_buf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        md_buf_address1 = tmp_38_reg_1005;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        md_buf_address1 = tmp_37_fu_699_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        md_buf_address1 = 64'd126;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        md_buf_address1 = 64'd124;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        md_buf_address1 = 64'd122;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        md_buf_address1 = 64'd121;
    end else begin
        md_buf_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | (1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state9) & (1'd0 == tmp_28_fu_594_p2)) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state9) & (1'd1 == tmp_28_fu_594_p2)) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state11))) begin
        md_buf_ce0 = 1'b1;
    end else begin
        md_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state11))) begin
        md_buf_ce1 = 1'b1;
    end else begin
        md_buf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        md_buf_d0 = tmp_56_reg_974;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        md_buf_d0 = tmp_35_reg_964;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        md_buf_d0 = tmp_33_reg_954;
    end else if (((1'b1 == ap_CS_fsm_state9) & (1'd0 == tmp_28_fu_594_p2))) begin
        md_buf_d0 = {{md_length_i[63:56]}};
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        md_buf_d0 = temp_buf_q0;
    end else if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state9) & (1'd1 == tmp_28_fu_594_p2)))) begin
        md_buf_d0 = 8'd0;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        md_buf_d0 = 8'd128;
    end else begin
        md_buf_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        md_buf_d1 = temp_buf_q0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        md_buf_d1 = tmp_36_reg_969;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        md_buf_d1 = tmp_34_reg_959;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        md_buf_d1 = tmp_32_reg_949;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        md_buf_d1 = {{md_length_i[55:48]}};
    end else begin
        md_buf_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state9) & (1'd0 == tmp_28_fu_594_p2)) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state3) & (1'd0 == tmp_54_fu_537_p3)) | ((1'b1 == ap_CS_fsm_state9) & (1'd1 == tmp_28_fu_594_p2)) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state11) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (icmp_fu_487_p2 == 1'd1)))) begin
        md_buf_we0 = 1'b1;
    end else begin
        md_buf_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state9) & (1'd0 == tmp_28_fu_594_p2)) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state11))) begin
        md_buf_we1 = 1'b1;
    end else begin
        md_buf_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (1'd1 == tmp_28_fu_594_p2))) begin
        md_curlen_o = tmp_31_cast_fu_606_p1;
    end else if (((1'b1 == ap_CS_fsm_state7) & (tmp_24_reg_903 == 1'd1) & (1'd1 == exitcond2_fu_573_p2))) begin
        md_curlen_o = 64'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (1'd0 == tmp_54_fu_537_p3))) begin
        md_curlen_o = tmp_27_cast_fu_551_p1;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (icmp_fu_487_p2 == 1'd1))) begin
        md_curlen_o = tmp_23_fu_516_p2;
    end else begin
        md_curlen_o = md_curlen_i;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state3) & (1'd0 == tmp_54_fu_537_p3)) | ((1'b1 == ap_CS_fsm_state9) & (1'd1 == tmp_28_fu_594_p2)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (icmp_fu_487_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state7) & (tmp_24_reg_903 == 1'd1) & (1'd1 == exitcond2_fu_573_p2)))) begin
        md_curlen_o_ap_vld = 1'b1;
    end else begin
        md_curlen_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (icmp_fu_487_p2 == 1'd1))) begin
        md_length_o = tmp_22_fu_509_p2;
    end else begin
        md_length_o = md_length_i;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (icmp_fu_487_p2 == 1'd1))) begin
        md_length_o_ap_vld = 1'b1;
    end else begin
        md_length_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        md_state_address0 = tmp_40_fu_733_p1;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state15))) begin
        md_state_address0 = grp_sha512_compress_128_fu_468_md_state_address0;
    end else begin
        md_state_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        md_state_ce0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state15))) begin
        md_state_ce0 = grp_sha512_compress_128_fu_468_md_state_ce0;
    end else begin
        md_state_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state15))) begin
        md_state_we0 = grp_sha512_compress_128_fu_468_md_state_we0;
    end else begin
        md_state_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        out_r_address0 = p_sum7_cast_fu_894_p1;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        out_r_address0 = p_sum6_cast_fu_884_p1;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        out_r_address0 = p_sum5_cast_fu_874_p1;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        out_r_address0 = p_sum4_cast_fu_864_p1;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        out_r_address0 = p_sum3_cast_fu_854_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        out_r_address0 = p_sum2_cast_fu_844_p1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        out_r_address0 = p_sum1_cast_fu_834_p1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        out_r_address0 = tmp_43_fu_760_p1;
    end else begin
        out_r_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state25))) begin
        out_r_ce0 = 1'b1;
    end else begin
        out_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        out_r_d0 = tmp_58_reg_1074;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        out_r_d0 = tmp_49_reg_1069;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        out_r_d0 = tmp_48_reg_1064;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        out_r_d0 = tmp_47_reg_1059;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        out_r_d0 = tmp_46_reg_1054;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        out_r_d0 = tmp_45_reg_1049;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        out_r_d0 = tmp_44_reg_1044;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        out_r_d0 = {{md_state_q0[63:56]}};
    end else begin
        out_r_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state25))) begin
        out_r_we0 = 1'b1;
    end else begin
        out_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        temp_buf_address0 = tmp_38_fu_716_p1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        temp_buf_address0 = tmp_37_reg_987;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        temp_buf_address0 = tmp_27_fu_585_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        temp_buf_address0 = tmp_26_reg_918;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state15))) begin
        temp_buf_address0 = grp_sha512_compress_128_fu_468_buf_r_address0;
    end else begin
        temp_buf_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state14))) begin
        temp_buf_ce0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state15))) begin
        temp_buf_ce0 = grp_sha512_compress_128_fu_468_buf_r_ce0;
    end else begin
        temp_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state15))) begin
        temp_buf_ce1 = grp_sha512_compress_128_fu_468_buf_r_ce1;
    end else begin
        temp_buf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        temp_buf_d0 = md_buf_q1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        temp_buf_d0 = md_buf_q0;
    end else begin
        temp_buf_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state14))) begin
        temp_buf_we0 = 1'b1;
    end else begin
        temp_buf_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (icmp_fu_487_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (icmp_fu_487_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (tmp_24_fu_527_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (1'd1 == tmp_54_fu_537_p3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (exitcond1_fu_556_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_sha512_compress_128_fu_468_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & ((1'd1 == exitcond2_fu_573_p2) | (tmp_24_reg_903 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (1'd1 == tmp_28_fu_594_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (1'd1 == exitcond9_fu_687_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_sha512_compress_128_fu_468_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((1'b1 == ap_CS_fsm_state16) & (1'd1 == exitcond8_fu_704_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state18 : begin
            if (((1'b1 == ap_CS_fsm_state18) & ((icmp_reg_899 == 1'd0) | (1'd1 == exitcond_fu_721_p2)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign exitcond1_fu_556_p2 = ((temp_index_reg_413 == 8'd128) ? 1'b1 : 1'b0);

assign exitcond2_fu_573_p2 = ((temp_index_1_reg_424 == 8'd128) ? 1'b1 : 1'b0);

assign exitcond8_fu_704_p2 = ((temp_index_3_reg_446 == 8'd128) ? 1'b1 : 1'b0);

assign exitcond9_fu_687_p2 = ((temp_index_2_reg_435 == 8'd128) ? 1'b1 : 1'b0);

assign exitcond_fu_721_p2 = ((i_reg_457 == 4'd8) ? 1'b1 : 1'b0);

assign grp_sha512_compress_128_fu_468_ap_start = ap_reg_grp_sha512_compress_128_fu_468_ap_start;

assign i_3_fu_727_p2 = (i_reg_457 + 4'd1);

assign icmp_fu_487_p2 = ((tmp_fu_477_p4 == 57'd0) ? 1'b1 : 1'b0);

assign md_buf_addr_12_gep_fu_217_p3 = md_curlen_i;

assign md_buf_addr_9_gep_fu_171_p3 = md_curlen_i;

assign md_state_d0 = grp_sha512_compress_128_fu_468_md_state_d0;

assign p_sum1_cast_fu_834_p1 = p_sum1_fu_829_p2;

assign p_sum1_fu_829_p2 = (tmp_42_reg_1033 | 6'd1);

assign p_sum2_cast_fu_844_p1 = p_sum2_fu_839_p2;

assign p_sum2_fu_839_p2 = (tmp_42_reg_1033 | 6'd2);

assign p_sum3_cast_fu_854_p1 = p_sum3_fu_849_p2;

assign p_sum3_fu_849_p2 = (tmp_42_reg_1033 | 6'd3);

assign p_sum4_cast_fu_864_p1 = p_sum4_fu_859_p2;

assign p_sum4_fu_859_p2 = (tmp_42_reg_1033 | 6'd4);

assign p_sum5_cast_fu_874_p1 = p_sum5_fu_869_p2;

assign p_sum5_fu_869_p2 = (tmp_42_reg_1033 | 6'd5);

assign p_sum6_cast_fu_884_p1 = p_sum6_fu_879_p2;

assign p_sum6_fu_879_p2 = (tmp_42_reg_1033 | 6'd6);

assign p_sum7_cast_fu_894_p1 = p_sum7_fu_889_p2;

assign p_sum7_fu_889_p2 = (tmp_42_reg_1033 | 6'd7);

assign temp_index_6_fu_562_p2 = (temp_index_reg_413 + 8'd1);

assign temp_index_7_fu_579_p2 = (temp_index_1_reg_424 + 8'd1);

assign temp_index_8_fu_693_p2 = (temp_index_2_reg_435 + 8'd1);

assign temp_index_9_fu_710_p2 = (temp_index_3_reg_446 + 8'd1);

assign tmp_22_fu_509_p2 = (md_length_i + tmp_cast_fu_505_p1);

assign tmp_23_fu_516_p2 = (64'd1 + md_curlen_i);

assign tmp_24_fu_527_p2 = ((tmp_52_fu_523_p1 > 8'd112) ? 1'b1 : 1'b0);

assign tmp_25_fu_545_p2 = (tmp_53_fu_533_p1 + 8'd1);

assign tmp_26_fu_568_p1 = temp_index_reg_413;

assign tmp_27_cast_fu_551_p1 = tmp_25_fu_545_p2;

assign tmp_27_fu_585_p1 = temp_index_1_reg_424;

assign tmp_28_fu_594_p2 = ((tmp_55_fu_590_p1 < 8'd120) ? 1'b1 : 1'b0);

assign tmp_29_fu_600_p2 = (tmp_55_fu_590_p1 + 8'd1);

assign tmp_31_cast_fu_606_p1 = tmp_29_fu_600_p2;

assign tmp_37_fu_699_p1 = temp_index_2_reg_435;

assign tmp_38_fu_716_p1 = temp_index_3_reg_446;

assign tmp_39_fu_493_p1 = md_curlen_i[6:0];

assign tmp_40_fu_733_p1 = i_reg_457;

assign tmp_42_fu_753_p3 = {{tmp_57_reg_1028}, {3'd0}};

assign tmp_43_fu_760_p1 = tmp_42_fu_753_p3;

assign tmp_52_fu_523_p1 = md_curlen_i[7:0];

assign tmp_53_fu_533_p1 = md_curlen_i[7:0];

assign tmp_54_fu_537_p3 = md_curlen_i[32'd7];

assign tmp_55_fu_590_p1 = md_curlen_i[7:0];

assign tmp_56_fu_683_p1 = md_length_i[7:0];

assign tmp_57_fu_738_p1 = i_reg_457[2:0];

assign tmp_58_fu_825_p1 = md_state_q0[7:0];

assign tmp_cast_fu_505_p1 = tmp_s_fu_497_p3;

assign tmp_fu_477_p4 = {{md_curlen_i[63:7]}};

assign tmp_s_fu_497_p3 = {{tmp_39_fu_493_p1}, {3'd0}};

always @ (posedge ap_clk) begin
    tmp_26_reg_918[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    tmp_27_reg_936[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    tmp_37_reg_987[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    tmp_38_reg_1005[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    tmp_42_reg_1033[2:0] <= 3'b000;
end

endmodule //sha512_final
