CC={{ cross_compile }}gcc
THRIFT_GEN_DIR=../gen-cpp
CPP_LIBS=-lstdc++ -lc
CFLAGS=-I. -I../user_mmap_driver/ -I/usr/local/include/thrift/ -I/usr/local/include/thrift/cpp -I$(THRIFT_GEN_DIR) {{ include_dirs }}
LDFLAGS=-L/usr/local/lib/ {{ lib_dirs }} -lthrift -lpthread {{ libs }}
SOURCES=$(wildcard $(THRIFT_GEN_DIR)/*.cpp) arm_code.c enclave_library.cpp ../user_mmap_driver/user_mmap_driver.c $(wildcard *.c)
EXECUTABLE={{ program_name }}

all: $(EXECUTABLE)

$(EXECUTABLE): $(SOURCES)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS) $(CPP_LIBS)

clean:
	rm -f {{ program_name }}
