CC=gcc
CPP_LIBS=-lstdc++ -lc
CFLAGS=-I. -I../user_mmap_driver/ -I/usr/local/include/thrift/ -I/usr/local/include/thrift/cpp {{ include_dirs }}
LDFLAGS=-L/usr/local/lib/ {{ lib_dirs } -lthrift {{ libs }}
THRIFT_GEN_DIR=../gen-cpp
SOURCES=$(wildcard $(THRIFT_GEN_DIR)/*.cpp) arm_code.c ../user_mmap_driver/user_mmap_driver.c $(wildcard *.c)
OUTDIR=.
EXECUTABLE={{ program_name }}

all: $(EXECUTABLE)

$(EXECUTABLE): $(SOURCES)
	$(CC) $(CFLAGS) -o $(OUTDIR)/$@ $^ $(LDFLAGS) $(CPP_LIBS)

clean:
	rm -f $(OURDIR)/{{ program_name }}
