#pragma line 1 "ed25519/src/add_scalar.cpp" ::: 0
#pragma line 1 "ed25519/src/add_scalar.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 155 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 11
#pragma line 145 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 64
#pragma line 156 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 67
#pragma line 413 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 197
#pragma line 427 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 200
#pragma line 7 "<command line>" 2 ::: 202
#pragma line 1 "<built-in>" 2 ::: 203
#pragma line 1 "ed25519/src/add_scalar.cpp" 2 ::: 204
#pragma line 1 "ed25519/src/ed25519.h" 1 ::: 205
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 209
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 245
#pragma line 5 "ed25519/src/ed25519.h" 2 ::: 248
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/hls_stream.h" 1 ::: 249
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_enum.h" 1 ::: 316
#pragma line 67 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/hls_stream.h" 2 ::: 451
#pragma line 6 "ed25519/src/ed25519.h" 2 ::: 557
#pragma line 27 "ed25519/src/ed25519.h" ::: 564
#pragma line 2 "ed25519/src/add_scalar.cpp" 2 ::: 581
#pragma line 1 "ed25519/src/ge.h" 1 ::: 582
#pragma line 1 "ed25519/src/fe.h" 1 ::: 586
#pragma line 1 "ed25519/src/fixedint.h" 1 ::: 590
#pragma line 21 "ed25519/src/fixedint.h" ::: 596
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 1 3 ::: 597
#pragma line 1 "/usr/include/limits.h" 1 3 4 ::: 636
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 662
#pragma line 122 "/usr/include/features.h" 3 4 ::: 759
#pragma line 177 "/usr/include/features.h" 3 4 ::: 792
#pragma line 188 "/usr/include/features.h" 3 4 ::: 795
#pragma line 340 "/usr/include/features.h" 3 4 ::: 826
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 830
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 865
#pragma line 343 "/usr/include/features.h" 2 3 4 ::: 874
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 897
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 938
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 944
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 962
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 968
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 972
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 974
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 978
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 988
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 1041
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 1082
#pragma line 351 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 1112
#pragma line 415 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 1136
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1137
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1139
#pragma line 416 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 1141
#pragma line 365 "/usr/include/features.h" 2 3 4 ::: 1142
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 1167
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 1178
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 1183
#pragma line 389 "/usr/include/features.h" 2 3 4 ::: 1184
#pragma line 26 "/usr/include/limits.h" 2 3 4 ::: 1185
#pragma line 116 "/usr/include/limits.h" 3 4 ::: 1196
#pragma line 142 "/usr/include/limits.h" 3 4 ::: 1210
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 1 3 4 ::: 1213
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 1 3 4 ::: 1374
#pragma line 37 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 3 4 ::: 1398
#pragma line 1 "/usr/include/linux/limits.h" 1 3 4 ::: 1401
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 2 3 4 ::: 1402
#pragma line 161 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 2 3 4 ::: 1463
#pragma line 144 "/usr/include/limits.h" 2 3 4 ::: 1473
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 1 3 4 ::: 1477
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 3 4 ::: 1538
#pragma line 148 "/usr/include/limits.h" 2 3 4 ::: 1540
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 1 3 4 ::: 1544
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1578
#pragma line 34 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 2 3 4 ::: 1595
#pragma line 121 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 3 4 ::: 1657
#pragma line 133 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 3 4 ::: 1659
#pragma line 152 "/usr/include/limits.h" 2 3 4 ::: 1661
#pragma line 39 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 2 3 ::: 1662
#pragma line 60 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1667
#pragma line 90 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1669
#pragma line 102 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1671
#pragma line 22 "ed25519/src/fixedint.h" 2 ::: 1676
#pragma line 39 "ed25519/src/fixedint.h" ::: 1684
#pragma line 5 "ed25519/src/fe.h" 2 ::: 1703
#pragma line 5 "ed25519/src/ge.h" 2 ::: 1739
#pragma line 3 "ed25519/src/add_scalar.cpp" 2 ::: 1808
#pragma line 1 "ed25519/src/sc.h" 1 ::: 1809
#pragma line 4 "ed25519/src/add_scalar.cpp" 2 ::: 1820
#pragma line 1 "ed25519/src/sha512.h" 1 ::: 1821
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 1825
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 1850
#pragma line 5 "ed25519/src/sha512.h" 2 ::: 1853
#pragma line 1 "ed25519/src/fixedint.h" 1 ::: 1855
#pragma line 7 "ed25519/src/sha512.h" 2 ::: 1861
#pragma line 5 "ed25519/src/add_scalar.cpp" 2 ::: 1879
