#pragma line 1 "ed25519/src/ge.cpp" ::: 0
#pragma line 1 "ed25519/src/ge.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 155 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 11
#pragma line 145 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 64
#pragma line 156 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 67
#pragma line 413 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 197
#pragma line 427 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 200
#pragma line 7 "<command line>" 2 ::: 202
#pragma line 1 "<built-in>" 2 ::: 203
#pragma line 1 "ed25519/src/ge.cpp" 2 ::: 204
#pragma line 1 "ed25519/src/ge.h" 1 ::: 205
#pragma line 1 "ed25519/src/fe.h" 1 ::: 209
#pragma line 1 "ed25519/src/fixedint.h" 1 ::: 213
#pragma line 21 "ed25519/src/fixedint.h" ::: 219
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 1 3 ::: 220
#pragma line 1 "/usr/include/limits.h" 1 3 4 ::: 259
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 285
#pragma line 122 "/usr/include/features.h" 3 4 ::: 382
#pragma line 177 "/usr/include/features.h" 3 4 ::: 415
#pragma line 188 "/usr/include/features.h" 3 4 ::: 418
#pragma line 340 "/usr/include/features.h" 3 4 ::: 449
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 453
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 488
#pragma line 343 "/usr/include/features.h" 2 3 4 ::: 497
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 520
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 561
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 567
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 585
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 591
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 595
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 597
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 601
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 611
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 664
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 705
#pragma line 351 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 735
#pragma line 415 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 759
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 760
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 762
#pragma line 416 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 764
#pragma line 365 "/usr/include/features.h" 2 3 4 ::: 765
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 790
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 801
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 806
#pragma line 389 "/usr/include/features.h" 2 3 4 ::: 807
#pragma line 26 "/usr/include/limits.h" 2 3 4 ::: 808
#pragma line 116 "/usr/include/limits.h" 3 4 ::: 819
#pragma line 142 "/usr/include/limits.h" 3 4 ::: 833
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 1 3 4 ::: 836
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 1 3 4 ::: 997
#pragma line 37 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 3 4 ::: 1021
#pragma line 1 "/usr/include/linux/limits.h" 1 3 4 ::: 1024
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 2 3 4 ::: 1025
#pragma line 161 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 2 3 4 ::: 1086
#pragma line 144 "/usr/include/limits.h" 2 3 4 ::: 1096
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 1 3 4 ::: 1100
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 3 4 ::: 1161
#pragma line 148 "/usr/include/limits.h" 2 3 4 ::: 1163
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 1 3 4 ::: 1167
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1201
#pragma line 34 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 2 3 4 ::: 1218
#pragma line 121 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 3 4 ::: 1280
#pragma line 133 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 3 4 ::: 1282
#pragma line 152 "/usr/include/limits.h" 2 3 4 ::: 1284
#pragma line 39 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 2 3 ::: 1285
#pragma line 60 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1290
#pragma line 90 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1292
#pragma line 102 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1294
#pragma line 22 "ed25519/src/fixedint.h" 2 ::: 1299
#pragma line 39 "ed25519/src/fixedint.h" ::: 1307
#pragma line 5 "ed25519/src/fe.h" 2 ::: 1326
#pragma line 5 "ed25519/src/ge.h" 2 ::: 1362
#pragma line 2 "ed25519/src/ge.cpp" 2 ::: 1431
#pragma line 1 "ed25519/src/precomp_data.h" 1 ::: 1432
#pragma line 3 "ed25519/src/ge.cpp" 2 ::: 2824
