#pragma line 1 "ed25519/src/key_exchange.cpp" ::: -10
#pragma line 1 "ed25519/src/key_exchange.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 155 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 1
#pragma line 145 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 54
#pragma line 156 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 57
#pragma line 413 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 187
#pragma line 427 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 7 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "ed25519/src/key_exchange.cpp" 2 ::: 194
#pragma line 1 "ed25519/src/ed25519.h" 1 ::: 195
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 199
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 235
#pragma line 5 "ed25519/src/ed25519.h" 2 ::: 238
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/hls_stream.h" 1 ::: 239
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_enum.h" 1 ::: 306
#pragma line 67 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/hls_stream.h" 2 ::: 441
#pragma line 6 "ed25519/src/ed25519.h" 2 ::: 547
#pragma line 27 "ed25519/src/ed25519.h" ::: 554
#pragma line 2 "ed25519/src/key_exchange.cpp" 2 ::: 571
#pragma line 1 "ed25519/src/fe.h" 1 ::: 572
#pragma line 1 "ed25519/src/fixedint.h" 1 ::: 576
#pragma line 21 "ed25519/src/fixedint.h" ::: 582
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 1 3 ::: 583
#pragma line 1 "/usr/include/limits.h" 1 3 4 ::: 622
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 648
#pragma line 122 "/usr/include/features.h" 3 4 ::: 745
#pragma line 177 "/usr/include/features.h" 3 4 ::: 778
#pragma line 188 "/usr/include/features.h" 3 4 ::: 781
#pragma line 340 "/usr/include/features.h" 3 4 ::: 812
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 816
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 851
#pragma line 343 "/usr/include/features.h" 2 3 4 ::: 860
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 883
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 924
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 930
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 948
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 954
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 958
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 960
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 964
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 974
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 1027
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 1068
#pragma line 351 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 1098
#pragma line 415 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 1122
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1123
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1125
#pragma line 416 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 1127
#pragma line 365 "/usr/include/features.h" 2 3 4 ::: 1128
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 1153
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 1164
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 1169
#pragma line 389 "/usr/include/features.h" 2 3 4 ::: 1170
#pragma line 26 "/usr/include/limits.h" 2 3 4 ::: 1171
#pragma line 116 "/usr/include/limits.h" 3 4 ::: 1182
#pragma line 142 "/usr/include/limits.h" 3 4 ::: 1196
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 1 3 4 ::: 1199
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 1 3 4 ::: 1360
#pragma line 37 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 3 4 ::: 1384
#pragma line 1 "/usr/include/linux/limits.h" 1 3 4 ::: 1387
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 2 3 4 ::: 1388
#pragma line 161 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 2 3 4 ::: 1449
#pragma line 144 "/usr/include/limits.h" 2 3 4 ::: 1459
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 1 3 4 ::: 1463
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 3 4 ::: 1524
#pragma line 148 "/usr/include/limits.h" 2 3 4 ::: 1526
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 1 3 4 ::: 1530
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1564
#pragma line 34 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 2 3 4 ::: 1581
#pragma line 121 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 3 4 ::: 1643
#pragma line 133 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 3 4 ::: 1645
#pragma line 152 "/usr/include/limits.h" 2 3 4 ::: 1647
#pragma line 39 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 2 3 ::: 1648
#pragma line 60 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1653
#pragma line 90 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1655
#pragma line 102 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1657
#pragma line 22 "ed25519/src/fixedint.h" 2 ::: 1662
#pragma line 39 "ed25519/src/fixedint.h" ::: 1670
#pragma line 5 "ed25519/src/fe.h" 2 ::: 1689
#pragma line 3 "ed25519/src/key_exchange.cpp" 2 ::: 1725
