#pragma line 1 "ed25519/src/sha512.cpp" ::: 0
#pragma line 1 "ed25519/src/sha512.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 155 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 11
#pragma line 145 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 64
#pragma line 156 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 67
#pragma line 413 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 197
#pragma line 427 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 200
#pragma line 7 "<command line>" 2 ::: 202
#pragma line 1 "<built-in>" 2 ::: 203
#pragma line 1 "ed25519/src/sha512.cpp" 2 ::: 204
#pragma line 1 "ed25519/src/fixedint.h" 1 ::: 217
#pragma line 21 "ed25519/src/fixedint.h" ::: 223
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 1 3 ::: 224
#pragma line 1 "/usr/include/limits.h" 1 3 4 ::: 263
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 289
#pragma line 122 "/usr/include/features.h" 3 4 ::: 386
#pragma line 177 "/usr/include/features.h" 3 4 ::: 419
#pragma line 188 "/usr/include/features.h" 3 4 ::: 422
#pragma line 340 "/usr/include/features.h" 3 4 ::: 453
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 457
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 492
#pragma line 343 "/usr/include/features.h" 2 3 4 ::: 501
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 524
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 565
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 571
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 589
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 595
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 599
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 601
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 605
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 615
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 668
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 709
#pragma line 351 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 739
#pragma line 415 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 763
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 764
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 766
#pragma line 416 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 768
#pragma line 365 "/usr/include/features.h" 2 3 4 ::: 769
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 794
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 805
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 810
#pragma line 389 "/usr/include/features.h" 2 3 4 ::: 811
#pragma line 26 "/usr/include/limits.h" 2 3 4 ::: 812
#pragma line 116 "/usr/include/limits.h" 3 4 ::: 823
#pragma line 142 "/usr/include/limits.h" 3 4 ::: 837
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 1 3 4 ::: 840
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 1 3 4 ::: 1001
#pragma line 37 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 3 4 ::: 1025
#pragma line 1 "/usr/include/linux/limits.h" 1 3 4 ::: 1028
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 2 3 4 ::: 1029
#pragma line 161 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 2 3 4 ::: 1090
#pragma line 144 "/usr/include/limits.h" 2 3 4 ::: 1100
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 1 3 4 ::: 1104
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 3 4 ::: 1165
#pragma line 148 "/usr/include/limits.h" 2 3 4 ::: 1167
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 1 3 4 ::: 1171
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1205
#pragma line 34 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 2 3 4 ::: 1222
#pragma line 121 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 3 4 ::: 1284
#pragma line 133 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 3 4 ::: 1286
#pragma line 152 "/usr/include/limits.h" 2 3 4 ::: 1288
#pragma line 39 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 2 3 ::: 1289
#pragma line 60 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1294
#pragma line 90 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1296
#pragma line 102 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1298
#pragma line 22 "ed25519/src/fixedint.h" 2 ::: 1303
#pragma line 39 "ed25519/src/fixedint.h" ::: 1311
#pragma line 13 "ed25519/src/sha512.cpp" 2 ::: 1330
#pragma line 1 "ed25519/src/sha512.h" 1 ::: 1331
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 1335
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 1371
#pragma line 5 "ed25519/src/sha512.h" 2 ::: 1374
#pragma line 1 "ed25519/src/fixedint.h" 1 ::: 1376
#pragma line 7 "ed25519/src/sha512.h" 2 ::: 1382
#pragma line 14 "ed25519/src/sha512.cpp" 2 ::: 1400
#pragma line 71 "ed25519/src/sha512.cpp" ::: 1447
#pragma line 95 "ed25519/src/sha512.cpp" ::: 1449
