#pragma line 1 "ed25519/src/sign.cpp" ::: -10
#pragma line 1 "ed25519/src/sign.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 155 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 1
#pragma line 145 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 54
#pragma line 156 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 57
#pragma line 413 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 187
#pragma line 427 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 7 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "ed25519/src/sign.cpp" 2 ::: 194
#pragma line 1 "ed25519/src/ed25519.h" 1 ::: 195
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 199
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 235
#pragma line 5 "ed25519/src/ed25519.h" 2 ::: 238
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/hls_stream.h" 1 ::: 239
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_enum.h" 1 ::: 306
#pragma line 67 "/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/hls_stream.h" 2 ::: 441
#pragma line 6 "ed25519/src/ed25519.h" 2 ::: 547
#pragma line 27 "ed25519/src/ed25519.h" ::: 554
#pragma line 2 "ed25519/src/sign.cpp" 2 ::: 571
#pragma line 1 "ed25519/src/sha512.h" 1 ::: 572
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 576
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 601
#pragma line 5 "ed25519/src/sha512.h" 2 ::: 604
#pragma line 1 "ed25519/src/fixedint.h" 1 ::: 606
#pragma line 21 "ed25519/src/fixedint.h" ::: 612
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 1 3 ::: 613
#pragma line 1 "/usr/include/limits.h" 1 3 4 ::: 652
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 678
#pragma line 122 "/usr/include/features.h" 3 4 ::: 775
#pragma line 177 "/usr/include/features.h" 3 4 ::: 808
#pragma line 188 "/usr/include/features.h" 3 4 ::: 811
#pragma line 340 "/usr/include/features.h" 3 4 ::: 842
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 846
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 881
#pragma line 343 "/usr/include/features.h" 2 3 4 ::: 890
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 913
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 954
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 960
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 978
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 984
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 988
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 990
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 994
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 1004
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 1057
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 1098
#pragma line 351 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 1128
#pragma line 415 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 1152
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1153
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1155
#pragma line 416 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 1157
#pragma line 365 "/usr/include/features.h" 2 3 4 ::: 1158
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 1183
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 1194
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 1199
#pragma line 389 "/usr/include/features.h" 2 3 4 ::: 1200
#pragma line 26 "/usr/include/limits.h" 2 3 4 ::: 1201
#pragma line 116 "/usr/include/limits.h" 3 4 ::: 1212
#pragma line 142 "/usr/include/limits.h" 3 4 ::: 1226
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 1 3 4 ::: 1229
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 1 3 4 ::: 1390
#pragma line 37 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 3 4 ::: 1414
#pragma line 1 "/usr/include/linux/limits.h" 1 3 4 ::: 1417
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 2 3 4 ::: 1418
#pragma line 161 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 2 3 4 ::: 1479
#pragma line 144 "/usr/include/limits.h" 2 3 4 ::: 1489
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 1 3 4 ::: 1493
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 3 4 ::: 1554
#pragma line 148 "/usr/include/limits.h" 2 3 4 ::: 1556
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 1 3 4 ::: 1560
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1594
#pragma line 34 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 2 3 4 ::: 1611
#pragma line 121 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 3 4 ::: 1673
#pragma line 133 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 3 4 ::: 1675
#pragma line 152 "/usr/include/limits.h" 2 3 4 ::: 1677
#pragma line 39 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 2 3 ::: 1678
#pragma line 60 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1683
#pragma line 90 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1685
#pragma line 102 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1687
#pragma line 22 "ed25519/src/fixedint.h" 2 ::: 1692
#pragma line 39 "ed25519/src/fixedint.h" ::: 1700
#pragma line 7 "ed25519/src/sha512.h" 2 ::: 1719
#pragma line 3 "ed25519/src/sign.cpp" 2 ::: 1737
#pragma line 1 "ed25519/src/ge.h" 1 ::: 1738
#pragma line 1 "ed25519/src/fe.h" 1 ::: 1742
#pragma line 1 "ed25519/src/fixedint.h" 1 ::: 1746
#pragma line 5 "ed25519/src/fe.h" 2 ::: 1752
#pragma line 5 "ed25519/src/ge.h" 2 ::: 1788
#pragma line 4 "ed25519/src/sign.cpp" 2 ::: 1857
#pragma line 1 "ed25519/src/sc.h" 1 ::: 1858
#pragma line 5 "ed25519/src/sign.cpp" 2 ::: 1869
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 1871
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1905
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1930
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 1933
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 1935
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1963
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1965
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1967
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 2028
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 2035
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 2053
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 2058
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 2069
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 2138
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 2152
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 2155
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 2156
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 2188
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2204
#pragma line 56 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2229
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 2232
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 2237
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 2259
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 2280
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 2283
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 2294
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 2304
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 2306
#pragma line 1 "/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 2310
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 2359
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 2360
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 2366
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 2368
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 2388
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 2399
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 2440
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 2470
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 2530
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 2545
#pragma line 521 "/usr/include/libio.h" 3 4 ::: 2557
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 2559
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 2565
#pragma line 152 "/usr/include/stdio.h" 3 4 ::: 2618
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 2634
#pragma line 167 "/usr/include/stdio.h" 2 3 4 ::: 2651
#pragma line 207 "/usr/include/stdio.h" 3 4 ::: 2683
#pragma line 299 "/usr/include/stdio.h" 3 4 ::: 2760
#pragma line 469 "/usr/include/stdio.h" 3 4 ::: 2899
#pragma line 529 "/usr/include/stdio.h" 3 4 ::: 2919
#pragma line 796 "/usr/include/stdio.h" 3 4 ::: 3172
#pragma line 820 "/usr/include/stdio.h" 3 4 ::: 3183
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 3220
#pragma line 856 "/usr/include/stdio.h" 2 3 4 ::: 3252
#pragma line 932 "/usr/include/stdio.h" 3 4 ::: 3319
#pragma line 944 "/usr/include/stdio.h" 3 4 ::: 3322
#pragma line 7 "ed25519/src/sign.cpp" 2 ::: 3324
