#pragma line 1 "ed25519/src/verify.cpp" ::: 0
#pragma line 1 "ed25519/src/verify.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 155 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 11
#pragma line 145 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 64
#pragma line 156 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 67
#pragma line 413 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 197
#pragma line 427 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 200
#pragma line 7 "<command line>" 2 ::: 202
#pragma line 1 "<built-in>" 2 ::: 203
#pragma line 1 "ed25519/src/verify.cpp" 2 ::: 204
#pragma line 1 "ed25519/src/ed25519.h" 1 ::: 205
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 209
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 245
#pragma line 5 "ed25519/src/ed25519.h" 2 ::: 248
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/hls_stream.h" 1 ::: 249
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_enum.h" 1 ::: 316
#pragma line 67 "/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/hls_stream.h" 2 ::: 451
#pragma line 6 "ed25519/src/ed25519.h" 2 ::: 557
#pragma line 27 "ed25519/src/ed25519.h" ::: 564
#pragma line 2 "ed25519/src/verify.cpp" 2 ::: 581
#pragma line 1 "ed25519/src/sha512.h" 1 ::: 582
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 ::: 586
#pragma line 56 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 ::: 611
#pragma line 5 "ed25519/src/sha512.h" 2 ::: 614
#pragma line 1 "ed25519/src/fixedint.h" 1 ::: 616
#pragma line 21 "ed25519/src/fixedint.h" ::: 622
#pragma line 1 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 1 3 ::: 623
#pragma line 1 "/usr/include/limits.h" 1 3 4 ::: 662
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 688
#pragma line 122 "/usr/include/features.h" 3 4 ::: 785
#pragma line 177 "/usr/include/features.h" 3 4 ::: 818
#pragma line 188 "/usr/include/features.h" 3 4 ::: 821
#pragma line 340 "/usr/include/features.h" 3 4 ::: 852
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 856
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 891
#pragma line 343 "/usr/include/features.h" 2 3 4 ::: 900
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 923
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 964
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 970
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 988
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 994
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 998
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 1000
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 1004
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 1014
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 1067
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 1108
#pragma line 351 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 1138
#pragma line 415 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 1162
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1163
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1165
#pragma line 416 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 1167
#pragma line 365 "/usr/include/features.h" 2 3 4 ::: 1168
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 1193
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 1204
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 1209
#pragma line 389 "/usr/include/features.h" 2 3 4 ::: 1210
#pragma line 26 "/usr/include/limits.h" 2 3 4 ::: 1211
#pragma line 116 "/usr/include/limits.h" 3 4 ::: 1222
#pragma line 142 "/usr/include/limits.h" 3 4 ::: 1236
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 1 3 4 ::: 1239
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 1 3 4 ::: 1400
#pragma line 37 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 3 4 ::: 1424
#pragma line 1 "/usr/include/linux/limits.h" 1 3 4 ::: 1427
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/local_lim.h" 2 3 4 ::: 1428
#pragma line 161 "/usr/include/x86_64-linux-gnu/bits/posix1_lim.h" 2 3 4 ::: 1489
#pragma line 144 "/usr/include/limits.h" 2 3 4 ::: 1499
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 1 3 4 ::: 1503
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/posix2_lim.h" 3 4 ::: 1564
#pragma line 148 "/usr/include/limits.h" 2 3 4 ::: 1566
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 1 3 4 ::: 1570
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1604
#pragma line 34 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 2 3 4 ::: 1621
#pragma line 121 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 3 4 ::: 1683
#pragma line 133 "/usr/include/x86_64-linux-gnu/bits/xopen_lim.h" 3 4 ::: 1685
#pragma line 152 "/usr/include/limits.h" 2 3 4 ::: 1687
#pragma line 39 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 2 3 ::: 1688
#pragma line 60 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1693
#pragma line 90 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1695
#pragma line 102 "/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/limits.h" 3 ::: 1697
#pragma line 22 "ed25519/src/fixedint.h" 2 ::: 1702
#pragma line 39 "ed25519/src/fixedint.h" ::: 1710
#pragma line 7 "ed25519/src/sha512.h" 2 ::: 1729
#pragma line 3 "ed25519/src/verify.cpp" 2 ::: 1747
#pragma line 1 "ed25519/src/ge.h" 1 ::: 1748
#pragma line 1 "ed25519/src/fe.h" 1 ::: 1752
#pragma line 1 "ed25519/src/fixedint.h" 1 ::: 1756
#pragma line 5 "ed25519/src/fe.h" 2 ::: 1762
#pragma line 5 "ed25519/src/ge.h" 2 ::: 1798
#pragma line 4 "ed25519/src/verify.cpp" 2 ::: 1867
#pragma line 1 "ed25519/src/sc.h" 1 ::: 1868
#pragma line 5 "ed25519/src/verify.cpp" 2 ::: 1879
