set_property SRC_FILE_INFO {cfile:/home/michael/hardware_security/zcu102/root_of_trust/operational_os/vivado/zcu102_pmod/zcu102_pmod.srcs/constrs_1/new/zcu_contraints.xdc rfile:../../../zcu102_pmod.srcs/constrs_1/new/zcu_contraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A20 [get_ports SERIAL_CLK_OUT]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B20 [get_ports SERIAL_DATA_LINE_OUT]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A22 [get_ports SERIAL_DATA_LINE_IN]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A21 [get_ports SERIAL_CLK_EN]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B21 [get_ports SERIAL_DATA_EN]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG14 [get_ports SERIAL_DATA_LED]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF13 [get_ports SERIAL_CLK_LED]
