// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="contact_discovery,hls_ip_2017_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-1-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.619000,HLS_SYN_LAT=5282525,HLS_SYN_TPT=none,HLS_SYN_MEM=249,HLS_SYN_DSP=0,HLS_SYN_FF=5431,HLS_SYN_LUT=7231}" *)

module contact_discovery (
        ap_clk,
        ap_rst_n,
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_pp0_stage0 = 17'd16;
parameter    ap_ST_fsm_state7 = 17'd32;
parameter    ap_ST_fsm_state8 = 17'd64;
parameter    ap_ST_fsm_state9 = 17'd128;
parameter    ap_ST_fsm_state10 = 17'd256;
parameter    ap_ST_fsm_state11 = 17'd512;
parameter    ap_ST_fsm_state12 = 17'd1024;
parameter    ap_ST_fsm_state13 = 17'd2048;
parameter    ap_ST_fsm_state14 = 17'd4096;
parameter    ap_ST_fsm_state15 = 17'd8192;
parameter    ap_ST_fsm_state16 = 17'd16384;
parameter    ap_ST_fsm_state17 = 17'd32768;
parameter    ap_ST_fsm_state18 = 17'd65536;
parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 15;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1:0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
output   interrupt;

reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] operation;
reg   [31:0] operation_preg;
wire    operation_ap_vld;
reg   [31:0] operation_in_sig;
reg    operation_ap_vld_preg;
reg    operation_ap_vld_in_sig;
wire   [5:0] contact_in_address0;
reg    contact_in_ce0;
wire   [7:0] contact_in_q0;
wire   [5:0] database_in_address0;
reg    database_in_ce0;
wire   [7:0] database_in_q0;
wire   [12:0] matched_out_address0;
reg    matched_out_ce0;
reg    matched_out_we0;
reg   [31:0] matched_finished_1_data_reg;
reg   [31:0] matched_finished_1_data_in;
reg    matched_finished_1_vld_reg;
reg    matched_finished_1_vld_in;
reg    matched_finished_1_ack_in;
reg   [31:0] error_out_1_data_reg;
reg   [31:0] error_out_1_data_in;
reg    error_out_1_vld_reg;
reg    error_out_1_vld_in;
reg    error_out_1_ack_in;
reg   [31:0] database_size_out_1_data_reg;
reg   [31:0] database_size_out_1_data_in;
reg    database_size_out_1_vld_reg;
reg    database_size_out_1_vld_in;
reg    database_size_out_1_ack_in;
reg   [31:0] contacts_size_out_1_data_reg;
reg   [31:0] contacts_size_out_1_data_in;
reg    contacts_size_out_1_vld_reg;
reg    contacts_size_out_1_vld_in;
reg    contacts_size_out_1_ack_in;
reg   [31:0] contacts_size;
reg   [31:0] database_size;
reg   [12:0] contacts_address0;
reg    contacts_ce0;
reg    contacts_we0;
wire   [7:0] contacts_q0;
reg    contacts_ce1;
wire   [7:0] contacts_q1;
reg   [18:0] database_address0;
reg    database_ce0;
reg    database_we0;
wire   [7:0] database_q0;
reg    database_ce1;
wire   [7:0] database_q1;
reg   [12:0] results_address0;
reg    results_ce0;
reg    results_we0;
wire   [0:0] results_q0;
reg    operation_blk_n;
reg   [12:0] i_reg_245;
wire   [31:0] operation_read_read_fu_116_p2;
reg    ap_block_state1;
reg   [31:0] contacts_size_load_reg_493;
reg   [31:0] database_size_load_reg_502;
wire   [19:0] tmp_2_cast_fu_344_p3;
reg   [19:0] tmp_2_cast_reg_514;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_7_fu_336_p2;
wire   [14:0] tmp_9_cast_fu_370_p3;
reg   [14:0] tmp_9_cast_reg_522;
wire   [0:0] icmp_fu_361_p2;
wire   [0:0] exitcond2_fu_378_p2;
wire    ap_CS_fsm_state3;
wire   [12:0] database_index_1_fu_384_p2;
reg   [12:0] database_index_1_reg_531;
wire   [0:0] exitcond_fu_390_p2;
reg   [0:0] exitcond_reg_536;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state5_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_flag00011001;
wire   [12:0] i_1_fu_396_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [63:0] tmp_4_fu_402_p1;
reg   [63:0] tmp_4_reg_545;
wire   [6:0] i_3_fu_413_p2;
reg   [6:0] i_3_reg_558;
wire    ap_CS_fsm_state9;
wire   [0:0] exitcond_i5_fu_407_p2;
wire   [19:0] sum_i9_fu_428_p2;
reg   [19:0] sum_i9_reg_568;
wire   [31:0] tmp_3_fu_433_p2;
wire   [6:0] i_2_fu_454_p2;
reg   [6:0] i_2_reg_581;
wire    ap_CS_fsm_state14;
wire   [0:0] exitcond_i_fu_448_p2;
wire   [14:0] sum_i_fu_469_p2;
reg   [14:0] sum_i_reg_591;
wire   [31:0] tmp_s_fu_474_p2;
wire    ap_block_pp0_stage0_flag00011011;
reg    ap_condition_pp0_exit_iter0_state5;
reg    ap_enable_reg_pp0_iter1;
wire    grp_match_db_contact_fu_302_ap_start;
wire    grp_match_db_contact_fu_302_ap_done;
wire    grp_match_db_contact_fu_302_ap_idle;
wire    grp_match_db_contact_fu_302_ap_ready;
wire   [12:0] grp_match_db_contact_fu_302_contacts_address0;
wire    grp_match_db_contact_fu_302_contacts_ce0;
wire   [12:0] grp_match_db_contact_fu_302_contacts_address1;
wire    grp_match_db_contact_fu_302_contacts_ce1;
wire   [18:0] grp_match_db_contact_fu_302_database_address0;
wire    grp_match_db_contact_fu_302_database_ce0;
wire   [18:0] grp_match_db_contact_fu_302_database_address1;
wire    grp_match_db_contact_fu_302_database_ce1;
wire   [12:0] grp_match_db_contact_fu_302_results_address0;
wire    grp_match_db_contact_fu_302_results_ce0;
wire    grp_match_db_contact_fu_302_results_we0;
wire   [0:0] grp_match_db_contact_fu_302_results_d0;
reg   [12:0] database_index_reg_233;
wire    ap_CS_fsm_state4;
reg   [6:0] i_i4_reg_256;
wire    ap_CS_fsm_state10;
reg   [31:0] storemerge_reg_267;
wire    ap_CS_fsm_state11;
reg   [6:0] i_i_reg_279;
wire    ap_CS_fsm_state15;
reg   [31:0] storemerge1_reg_290;
wire    ap_CS_fsm_state16;
reg    ap_reg_grp_match_db_contact_fu_302_ap_start;
wire    ap_block_pp0_stage0_flag00000000;
wire   [63:0] tmp_i6_fu_419_p1;
wire  signed [63:0] sum_i9_cast_fu_444_p1;
wire   [63:0] tmp_i_fu_460_p1;
wire  signed [63:0] sum_i_cast_fu_485_p1;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state12;
wire   [13:0] tmp_128_fu_341_p1;
wire   [24:0] tmp_fu_352_p4;
wire   [8:0] tmp_127_fu_367_p1;
wire   [19:0] tmp_i6_cast_fu_424_p1;
wire   [14:0] tmp_i_cast_fu_465_p1;
wire    ap_CS_fsm_state8;
reg    ap_block_state8;
reg   [16:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 operation_preg = 32'd0;
#0 operation_ap_vld_preg = 1'b0;
#0 matched_finished_1_data_reg = 32'd0;
#0 matched_finished_1_vld_reg = 1'b0;
#0 error_out_1_data_reg = 32'd0;
#0 error_out_1_vld_reg = 1'b0;
#0 database_size_out_1_data_reg = 32'd0;
#0 database_size_out_1_vld_reg = 1'b0;
#0 contacts_size_out_1_data_reg = 32'd0;
#0 contacts_size_out_1_vld_reg = 1'b0;
#0 contacts_size = 32'd0;
#0 database_size = 32'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_reg_grp_match_db_contact_fu_302_ap_start = 1'b0;
end

contact_discoverybkb #(
    .DataWidth( 8 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
contacts_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(contacts_address0),
    .ce0(contacts_ce0),
    .we0(contacts_we0),
    .d0(contact_in_q0),
    .q0(contacts_q0),
    .address1(grp_match_db_contact_fu_302_contacts_address1),
    .ce1(contacts_ce1),
    .q1(contacts_q1)
);

contact_discoverycud #(
    .DataWidth( 8 ),
    .AddressRange( 480000 ),
    .AddressWidth( 19 ))
database_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(database_address0),
    .ce0(database_ce0),
    .we0(database_we0),
    .d0(database_in_q0),
    .q0(database_q0),
    .address1(grp_match_db_contact_fu_302_database_address1),
    .ce1(database_ce1),
    .q1(database_q1)
);

contact_discoverydEe #(
    .DataWidth( 1 ),
    .AddressRange( 7500 ),
    .AddressWidth( 13 ))
results_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(results_address0),
    .ce0(results_ce0),
    .we0(results_we0),
    .d0(grp_match_db_contact_fu_302_results_d0),
    .q0(results_q0)
);

contact_discovery_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
contact_discovery_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .operation(operation),
    .operation_ap_vld(operation_ap_vld),
    .contact_in_address0(contact_in_address0),
    .contact_in_ce0(contact_in_ce0),
    .contact_in_q0(contact_in_q0),
    .database_in_address0(database_in_address0),
    .database_in_ce0(database_in_ce0),
    .database_in_q0(database_in_q0),
    .matched_out_address0(matched_out_address0),
    .matched_out_ce0(matched_out_ce0),
    .matched_out_we0(matched_out_we0),
    .matched_out_d0(results_q0),
    .matched_finished(matched_finished_1_data_reg),
    .error_out(error_out_1_data_reg),
    .database_size_out(database_size_out_1_data_reg),
    .contacts_size_out(contacts_size_out_1_data_reg)
);

match_db_contact grp_match_db_contact_fu_302(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_match_db_contact_fu_302_ap_start),
    .ap_done(grp_match_db_contact_fu_302_ap_done),
    .ap_idle(grp_match_db_contact_fu_302_ap_idle),
    .ap_ready(grp_match_db_contact_fu_302_ap_ready),
    .database_index(database_index_reg_233),
    .contacts_address0(grp_match_db_contact_fu_302_contacts_address0),
    .contacts_ce0(grp_match_db_contact_fu_302_contacts_ce0),
    .contacts_q0(contacts_q0),
    .contacts_address1(grp_match_db_contact_fu_302_contacts_address1),
    .contacts_ce1(grp_match_db_contact_fu_302_contacts_ce1),
    .contacts_q1(contacts_q1),
    .database_address0(grp_match_db_contact_fu_302_database_address0),
    .database_ce0(grp_match_db_contact_fu_302_database_ce0),
    .database_q0(database_q0),
    .database_address1(grp_match_db_contact_fu_302_database_address1),
    .database_ce1(grp_match_db_contact_fu_302_database_ce1),
    .database_q1(database_q1),
    .results_address0(grp_match_db_contact_fu_302_results_address0),
    .results_ce0(grp_match_db_contact_fu_302_results_ce0),
    .results_we0(grp_match_db_contact_fu_302_results_we0),
    .results_d0(grp_match_db_contact_fu_302_results_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (1'b1 == ap_condition_pp0_exit_iter0_state5))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & (exitcond2_fu_378_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((ap_block_pp0_stage0_flag00011011 == 1'b0) & (1'b1 == ap_condition_pp0_exit_iter0_state5))) begin
            ap_enable_reg_pp0_iter1 <= (ap_condition_pp0_exit_iter0_state5 ^ 1'b1);
        end else if ((ap_block_pp0_stage0_flag00011011 == 1'b0)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state3) & (exitcond2_fu_378_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_grp_match_db_contact_fu_302_ap_start <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & (1'd0 == exitcond2_fu_378_p2))) begin
            ap_reg_grp_match_db_contact_fu_302_ap_start <= 1'b1;
        end else if ((1'b1 == grp_match_db_contact_fu_302_ap_ready)) begin
            ap_reg_grp_match_db_contact_fu_302_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        operation_ap_vld_preg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state8) & ~((1'b0 == matched_finished_1_ack_in) | (1'b0 == error_out_1_ack_in) | (1'b0 == database_size_out_1_ack_in) | (1'b0 == contacts_size_out_1_ack_in)))) begin
            operation_ap_vld_preg <= 1'b0;
        end else if (((1'b1 == operation_ap_vld) & ~((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1)))) begin
            operation_ap_vld_preg <= operation_ap_vld;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        operation_preg <= 32'd0;
    end else begin
        if (((1'b1 == operation_ap_vld) & ~((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1)))) begin
            operation_preg <= operation;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (1'd1 == exitcond_i_fu_448_p2))) begin
        contacts_size <= tmp_s_fu_474_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd4))) begin
        contacts_size <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_match_db_contact_fu_302_ap_done == 1'b1))) begin
        database_index_reg_233 <= database_index_1_reg_531;
    end else if (((1'b1 == ap_CS_fsm_state2) & (operation_read_read_fu_116_p2 == 32'd2))) begin
        database_index_reg_233 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (exitcond_i5_fu_407_p2 == 1'd1))) begin
        database_size <= tmp_3_fu_433_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd3))) begin
        database_size <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        i_i4_reg_256 <= i_3_reg_558;
    end else if (((1'b1 == ap_CS_fsm_state2) & (operation_read_read_fu_116_p2 == 32'd1) & (tmp_7_fu_336_p2 == 1'd0))) begin
        i_i4_reg_256 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        i_i_reg_279 <= i_2_reg_581;
    end else if (((1'b1 == ap_CS_fsm_state2) & (32'd0 == operation_read_read_fu_116_p2) & (1'd0 == icmp_fu_361_p2))) begin
        i_i_reg_279 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (exitcond2_fu_378_p2 == 1'd1))) begin
        i_reg_245 <= 13'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == exitcond_fu_390_p2))) begin
        i_reg_245 <= i_1_fu_396_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        storemerge1_reg_290 <= contacts_size_load_reg_493;
    end else if (((1'b1 == ap_CS_fsm_state14) & (1'd1 == exitcond_i_fu_448_p2))) begin
        storemerge1_reg_290 <= tmp_s_fu_474_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        storemerge_reg_267 <= database_size_load_reg_502;
    end else if (((1'b1 == ap_CS_fsm_state9) & (exitcond_i5_fu_407_p2 == 1'd1))) begin
        storemerge_reg_267 <= tmp_3_fu_433_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)))) begin
        contacts_size_load_reg_493 <= contacts_size;
        database_size_load_reg_502 <= database_size;
    end
end

always @ (posedge ap_clk) begin
    if (((~((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == contacts_size_out_1_vld_in) & (1'b0 == contacts_size_out_1_vld_reg)) | (~((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == contacts_size_out_1_vld_in) & (1'b1 == contacts_size_out_1_vld_reg) & (1'b1 == 1'b1)))) begin
        contacts_size_out_1_data_reg <= contacts_size_out_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        database_index_1_reg_531 <= database_index_1_fu_384_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((~((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == database_size_out_1_vld_in) & (1'b0 == database_size_out_1_vld_reg)) | (~((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == database_size_out_1_vld_in) & (1'b1 == database_size_out_1_vld_reg) & (1'b1 == 1'b1)))) begin
        database_size_out_1_data_reg <= database_size_out_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if (((~((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == error_out_1_vld_in) & (1'b0 == error_out_1_vld_reg)) | (~((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == error_out_1_vld_in) & (1'b1 == error_out_1_vld_reg) & (1'b1 == 1'b1)))) begin
        error_out_1_data_reg <= error_out_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        exitcond_reg_536 <= exitcond_fu_390_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        i_2_reg_581 <= i_2_fu_454_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        i_3_reg_558 <= i_3_fu_413_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((~((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == matched_finished_1_vld_in) & (1'b0 == matched_finished_1_vld_reg)) | (~((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == matched_finished_1_vld_in) & (1'b1 == matched_finished_1_vld_reg) & (1'b1 == 1'b1)))) begin
        matched_finished_1_data_reg <= matched_finished_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (1'd0 == exitcond_i5_fu_407_p2))) begin
        sum_i9_reg_568 <= sum_i9_fu_428_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (1'd0 == exitcond_i_fu_448_p2))) begin
        sum_i_reg_591 <= sum_i_fu_469_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (operation_read_read_fu_116_p2 == 32'd1) & (tmp_7_fu_336_p2 == 1'd0))) begin
        tmp_2_cast_reg_514[19 : 6] <= tmp_2_cast_fu_344_p3[19 : 6];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == exitcond_fu_390_p2))) begin
        tmp_4_reg_545[12 : 0] <= tmp_4_fu_402_p1[12 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (32'd0 == operation_read_read_fu_116_p2) & (1'd0 == icmp_fu_361_p2))) begin
        tmp_9_cast_reg_522[14 : 6] <= tmp_9_cast_fu_370_p3[14 : 6];
    end
end

always @ (*) begin
    if ((exitcond_fu_390_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & ~((1'b0 == matched_finished_1_ack_in) | (1'b0 == error_out_1_ack_in) | (1'b0 == database_size_out_1_ack_in) | (1'b0 == contacts_size_out_1_ack_in)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & ~((1'b0 == matched_finished_1_ack_in) | (1'b0 == error_out_1_ack_in) | (1'b0 == database_size_out_1_ack_in) | (1'b0 == contacts_size_out_1_ack_in)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        contact_in_ce0 = 1'b1;
    end else begin
        contact_in_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        contacts_address0 = sum_i_cast_fu_485_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        contacts_address0 = grp_match_db_contact_fu_302_contacts_address0;
    end else begin
        contacts_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        contacts_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        contacts_ce0 = grp_match_db_contact_fu_302_contacts_ce0;
    end else begin
        contacts_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        contacts_ce1 = grp_match_db_contact_fu_302_contacts_ce1;
    end else begin
        contacts_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == contacts_size_out_1_vld_reg) | ((1'b1 == contacts_size_out_1_vld_reg) & (1'b1 == 1'b1)))) begin
        contacts_size_out_1_ack_in = 1'b1;
    end else begin
        contacts_size_out_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        contacts_size_out_1_data_in = storemerge1_reg_290;
    end else if ((((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd3)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & ~(32'd0 == operation_read_read_fu_116_p2) & ~(operation_read_read_fu_116_p2 == 32'd1) & ~(operation_read_read_fu_116_p2 == 32'd2) & ~(operation_read_read_fu_116_p2 == 32'd3) & ~(operation_read_read_fu_116_p2 == 32'd4)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd2)))) begin
        contacts_size_out_1_data_in = contacts_size;
    end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd4))) begin
        contacts_size_out_1_data_in = 32'd0;
    end else begin
        contacts_size_out_1_data_in = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd4)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd3)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & ~(32'd0 == operation_read_read_fu_116_p2) & ~(operation_read_read_fu_116_p2 == 32'd1) & ~(operation_read_read_fu_116_p2 == 32'd2) & ~(operation_read_read_fu_116_p2 == 32'd3) & ~(operation_read_read_fu_116_p2 == 32'd4)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd2)) | (1'b1 == ap_CS_fsm_state17))) begin
        contacts_size_out_1_vld_in = 1'b1;
    end else begin
        contacts_size_out_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        contacts_we0 = 1'b1;
    end else begin
        contacts_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        database_address0 = sum_i9_cast_fu_444_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        database_address0 = grp_match_db_contact_fu_302_database_address0;
    end else begin
        database_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        database_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        database_ce0 = grp_match_db_contact_fu_302_database_ce0;
    end else begin
        database_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        database_ce1 = grp_match_db_contact_fu_302_database_ce1;
    end else begin
        database_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        database_in_ce0 = 1'b1;
    end else begin
        database_in_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == database_size_out_1_vld_reg) | ((1'b1 == database_size_out_1_vld_reg) & (1'b1 == 1'b1)))) begin
        database_size_out_1_ack_in = 1'b1;
    end else begin
        database_size_out_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        database_size_out_1_data_in = storemerge_reg_267;
    end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd3))) begin
        database_size_out_1_data_in = 32'd0;
    end else if ((((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd4)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (32'd0 == operation_read_read_fu_116_p2)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & ~(32'd0 == operation_read_read_fu_116_p2) & ~(operation_read_read_fu_116_p2 == 32'd1) & ~(operation_read_read_fu_116_p2 == 32'd2) & ~(operation_read_read_fu_116_p2 == 32'd3) & ~(operation_read_read_fu_116_p2 == 32'd4)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd2)))) begin
        database_size_out_1_data_in = database_size;
    end else begin
        database_size_out_1_data_in = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd4)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd3)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (32'd0 == operation_read_read_fu_116_p2)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & ~(32'd0 == operation_read_read_fu_116_p2) & ~(operation_read_read_fu_116_p2 == 32'd1) & ~(operation_read_read_fu_116_p2 == 32'd2) & ~(operation_read_read_fu_116_p2 == 32'd3) & ~(operation_read_read_fu_116_p2 == 32'd4)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd2)) | (1'b1 == ap_CS_fsm_state12))) begin
        database_size_out_1_vld_in = 1'b1;
    end else begin
        database_size_out_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        database_we0 = 1'b1;
    end else begin
        database_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == error_out_1_vld_reg) | ((1'b1 == error_out_1_vld_reg) & (1'b1 == 1'b1)))) begin
        error_out_1_ack_in = 1'b1;
    end else begin
        error_out_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (32'd0 == operation_read_read_fu_116_p2) & (icmp_fu_361_p2 == 1'd1))) begin
        error_out_1_data_in = 32'd1;
    end else if (((1'b1 == ap_CS_fsm_state2) & (operation_read_read_fu_116_p2 == 32'd1) & (tmp_7_fu_336_p2 == 1'd1))) begin
        error_out_1_data_in = 32'd2;
    end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & ~(32'd0 == operation_read_read_fu_116_p2) & ~(operation_read_read_fu_116_p2 == 32'd1) & ~(operation_read_read_fu_116_p2 == 32'd2) & ~(operation_read_read_fu_116_p2 == 32'd3) & ~(operation_read_read_fu_116_p2 == 32'd4))) begin
        error_out_1_data_in = 32'd3;
    end else if ((((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd4)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd3)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd1)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (32'd0 == operation_read_read_fu_116_p2)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd2)))) begin
        error_out_1_data_in = 32'd0;
    end else begin
        error_out_1_data_in = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd4)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd3)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd1)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (32'd0 == operation_read_read_fu_116_p2)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & ~(32'd0 == operation_read_read_fu_116_p2) & ~(operation_read_read_fu_116_p2 == 32'd1) & ~(operation_read_read_fu_116_p2 == 32'd2) & ~(operation_read_read_fu_116_p2 == 32'd3) & ~(operation_read_read_fu_116_p2 == 32'd4)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd2)) | ((1'b1 == ap_CS_fsm_state2) & (operation_read_read_fu_116_p2 == 32'd1) & (tmp_7_fu_336_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (32'd0 == operation_read_read_fu_116_p2) & (icmp_fu_361_p2 == 1'd1)))) begin
        error_out_1_vld_in = 1'b1;
    end else begin
        error_out_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == matched_finished_1_vld_reg) | ((1'b1 == matched_finished_1_vld_reg) & (1'b1 == 1'b1)))) begin
        matched_finished_1_ack_in = 1'b1;
    end else begin
        matched_finished_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        matched_finished_1_data_in = 32'd1;
    end else if ((((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd4)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd3)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd1)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (32'd0 == operation_read_read_fu_116_p2)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & ~(32'd0 == operation_read_read_fu_116_p2) & ~(operation_read_read_fu_116_p2 == 32'd1) & ~(operation_read_read_fu_116_p2 == 32'd2) & ~(operation_read_read_fu_116_p2 == 32'd3) & ~(operation_read_read_fu_116_p2 == 32'd4)))) begin
        matched_finished_1_data_in = 32'd0;
    end else begin
        matched_finished_1_data_in = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd4)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd3)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (operation_read_read_fu_116_p2 == 32'd1)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & (32'd0 == operation_read_read_fu_116_p2)) | ((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)) & ~(32'd0 == operation_read_read_fu_116_p2) & ~(operation_read_read_fu_116_p2 == 32'd1) & ~(operation_read_read_fu_116_p2 == 32'd2) & ~(operation_read_read_fu_116_p2 == 32'd3) & ~(operation_read_read_fu_116_p2 == 32'd4)) | (1'b1 == ap_CS_fsm_state7))) begin
        matched_finished_1_vld_in = 1'b1;
    end else begin
        matched_finished_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        matched_out_ce0 = 1'b1;
    end else begin
        matched_out_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd0 == exitcond_reg_536))) begin
        matched_out_we0 = 1'b1;
    end else begin
        matched_out_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == operation_ap_vld)) begin
        operation_ap_vld_in_sig = operation_ap_vld;
    end else begin
        operation_ap_vld_in_sig = operation_ap_vld_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        operation_blk_n = operation_ap_vld;
    end else begin
        operation_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == operation_ap_vld)) begin
        operation_in_sig = operation;
    end else begin
        operation_in_sig = operation_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage0_flag00000000 == 1'b0))) begin
        results_address0 = tmp_4_fu_402_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        results_address0 = grp_match_db_contact_fu_302_results_address0;
    end else begin
        results_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        results_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        results_ce0 = grp_match_db_contact_fu_302_results_ce0;
    end else begin
        results_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        results_we0 = grp_match_db_contact_fu_302_results_we0;
    end else begin
        results_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig)))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (32'd0 == operation_read_read_fu_116_p2) & (1'd0 == icmp_fu_361_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else if (((1'b1 == ap_CS_fsm_state2) & (32'd0 == operation_read_read_fu_116_p2) & (icmp_fu_361_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else if (((1'b1 == ap_CS_fsm_state2) & (operation_read_read_fu_116_p2 == 32'd1) & (tmp_7_fu_336_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((1'b1 == ap_CS_fsm_state2) & (operation_read_read_fu_116_p2 == 32'd1) & (tmp_7_fu_336_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if (((1'b1 == ap_CS_fsm_state2) & (operation_read_read_fu_116_p2 == 32'd2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (exitcond2_fu_378_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_match_db_contact_fu_302_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (exitcond_fu_390_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (exitcond_fu_390_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & ~((1'b0 == matched_finished_1_ack_in) | (1'b0 == error_out_1_ack_in) | (1'b0 == database_size_out_1_ack_in) | (1'b0 == contacts_size_out_1_ack_in)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (exitcond_i5_fu_407_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state14 : begin
            if (((1'b1 == ap_CS_fsm_state14) & (1'd1 == exitcond_i_fu_448_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0_flag00000000 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_flag00011001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_flag00011011 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1 = ((1'b0 == ap_start) | (1'b0 == operation_ap_vld_in_sig));
end

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8 = ((1'b0 == matched_finished_1_ack_in) | (1'b0 == error_out_1_ack_in) | (1'b0 == database_size_out_1_ack_in) | (1'b0 == contacts_size_out_1_ack_in));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign contact_in_address0 = tmp_i_fu_460_p1;

assign database_in_address0 = tmp_i6_fu_419_p1;

assign database_index_1_fu_384_p2 = (database_index_reg_233 + 13'd1);

assign exitcond2_fu_378_p2 = ((database_index_reg_233 == 13'd7500) ? 1'b1 : 1'b0);

assign exitcond_fu_390_p2 = ((i_reg_245 == 13'd7500) ? 1'b1 : 1'b0);

assign exitcond_i5_fu_407_p2 = ((i_i4_reg_256 == 7'd64) ? 1'b1 : 1'b0);

assign exitcond_i_fu_448_p2 = ((i_i_reg_279 == 7'd64) ? 1'b1 : 1'b0);

assign grp_match_db_contact_fu_302_ap_start = ap_reg_grp_match_db_contact_fu_302_ap_start;

assign i_1_fu_396_p2 = (i_reg_245 + 13'd1);

assign i_2_fu_454_p2 = (i_i_reg_279 + 7'd1);

assign i_3_fu_413_p2 = (i_i4_reg_256 + 7'd1);

assign icmp_fu_361_p2 = (($signed(tmp_fu_352_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign matched_out_address0 = tmp_4_reg_545;

assign operation_read_read_fu_116_p2 = operation_in_sig;

assign sum_i9_cast_fu_444_p1 = $signed(sum_i9_reg_568);

assign sum_i9_fu_428_p2 = (tmp_i6_cast_fu_424_p1 + tmp_2_cast_reg_514);

assign sum_i_cast_fu_485_p1 = $signed(sum_i_reg_591);

assign sum_i_fu_469_p2 = (tmp_i_cast_fu_465_p1 + tmp_9_cast_reg_522);

assign tmp_127_fu_367_p1 = contacts_size_load_reg_493[8:0];

assign tmp_128_fu_341_p1 = database_size_load_reg_502[13:0];

assign tmp_2_cast_fu_344_p3 = {{tmp_128_fu_341_p1}, {6'd0}};

assign tmp_3_fu_433_p2 = (database_size_load_reg_502 + 32'd1);

assign tmp_4_fu_402_p1 = i_reg_245;

assign tmp_7_fu_336_p2 = (($signed(database_size_load_reg_502) > $signed(32'd7499)) ? 1'b1 : 1'b0);

assign tmp_9_cast_fu_370_p3 = {{tmp_127_fu_367_p1}, {6'd0}};

assign tmp_fu_352_p4 = {{contacts_size_load_reg_493[31:7]}};

assign tmp_i6_cast_fu_424_p1 = i_i4_reg_256;

assign tmp_i6_fu_419_p1 = i_i4_reg_256;

assign tmp_i_cast_fu_465_p1 = i_i_reg_279;

assign tmp_i_fu_460_p1 = i_i_reg_279;

assign tmp_s_fu_474_p2 = (contacts_size_load_reg_493 + 32'd1);

always @ (posedge ap_clk) begin
    tmp_2_cast_reg_514[5:0] <= 6'b000000;
    tmp_9_cast_reg_522[5:0] <= 6'b000000;
    tmp_4_reg_545[63:13] <= 51'b000000000000000000000000000000000000000000000000000;
end

endmodule //contact_discovery
